// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountdailyfinancialvalue"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountDailyFinancialValueDelete is the builder for deleting a AccountDailyFinancialValue entity.
type AccountDailyFinancialValueDelete struct {
	config
	hooks    []Hook
	mutation *AccountDailyFinancialValueMutation
}

// Where appends a list predicates to the AccountDailyFinancialValueDelete builder.
func (_d *AccountDailyFinancialValueDelete) Where(ps ...predicate.AccountDailyFinancialValue) *AccountDailyFinancialValueDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountDailyFinancialValueDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountDailyFinancialValueDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountDailyFinancialValueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountdailyfinancialvalue.Table, sqlgraph.NewFieldSpec(accountdailyfinancialvalue.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountDailyFinancialValueDeleteOne is the builder for deleting a single AccountDailyFinancialValue entity.
type AccountDailyFinancialValueDeleteOne struct {
	_d *AccountDailyFinancialValueDelete
}

// Where appends a list predicates to the AccountDailyFinancialValueDelete builder.
func (_d *AccountDailyFinancialValueDeleteOne) Where(ps ...predicate.AccountDailyFinancialValue) *AccountDailyFinancialValueDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountDailyFinancialValueDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountdailyfinancialvalue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountDailyFinancialValueDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
