// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountdailyfinancialvalue"
)

// AccountDailyFinancialValueCreate is the builder for creating a AccountDailyFinancialValue entity.
type AccountDailyFinancialValueCreate struct {
	config
	mutation *AccountDailyFinancialValueMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountDailyFinancialValueCreate) SetAccountID(v int64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetBusinessDate sets the "business_date" field.
func (_c *AccountDailyFinancialValueCreate) SetBusinessDate(v time.Time) *AccountDailyFinancialValueCreate {
	_c.mutation.SetBusinessDate(v)
	return _c
}

// SetOauthCostCny sets the "oauth_cost_cny" field.
func (_c *AccountDailyFinancialValueCreate) SetOauthCostCny(v float64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetOauthCostCny(v)
	return _c
}

// SetNillableOauthCostCny sets the "oauth_cost_cny" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableOauthCostCny(v *float64) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetOauthCostCny(*v)
	}
	return _c
}

// SetRevenueOverrideCny sets the "revenue_override_cny" field.
func (_c *AccountDailyFinancialValueCreate) SetRevenueOverrideCny(v float64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetRevenueOverrideCny(v)
	return _c
}

// SetNillableRevenueOverrideCny sets the "revenue_override_cny" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableRevenueOverrideCny(v *float64) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetRevenueOverrideCny(*v)
	}
	return _c
}

// SetRevenueOverrideAt sets the "revenue_override_at" field.
func (_c *AccountDailyFinancialValueCreate) SetRevenueOverrideAt(v time.Time) *AccountDailyFinancialValueCreate {
	_c.mutation.SetRevenueOverrideAt(v)
	return _c
}

// SetNillableRevenueOverrideAt sets the "revenue_override_at" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableRevenueOverrideAt(v *time.Time) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetRevenueOverrideAt(*v)
	}
	return _c
}

// SetRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field.
func (_c *AccountDailyFinancialValueCreate) SetRevenueEvidenceCutoffID(v int64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetRevenueEvidenceCutoffID(v)
	return _c
}

// SetNillableRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableRevenueEvidenceCutoffID(v *int64) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetRevenueEvidenceCutoffID(*v)
	}
	return _c
}

// SetRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field.
func (_c *AccountDailyFinancialValueCreate) SetRevenueReviewCutoffID(v int64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetRevenueReviewCutoffID(v)
	return _c
}

// SetNillableRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableRevenueReviewCutoffID(v *int64) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetRevenueReviewCutoffID(*v)
	}
	return _c
}

// SetCostOverrideCny sets the "cost_override_cny" field.
func (_c *AccountDailyFinancialValueCreate) SetCostOverrideCny(v float64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetCostOverrideCny(v)
	return _c
}

// SetNillableCostOverrideCny sets the "cost_override_cny" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableCostOverrideCny(v *float64) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetCostOverrideCny(*v)
	}
	return _c
}

// SetCostOverrideAt sets the "cost_override_at" field.
func (_c *AccountDailyFinancialValueCreate) SetCostOverrideAt(v time.Time) *AccountDailyFinancialValueCreate {
	_c.mutation.SetCostOverrideAt(v)
	return _c
}

// SetNillableCostOverrideAt sets the "cost_override_at" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableCostOverrideAt(v *time.Time) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetCostOverrideAt(*v)
	}
	return _c
}

// SetCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field.
func (_c *AccountDailyFinancialValueCreate) SetCostEvidenceCutoffID(v int64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetCostEvidenceCutoffID(v)
	return _c
}

// SetNillableCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableCostEvidenceCutoffID(v *int64) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetCostEvidenceCutoffID(*v)
	}
	return _c
}

// SetCostReviewCutoffID sets the "cost_review_cutoff_id" field.
func (_c *AccountDailyFinancialValueCreate) SetCostReviewCutoffID(v int64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetCostReviewCutoffID(v)
	return _c
}

// SetNillableCostReviewCutoffID sets the "cost_review_cutoff_id" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableCostReviewCutoffID(v *int64) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetCostReviewCutoffID(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *AccountDailyFinancialValueCreate) SetUpdatedBy(v int64) *AccountDailyFinancialValueCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountDailyFinancialValueCreate) SetCreatedAt(v time.Time) *AccountDailyFinancialValueCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableCreatedAt(v *time.Time) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountDailyFinancialValueCreate) SetUpdatedAt(v time.Time) *AccountDailyFinancialValueCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountDailyFinancialValueCreate) SetNillableUpdatedAt(v *time.Time) *AccountDailyFinancialValueCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountDailyFinancialValueCreate) SetAccount(v *Account) *AccountDailyFinancialValueCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the AccountDailyFinancialValueMutation object of the builder.
func (_c *AccountDailyFinancialValueCreate) Mutation() *AccountDailyFinancialValueMutation {
	return _c.mutation
}

// Save creates the AccountDailyFinancialValue in the database.
func (_c *AccountDailyFinancialValueCreate) Save(ctx context.Context) (*AccountDailyFinancialValue, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountDailyFinancialValueCreate) SaveX(ctx context.Context) *AccountDailyFinancialValue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountDailyFinancialValueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountDailyFinancialValueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountDailyFinancialValueCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountdailyfinancialvalue.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountdailyfinancialvalue.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountDailyFinancialValueCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountDailyFinancialValue.account_id"`)}
	}
	if _, ok := _c.mutation.BusinessDate(); !ok {
		return &ValidationError{Name: "business_date", err: errors.New(`ent: missing required field "AccountDailyFinancialValue.business_date"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "AccountDailyFinancialValue.updated_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountDailyFinancialValue.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountDailyFinancialValue.updated_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountDailyFinancialValue.account"`)}
	}
	return nil
}

func (_c *AccountDailyFinancialValueCreate) sqlSave(ctx context.Context) (*AccountDailyFinancialValue, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountDailyFinancialValueCreate) createSpec() (*AccountDailyFinancialValue, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountDailyFinancialValue{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountdailyfinancialvalue.Table, sqlgraph.NewFieldSpec(accountdailyfinancialvalue.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BusinessDate(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldBusinessDate, field.TypeTime, value)
		_node.BusinessDate = value
	}
	if value, ok := _c.mutation.OauthCostCny(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldOauthCostCny, field.TypeFloat64, value)
		_node.OauthCostCny = &value
	}
	if value, ok := _c.mutation.RevenueOverrideCny(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldRevenueOverrideCny, field.TypeFloat64, value)
		_node.RevenueOverrideCny = &value
	}
	if value, ok := _c.mutation.RevenueOverrideAt(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldRevenueOverrideAt, field.TypeTime, value)
		_node.RevenueOverrideAt = &value
	}
	if value, ok := _c.mutation.RevenueEvidenceCutoffID(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldRevenueEvidenceCutoffID, field.TypeInt64, value)
		_node.RevenueEvidenceCutoffID = &value
	}
	if value, ok := _c.mutation.RevenueReviewCutoffID(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldRevenueReviewCutoffID, field.TypeInt64, value)
		_node.RevenueReviewCutoffID = &value
	}
	if value, ok := _c.mutation.CostOverrideCny(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldCostOverrideCny, field.TypeFloat64, value)
		_node.CostOverrideCny = &value
	}
	if value, ok := _c.mutation.CostOverrideAt(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldCostOverrideAt, field.TypeTime, value)
		_node.CostOverrideAt = &value
	}
	if value, ok := _c.mutation.CostEvidenceCutoffID(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldCostEvidenceCutoffID, field.TypeInt64, value)
		_node.CostEvidenceCutoffID = &value
	}
	if value, ok := _c.mutation.CostReviewCutoffID(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldCostReviewCutoffID, field.TypeInt64, value)
		_node.CostReviewCutoffID = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountdailyfinancialvalue.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountdailyfinancialvalue.AccountTable,
			Columns: []string{accountdailyfinancialvalue.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountDailyFinancialValue.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountDailyFinancialValueUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountDailyFinancialValueCreate) OnConflict(opts ...sql.ConflictOption) *AccountDailyFinancialValueUpsertOne {
	_c.conflict = opts
	return &AccountDailyFinancialValueUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountDailyFinancialValue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountDailyFinancialValueCreate) OnConflictColumns(columns ...string) *AccountDailyFinancialValueUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountDailyFinancialValueUpsertOne{
		create: _c,
	}
}

type (
	// AccountDailyFinancialValueUpsertOne is the builder for "upsert"-ing
	//  one AccountDailyFinancialValue node.
	AccountDailyFinancialValueUpsertOne struct {
		create *AccountDailyFinancialValueCreate
	}

	// AccountDailyFinancialValueUpsert is the "OnConflict" setter.
	AccountDailyFinancialValueUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountDailyFinancialValueUpsert) SetAccountID(v int64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateAccountID() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldAccountID)
	return u
}

// SetBusinessDate sets the "business_date" field.
func (u *AccountDailyFinancialValueUpsert) SetBusinessDate(v time.Time) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldBusinessDate, v)
	return u
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateBusinessDate() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldBusinessDate)
	return u
}

// SetOauthCostCny sets the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsert) SetOauthCostCny(v float64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldOauthCostCny, v)
	return u
}

// UpdateOauthCostCny sets the "oauth_cost_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateOauthCostCny() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldOauthCostCny)
	return u
}

// AddOauthCostCny adds v to the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsert) AddOauthCostCny(v float64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldOauthCostCny, v)
	return u
}

// ClearOauthCostCny clears the value of the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsert) ClearOauthCostCny() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldOauthCostCny)
	return u
}

// SetRevenueOverrideCny sets the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsert) SetRevenueOverrideCny(v float64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldRevenueOverrideCny, v)
	return u
}

// UpdateRevenueOverrideCny sets the "revenue_override_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateRevenueOverrideCny() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldRevenueOverrideCny)
	return u
}

// AddRevenueOverrideCny adds v to the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsert) AddRevenueOverrideCny(v float64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldRevenueOverrideCny, v)
	return u
}

// ClearRevenueOverrideCny clears the value of the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsert) ClearRevenueOverrideCny() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldRevenueOverrideCny)
	return u
}

// SetRevenueOverrideAt sets the "revenue_override_at" field.
func (u *AccountDailyFinancialValueUpsert) SetRevenueOverrideAt(v time.Time) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldRevenueOverrideAt, v)
	return u
}

// UpdateRevenueOverrideAt sets the "revenue_override_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateRevenueOverrideAt() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldRevenueOverrideAt)
	return u
}

// ClearRevenueOverrideAt clears the value of the "revenue_override_at" field.
func (u *AccountDailyFinancialValueUpsert) ClearRevenueOverrideAt() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldRevenueOverrideAt)
	return u
}

// SetRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) SetRevenueEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldRevenueEvidenceCutoffID, v)
	return u
}

// UpdateRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateRevenueEvidenceCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldRevenueEvidenceCutoffID)
	return u
}

// AddRevenueEvidenceCutoffID adds v to the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) AddRevenueEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldRevenueEvidenceCutoffID, v)
	return u
}

// ClearRevenueEvidenceCutoffID clears the value of the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) ClearRevenueEvidenceCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldRevenueEvidenceCutoffID)
	return u
}

// SetRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) SetRevenueReviewCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldRevenueReviewCutoffID, v)
	return u
}

// UpdateRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateRevenueReviewCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldRevenueReviewCutoffID)
	return u
}

// AddRevenueReviewCutoffID adds v to the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) AddRevenueReviewCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldRevenueReviewCutoffID, v)
	return u
}

// ClearRevenueReviewCutoffID clears the value of the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) ClearRevenueReviewCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldRevenueReviewCutoffID)
	return u
}

// SetCostOverrideCny sets the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsert) SetCostOverrideCny(v float64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldCostOverrideCny, v)
	return u
}

// UpdateCostOverrideCny sets the "cost_override_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateCostOverrideCny() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldCostOverrideCny)
	return u
}

// AddCostOverrideCny adds v to the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsert) AddCostOverrideCny(v float64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldCostOverrideCny, v)
	return u
}

// ClearCostOverrideCny clears the value of the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsert) ClearCostOverrideCny() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldCostOverrideCny)
	return u
}

// SetCostOverrideAt sets the "cost_override_at" field.
func (u *AccountDailyFinancialValueUpsert) SetCostOverrideAt(v time.Time) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldCostOverrideAt, v)
	return u
}

// UpdateCostOverrideAt sets the "cost_override_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateCostOverrideAt() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldCostOverrideAt)
	return u
}

// ClearCostOverrideAt clears the value of the "cost_override_at" field.
func (u *AccountDailyFinancialValueUpsert) ClearCostOverrideAt() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldCostOverrideAt)
	return u
}

// SetCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) SetCostEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldCostEvidenceCutoffID, v)
	return u
}

// UpdateCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateCostEvidenceCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldCostEvidenceCutoffID)
	return u
}

// AddCostEvidenceCutoffID adds v to the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) AddCostEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldCostEvidenceCutoffID, v)
	return u
}

// ClearCostEvidenceCutoffID clears the value of the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) ClearCostEvidenceCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldCostEvidenceCutoffID)
	return u
}

// SetCostReviewCutoffID sets the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) SetCostReviewCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldCostReviewCutoffID, v)
	return u
}

// UpdateCostReviewCutoffID sets the "cost_review_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateCostReviewCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldCostReviewCutoffID)
	return u
}

// AddCostReviewCutoffID adds v to the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) AddCostReviewCutoffID(v int64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldCostReviewCutoffID, v)
	return u
}

// ClearCostReviewCutoffID clears the value of the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsert) ClearCostReviewCutoffID() *AccountDailyFinancialValueUpsert {
	u.SetNull(accountdailyfinancialvalue.FieldCostReviewCutoffID)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AccountDailyFinancialValueUpsert) SetUpdatedBy(v int64) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateUpdatedBy() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AccountDailyFinancialValueUpsert) AddUpdatedBy(v int64) *AccountDailyFinancialValueUpsert {
	u.Add(accountdailyfinancialvalue.FieldUpdatedBy, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountDailyFinancialValueUpsert) SetUpdatedAt(v time.Time) *AccountDailyFinancialValueUpsert {
	u.Set(accountdailyfinancialvalue.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsert) UpdateUpdatedAt() *AccountDailyFinancialValueUpsert {
	u.SetExcluded(accountdailyfinancialvalue.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountDailyFinancialValue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountDailyFinancialValueUpsertOne) UpdateNewValues() *AccountDailyFinancialValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountdailyfinancialvalue.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountDailyFinancialValue.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountDailyFinancialValueUpsertOne) Ignore() *AccountDailyFinancialValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountDailyFinancialValueUpsertOne) DoNothing() *AccountDailyFinancialValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountDailyFinancialValueCreate.OnConflict
// documentation for more info.
func (u *AccountDailyFinancialValueUpsertOne) Update(set func(*AccountDailyFinancialValueUpsert)) *AccountDailyFinancialValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountDailyFinancialValueUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountDailyFinancialValueUpsertOne) SetAccountID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateAccountID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateAccountID()
	})
}

// SetBusinessDate sets the "business_date" field.
func (u *AccountDailyFinancialValueUpsertOne) SetBusinessDate(v time.Time) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateBusinessDate() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetOauthCostCny sets the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) SetOauthCostCny(v float64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetOauthCostCny(v)
	})
}

// AddOauthCostCny adds v to the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) AddOauthCostCny(v float64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddOauthCostCny(v)
	})
}

// UpdateOauthCostCny sets the "oauth_cost_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateOauthCostCny() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateOauthCostCny()
	})
}

// ClearOauthCostCny clears the value of the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearOauthCostCny() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearOauthCostCny()
	})
}

// SetRevenueOverrideCny sets the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) SetRevenueOverrideCny(v float64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueOverrideCny(v)
	})
}

// AddRevenueOverrideCny adds v to the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) AddRevenueOverrideCny(v float64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddRevenueOverrideCny(v)
	})
}

// UpdateRevenueOverrideCny sets the "revenue_override_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateRevenueOverrideCny() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueOverrideCny()
	})
}

// ClearRevenueOverrideCny clears the value of the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearRevenueOverrideCny() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueOverrideCny()
	})
}

// SetRevenueOverrideAt sets the "revenue_override_at" field.
func (u *AccountDailyFinancialValueUpsertOne) SetRevenueOverrideAt(v time.Time) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueOverrideAt(v)
	})
}

// UpdateRevenueOverrideAt sets the "revenue_override_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateRevenueOverrideAt() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueOverrideAt()
	})
}

// ClearRevenueOverrideAt clears the value of the "revenue_override_at" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearRevenueOverrideAt() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueOverrideAt()
	})
}

// SetRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) SetRevenueEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueEvidenceCutoffID(v)
	})
}

// AddRevenueEvidenceCutoffID adds v to the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) AddRevenueEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddRevenueEvidenceCutoffID(v)
	})
}

// UpdateRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateRevenueEvidenceCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueEvidenceCutoffID()
	})
}

// ClearRevenueEvidenceCutoffID clears the value of the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearRevenueEvidenceCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueEvidenceCutoffID()
	})
}

// SetRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) SetRevenueReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueReviewCutoffID(v)
	})
}

// AddRevenueReviewCutoffID adds v to the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) AddRevenueReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddRevenueReviewCutoffID(v)
	})
}

// UpdateRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateRevenueReviewCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueReviewCutoffID()
	})
}

// ClearRevenueReviewCutoffID clears the value of the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearRevenueReviewCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueReviewCutoffID()
	})
}

// SetCostOverrideCny sets the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) SetCostOverrideCny(v float64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostOverrideCny(v)
	})
}

// AddCostOverrideCny adds v to the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) AddCostOverrideCny(v float64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddCostOverrideCny(v)
	})
}

// UpdateCostOverrideCny sets the "cost_override_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateCostOverrideCny() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostOverrideCny()
	})
}

// ClearCostOverrideCny clears the value of the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearCostOverrideCny() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostOverrideCny()
	})
}

// SetCostOverrideAt sets the "cost_override_at" field.
func (u *AccountDailyFinancialValueUpsertOne) SetCostOverrideAt(v time.Time) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostOverrideAt(v)
	})
}

// UpdateCostOverrideAt sets the "cost_override_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateCostOverrideAt() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostOverrideAt()
	})
}

// ClearCostOverrideAt clears the value of the "cost_override_at" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearCostOverrideAt() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostOverrideAt()
	})
}

// SetCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) SetCostEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostEvidenceCutoffID(v)
	})
}

// AddCostEvidenceCutoffID adds v to the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) AddCostEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddCostEvidenceCutoffID(v)
	})
}

// UpdateCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateCostEvidenceCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostEvidenceCutoffID()
	})
}

// ClearCostEvidenceCutoffID clears the value of the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearCostEvidenceCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostEvidenceCutoffID()
	})
}

// SetCostReviewCutoffID sets the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) SetCostReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostReviewCutoffID(v)
	})
}

// AddCostReviewCutoffID adds v to the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) AddCostReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddCostReviewCutoffID(v)
	})
}

// UpdateCostReviewCutoffID sets the "cost_review_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateCostReviewCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostReviewCutoffID()
	})
}

// ClearCostReviewCutoffID clears the value of the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertOne) ClearCostReviewCutoffID() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostReviewCutoffID()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AccountDailyFinancialValueUpsertOne) SetUpdatedBy(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AccountDailyFinancialValueUpsertOne) AddUpdatedBy(v int64) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateUpdatedBy() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountDailyFinancialValueUpsertOne) SetUpdatedAt(v time.Time) *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertOne) UpdateUpdatedAt() *AccountDailyFinancialValueUpsertOne {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountDailyFinancialValueUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountDailyFinancialValueCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountDailyFinancialValueUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountDailyFinancialValueUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountDailyFinancialValueUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountDailyFinancialValueCreateBulk is the builder for creating many AccountDailyFinancialValue entities in bulk.
type AccountDailyFinancialValueCreateBulk struct {
	config
	err      error
	builders []*AccountDailyFinancialValueCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountDailyFinancialValue entities in the database.
func (_c *AccountDailyFinancialValueCreateBulk) Save(ctx context.Context) ([]*AccountDailyFinancialValue, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountDailyFinancialValue, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountDailyFinancialValueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountDailyFinancialValueCreateBulk) SaveX(ctx context.Context) []*AccountDailyFinancialValue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountDailyFinancialValueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountDailyFinancialValueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountDailyFinancialValue.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountDailyFinancialValueUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountDailyFinancialValueCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountDailyFinancialValueUpsertBulk {
	_c.conflict = opts
	return &AccountDailyFinancialValueUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountDailyFinancialValue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountDailyFinancialValueCreateBulk) OnConflictColumns(columns ...string) *AccountDailyFinancialValueUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountDailyFinancialValueUpsertBulk{
		create: _c,
	}
}

// AccountDailyFinancialValueUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountDailyFinancialValue nodes.
type AccountDailyFinancialValueUpsertBulk struct {
	create *AccountDailyFinancialValueCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountDailyFinancialValue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountDailyFinancialValueUpsertBulk) UpdateNewValues() *AccountDailyFinancialValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountdailyfinancialvalue.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountDailyFinancialValue.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountDailyFinancialValueUpsertBulk) Ignore() *AccountDailyFinancialValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountDailyFinancialValueUpsertBulk) DoNothing() *AccountDailyFinancialValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountDailyFinancialValueCreateBulk.OnConflict
// documentation for more info.
func (u *AccountDailyFinancialValueUpsertBulk) Update(set func(*AccountDailyFinancialValueUpsert)) *AccountDailyFinancialValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountDailyFinancialValueUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetAccountID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateAccountID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateAccountID()
	})
}

// SetBusinessDate sets the "business_date" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetBusinessDate(v time.Time) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetBusinessDate(v)
	})
}

// UpdateBusinessDate sets the "business_date" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateBusinessDate() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateBusinessDate()
	})
}

// SetOauthCostCny sets the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetOauthCostCny(v float64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetOauthCostCny(v)
	})
}

// AddOauthCostCny adds v to the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddOauthCostCny(v float64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddOauthCostCny(v)
	})
}

// UpdateOauthCostCny sets the "oauth_cost_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateOauthCostCny() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateOauthCostCny()
	})
}

// ClearOauthCostCny clears the value of the "oauth_cost_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearOauthCostCny() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearOauthCostCny()
	})
}

// SetRevenueOverrideCny sets the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetRevenueOverrideCny(v float64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueOverrideCny(v)
	})
}

// AddRevenueOverrideCny adds v to the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddRevenueOverrideCny(v float64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddRevenueOverrideCny(v)
	})
}

// UpdateRevenueOverrideCny sets the "revenue_override_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateRevenueOverrideCny() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueOverrideCny()
	})
}

// ClearRevenueOverrideCny clears the value of the "revenue_override_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearRevenueOverrideCny() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueOverrideCny()
	})
}

// SetRevenueOverrideAt sets the "revenue_override_at" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetRevenueOverrideAt(v time.Time) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueOverrideAt(v)
	})
}

// UpdateRevenueOverrideAt sets the "revenue_override_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateRevenueOverrideAt() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueOverrideAt()
	})
}

// ClearRevenueOverrideAt clears the value of the "revenue_override_at" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearRevenueOverrideAt() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueOverrideAt()
	})
}

// SetRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetRevenueEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueEvidenceCutoffID(v)
	})
}

// AddRevenueEvidenceCutoffID adds v to the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddRevenueEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddRevenueEvidenceCutoffID(v)
	})
}

// UpdateRevenueEvidenceCutoffID sets the "revenue_evidence_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateRevenueEvidenceCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueEvidenceCutoffID()
	})
}

// ClearRevenueEvidenceCutoffID clears the value of the "revenue_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearRevenueEvidenceCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueEvidenceCutoffID()
	})
}

// SetRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetRevenueReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetRevenueReviewCutoffID(v)
	})
}

// AddRevenueReviewCutoffID adds v to the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddRevenueReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddRevenueReviewCutoffID(v)
	})
}

// UpdateRevenueReviewCutoffID sets the "revenue_review_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateRevenueReviewCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateRevenueReviewCutoffID()
	})
}

// ClearRevenueReviewCutoffID clears the value of the "revenue_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearRevenueReviewCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearRevenueReviewCutoffID()
	})
}

// SetCostOverrideCny sets the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetCostOverrideCny(v float64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostOverrideCny(v)
	})
}

// AddCostOverrideCny adds v to the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddCostOverrideCny(v float64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddCostOverrideCny(v)
	})
}

// UpdateCostOverrideCny sets the "cost_override_cny" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateCostOverrideCny() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostOverrideCny()
	})
}

// ClearCostOverrideCny clears the value of the "cost_override_cny" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearCostOverrideCny() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostOverrideCny()
	})
}

// SetCostOverrideAt sets the "cost_override_at" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetCostOverrideAt(v time.Time) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostOverrideAt(v)
	})
}

// UpdateCostOverrideAt sets the "cost_override_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateCostOverrideAt() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostOverrideAt()
	})
}

// ClearCostOverrideAt clears the value of the "cost_override_at" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearCostOverrideAt() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostOverrideAt()
	})
}

// SetCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetCostEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostEvidenceCutoffID(v)
	})
}

// AddCostEvidenceCutoffID adds v to the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddCostEvidenceCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddCostEvidenceCutoffID(v)
	})
}

// UpdateCostEvidenceCutoffID sets the "cost_evidence_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateCostEvidenceCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostEvidenceCutoffID()
	})
}

// ClearCostEvidenceCutoffID clears the value of the "cost_evidence_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearCostEvidenceCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostEvidenceCutoffID()
	})
}

// SetCostReviewCutoffID sets the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetCostReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetCostReviewCutoffID(v)
	})
}

// AddCostReviewCutoffID adds v to the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddCostReviewCutoffID(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddCostReviewCutoffID(v)
	})
}

// UpdateCostReviewCutoffID sets the "cost_review_cutoff_id" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateCostReviewCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateCostReviewCutoffID()
	})
}

// ClearCostReviewCutoffID clears the value of the "cost_review_cutoff_id" field.
func (u *AccountDailyFinancialValueUpsertBulk) ClearCostReviewCutoffID() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.ClearCostReviewCutoffID()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetUpdatedBy(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AccountDailyFinancialValueUpsertBulk) AddUpdatedBy(v int64) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateUpdatedBy() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountDailyFinancialValueUpsertBulk) SetUpdatedAt(v time.Time) *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountDailyFinancialValueUpsertBulk) UpdateUpdatedAt() *AccountDailyFinancialValueUpsertBulk {
	return u.Update(func(s *AccountDailyFinancialValueUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountDailyFinancialValueUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountDailyFinancialValueCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountDailyFinancialValueCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountDailyFinancialValueUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
