// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountfinancialsetting"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountFinancialSettingUpdate is the builder for updating AccountFinancialSetting entities.
type AccountFinancialSettingUpdate struct {
	config
	hooks    []Hook
	mutation *AccountFinancialSettingMutation
}

// Where appends a list predicates to the AccountFinancialSettingUpdate builder.
func (_u *AccountFinancialSettingUpdate) Where(ps ...predicate.AccountFinancialSetting) *AccountFinancialSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *AccountFinancialSettingUpdate) SetKey(v string) *AccountFinancialSettingUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *AccountFinancialSettingUpdate) SetNillableKey(v *string) *AccountFinancialSettingUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnabledAt sets the "enabled_at" field.
func (_u *AccountFinancialSettingUpdate) SetEnabledAt(v time.Time) *AccountFinancialSettingUpdate {
	_u.mutation.SetEnabledAt(v)
	return _u
}

// SetNillableEnabledAt sets the "enabled_at" field if the given value is not nil.
func (_u *AccountFinancialSettingUpdate) SetNillableEnabledAt(v *time.Time) *AccountFinancialSettingUpdate {
	if v != nil {
		_u.SetEnabledAt(*v)
	}
	return _u
}

// ClearEnabledAt clears the value of the "enabled_at" field.
func (_u *AccountFinancialSettingUpdate) ClearEnabledAt() *AccountFinancialSettingUpdate {
	_u.mutation.ClearEnabledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountFinancialSettingUpdate) SetUpdatedAt(v time.Time) *AccountFinancialSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountFinancialSettingMutation object of the builder.
func (_u *AccountFinancialSettingUpdate) Mutation() *AccountFinancialSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountFinancialSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountFinancialSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountFinancialSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountFinancialSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountFinancialSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountfinancialsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountFinancialSettingUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := accountfinancialsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AccountFinancialSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountFinancialSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountfinancialsetting.Table, accountfinancialsetting.Columns, sqlgraph.NewFieldSpec(accountfinancialsetting.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(accountfinancialsetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnabledAt(); ok {
		_spec.SetField(accountfinancialsetting.FieldEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.EnabledAtCleared() {
		_spec.ClearField(accountfinancialsetting.FieldEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountfinancialsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountfinancialsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountFinancialSettingUpdateOne is the builder for updating a single AccountFinancialSetting entity.
type AccountFinancialSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountFinancialSettingMutation
}

// SetKey sets the "key" field.
func (_u *AccountFinancialSettingUpdateOne) SetKey(v string) *AccountFinancialSettingUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *AccountFinancialSettingUpdateOne) SetNillableKey(v *string) *AccountFinancialSettingUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetEnabledAt sets the "enabled_at" field.
func (_u *AccountFinancialSettingUpdateOne) SetEnabledAt(v time.Time) *AccountFinancialSettingUpdateOne {
	_u.mutation.SetEnabledAt(v)
	return _u
}

// SetNillableEnabledAt sets the "enabled_at" field if the given value is not nil.
func (_u *AccountFinancialSettingUpdateOne) SetNillableEnabledAt(v *time.Time) *AccountFinancialSettingUpdateOne {
	if v != nil {
		_u.SetEnabledAt(*v)
	}
	return _u
}

// ClearEnabledAt clears the value of the "enabled_at" field.
func (_u *AccountFinancialSettingUpdateOne) ClearEnabledAt() *AccountFinancialSettingUpdateOne {
	_u.mutation.ClearEnabledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountFinancialSettingUpdateOne) SetUpdatedAt(v time.Time) *AccountFinancialSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountFinancialSettingMutation object of the builder.
func (_u *AccountFinancialSettingUpdateOne) Mutation() *AccountFinancialSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountFinancialSettingUpdate builder.
func (_u *AccountFinancialSettingUpdateOne) Where(ps ...predicate.AccountFinancialSetting) *AccountFinancialSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountFinancialSettingUpdateOne) Select(field string, fields ...string) *AccountFinancialSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountFinancialSetting entity.
func (_u *AccountFinancialSettingUpdateOne) Save(ctx context.Context) (*AccountFinancialSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountFinancialSettingUpdateOne) SaveX(ctx context.Context) *AccountFinancialSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountFinancialSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountFinancialSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountFinancialSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountfinancialsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountFinancialSettingUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := accountfinancialsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "AccountFinancialSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountFinancialSettingUpdateOne) sqlSave(ctx context.Context) (_node *AccountFinancialSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountfinancialsetting.Table, accountfinancialsetting.Columns, sqlgraph.NewFieldSpec(accountfinancialsetting.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountFinancialSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountfinancialsetting.FieldID)
		for _, f := range fields {
			if !accountfinancialsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountfinancialsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(accountfinancialsetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnabledAt(); ok {
		_spec.SetField(accountfinancialsetting.FieldEnabledAt, field.TypeTime, value)
	}
	if _u.mutation.EnabledAtCleared() {
		_spec.ClearField(accountfinancialsetting.FieldEnabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountfinancialsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AccountFinancialSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountfinancialsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
