// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagecostreview"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// UsageCostReview is the model entity for the UsageCostReview schema.
type UsageCostReview struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// ReviewStatus holds the value of the "review_status" field.
	ReviewStatus usagecostreview.ReviewStatus `json:"review_status,omitempty"`
	// ManualCostCny holds the value of the "manual_cost_cny" field.
	ManualCostCny float64 `json:"manual_cost_cny,omitempty"`
	// ManualProfitCny holds the value of the "manual_profit_cny" field.
	ManualProfitCny float64 `json:"manual_profit_cny,omitempty"`
	// ReviewedBy holds the value of the "reviewed_by" field.
	ReviewedBy int64 `json:"reviewed_by,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt time.Time `json:"reviewed_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageCostReviewQuery when eager-loading is set.
	Edges        UsageCostReviewEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageCostReviewEdges holds the relations/edges for other nodes in the graph.
type UsageCostReviewEdges struct {
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageCostReviewEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageCostReview) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagecostreview.FieldManualCostCny, usagecostreview.FieldManualProfitCny:
			values[i] = new(sql.NullFloat64)
		case usagecostreview.FieldID, usagecostreview.FieldUsageLogID, usagecostreview.FieldReviewedBy:
			values[i] = new(sql.NullInt64)
		case usagecostreview.FieldReviewStatus:
			values[i] = new(sql.NullString)
		case usagecostreview.FieldReviewedAt, usagecostreview.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageCostReview fields.
func (_m *UsageCostReview) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagecostreview.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagecostreview.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case usagecostreview.FieldReviewStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_status", values[i])
			} else if value.Valid {
				_m.ReviewStatus = usagecostreview.ReviewStatus(value.String)
			}
		case usagecostreview.FieldManualCostCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_cost_cny", values[i])
			} else if value.Valid {
				_m.ManualCostCny = value.Float64
			}
		case usagecostreview.FieldManualProfitCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field manual_profit_cny", values[i])
			} else if value.Valid {
				_m.ManualProfitCny = value.Float64
			}
		case usagecostreview.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = value.Int64
			}
		case usagecostreview.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = value.Time
			}
		case usagecostreview.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageCostReview.
// This includes values selected through modifiers, order, etc.
func (_m *UsageCostReview) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageLog queries the "usage_log" edge of the UsageCostReview entity.
func (_m *UsageCostReview) QueryUsageLog() *UsageLogQuery {
	return NewUsageCostReviewClient(_m.config).QueryUsageLog(_m)
}

// Update returns a builder for updating this UsageCostReview.
// Note that you need to call UsageCostReview.Unwrap() before calling this method if this UsageCostReview
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageCostReview) Update() *UsageCostReviewUpdateOne {
	return NewUsageCostReviewClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageCostReview entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageCostReview) Unwrap() *UsageCostReview {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageCostReview is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageCostReview) String() string {
	var builder strings.Builder
	builder.WriteString("UsageCostReview(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("review_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewStatus))
	builder.WriteString(", ")
	builder.WriteString("manual_cost_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManualCostCny))
	builder.WriteString(", ")
	builder.WriteString("manual_profit_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManualProfitCny))
	builder.WriteString(", ")
	builder.WriteString("reviewed_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewedBy))
	builder.WriteString(", ")
	builder.WriteString("reviewed_at=")
	builder.WriteString(_m.ReviewedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageCostReviews is a parsable slice of UsageCostReview.
type UsageCostReviews []*UsageCostReview
