// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagecostreview"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// UsageCostReviewUpdate is the builder for updating UsageCostReview entities.
type UsageCostReviewUpdate struct {
	config
	hooks    []Hook
	mutation *UsageCostReviewMutation
}

// Where appends a list predicates to the UsageCostReviewUpdate builder.
func (_u *UsageCostReviewUpdate) Where(ps ...predicate.UsageCostReview) *UsageCostReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageCostReviewUpdate) SetUsageLogID(v int64) *UsageCostReviewUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageCostReviewUpdate) SetNillableUsageLogID(v *int64) *UsageCostReviewUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetReviewStatus sets the "review_status" field.
func (_u *UsageCostReviewUpdate) SetReviewStatus(v usagecostreview.ReviewStatus) *UsageCostReviewUpdate {
	_u.mutation.SetReviewStatus(v)
	return _u
}

// SetNillableReviewStatus sets the "review_status" field if the given value is not nil.
func (_u *UsageCostReviewUpdate) SetNillableReviewStatus(v *usagecostreview.ReviewStatus) *UsageCostReviewUpdate {
	if v != nil {
		_u.SetReviewStatus(*v)
	}
	return _u
}

// SetManualCostCny sets the "manual_cost_cny" field.
func (_u *UsageCostReviewUpdate) SetManualCostCny(v float64) *UsageCostReviewUpdate {
	_u.mutation.ResetManualCostCny()
	_u.mutation.SetManualCostCny(v)
	return _u
}

// SetNillableManualCostCny sets the "manual_cost_cny" field if the given value is not nil.
func (_u *UsageCostReviewUpdate) SetNillableManualCostCny(v *float64) *UsageCostReviewUpdate {
	if v != nil {
		_u.SetManualCostCny(*v)
	}
	return _u
}

// AddManualCostCny adds value to the "manual_cost_cny" field.
func (_u *UsageCostReviewUpdate) AddManualCostCny(v float64) *UsageCostReviewUpdate {
	_u.mutation.AddManualCostCny(v)
	return _u
}

// SetManualProfitCny sets the "manual_profit_cny" field.
func (_u *UsageCostReviewUpdate) SetManualProfitCny(v float64) *UsageCostReviewUpdate {
	_u.mutation.ResetManualProfitCny()
	_u.mutation.SetManualProfitCny(v)
	return _u
}

// SetNillableManualProfitCny sets the "manual_profit_cny" field if the given value is not nil.
func (_u *UsageCostReviewUpdate) SetNillableManualProfitCny(v *float64) *UsageCostReviewUpdate {
	if v != nil {
		_u.SetManualProfitCny(*v)
	}
	return _u
}

// AddManualProfitCny adds value to the "manual_profit_cny" field.
func (_u *UsageCostReviewUpdate) AddManualProfitCny(v float64) *UsageCostReviewUpdate {
	_u.mutation.AddManualProfitCny(v)
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *UsageCostReviewUpdate) SetReviewedBy(v int64) *UsageCostReviewUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *UsageCostReviewUpdate) SetNillableReviewedBy(v *int64) *UsageCostReviewUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *UsageCostReviewUpdate) AddReviewedBy(v int64) *UsageCostReviewUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *UsageCostReviewUpdate) SetReviewedAt(v time.Time) *UsageCostReviewUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *UsageCostReviewUpdate) SetNillableReviewedAt(v *time.Time) *UsageCostReviewUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageCostReviewUpdate) SetUpdatedAt(v time.Time) *UsageCostReviewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *UsageCostReviewUpdate) SetUsageLog(v *UsageLog) *UsageCostReviewUpdate {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the UsageCostReviewMutation object of the builder.
func (_u *UsageCostReviewUpdate) Mutation() *UsageCostReviewMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *UsageCostReviewUpdate) ClearUsageLog() *UsageCostReviewUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageCostReviewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageCostReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageCostReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageCostReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageCostReviewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagecostreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageCostReviewUpdate) check() error {
	if v, ok := _u.mutation.ReviewStatus(); ok {
		if err := usagecostreview.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`ent: validator failed for field "UsageCostReview.review_status": %w`, err)}
		}
	}
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageCostReview.usage_log"`)
	}
	return nil
}

func (_u *UsageCostReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagecostreview.Table, usagecostreview.Columns, sqlgraph.NewFieldSpec(usagecostreview.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReviewStatus(); ok {
		_spec.SetField(usagecostreview.FieldReviewStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ManualCostCny(); ok {
		_spec.SetField(usagecostreview.FieldManualCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualCostCny(); ok {
		_spec.AddField(usagecostreview.FieldManualCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ManualProfitCny(); ok {
		_spec.SetField(usagecostreview.FieldManualProfitCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualProfitCny(); ok {
		_spec.AddField(usagecostreview.FieldManualProfitCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(usagecostreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(usagecostreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(usagecostreview.FieldReviewedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagecostreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagecostreview.UsageLogTable,
			Columns: []string{usagecostreview.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagecostreview.UsageLogTable,
			Columns: []string{usagecostreview.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagecostreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageCostReviewUpdateOne is the builder for updating a single UsageCostReview entity.
type UsageCostReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageCostReviewMutation
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageCostReviewUpdateOne) SetUsageLogID(v int64) *UsageCostReviewUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageCostReviewUpdateOne) SetNillableUsageLogID(v *int64) *UsageCostReviewUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetReviewStatus sets the "review_status" field.
func (_u *UsageCostReviewUpdateOne) SetReviewStatus(v usagecostreview.ReviewStatus) *UsageCostReviewUpdateOne {
	_u.mutation.SetReviewStatus(v)
	return _u
}

// SetNillableReviewStatus sets the "review_status" field if the given value is not nil.
func (_u *UsageCostReviewUpdateOne) SetNillableReviewStatus(v *usagecostreview.ReviewStatus) *UsageCostReviewUpdateOne {
	if v != nil {
		_u.SetReviewStatus(*v)
	}
	return _u
}

// SetManualCostCny sets the "manual_cost_cny" field.
func (_u *UsageCostReviewUpdateOne) SetManualCostCny(v float64) *UsageCostReviewUpdateOne {
	_u.mutation.ResetManualCostCny()
	_u.mutation.SetManualCostCny(v)
	return _u
}

// SetNillableManualCostCny sets the "manual_cost_cny" field if the given value is not nil.
func (_u *UsageCostReviewUpdateOne) SetNillableManualCostCny(v *float64) *UsageCostReviewUpdateOne {
	if v != nil {
		_u.SetManualCostCny(*v)
	}
	return _u
}

// AddManualCostCny adds value to the "manual_cost_cny" field.
func (_u *UsageCostReviewUpdateOne) AddManualCostCny(v float64) *UsageCostReviewUpdateOne {
	_u.mutation.AddManualCostCny(v)
	return _u
}

// SetManualProfitCny sets the "manual_profit_cny" field.
func (_u *UsageCostReviewUpdateOne) SetManualProfitCny(v float64) *UsageCostReviewUpdateOne {
	_u.mutation.ResetManualProfitCny()
	_u.mutation.SetManualProfitCny(v)
	return _u
}

// SetNillableManualProfitCny sets the "manual_profit_cny" field if the given value is not nil.
func (_u *UsageCostReviewUpdateOne) SetNillableManualProfitCny(v *float64) *UsageCostReviewUpdateOne {
	if v != nil {
		_u.SetManualProfitCny(*v)
	}
	return _u
}

// AddManualProfitCny adds value to the "manual_profit_cny" field.
func (_u *UsageCostReviewUpdateOne) AddManualProfitCny(v float64) *UsageCostReviewUpdateOne {
	_u.mutation.AddManualProfitCny(v)
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *UsageCostReviewUpdateOne) SetReviewedBy(v int64) *UsageCostReviewUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *UsageCostReviewUpdateOne) SetNillableReviewedBy(v *int64) *UsageCostReviewUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *UsageCostReviewUpdateOne) AddReviewedBy(v int64) *UsageCostReviewUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *UsageCostReviewUpdateOne) SetReviewedAt(v time.Time) *UsageCostReviewUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *UsageCostReviewUpdateOne) SetNillableReviewedAt(v *time.Time) *UsageCostReviewUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageCostReviewUpdateOne) SetUpdatedAt(v time.Time) *UsageCostReviewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *UsageCostReviewUpdateOne) SetUsageLog(v *UsageLog) *UsageCostReviewUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the UsageCostReviewMutation object of the builder.
func (_u *UsageCostReviewUpdateOne) Mutation() *UsageCostReviewMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *UsageCostReviewUpdateOne) ClearUsageLog() *UsageCostReviewUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// Where appends a list predicates to the UsageCostReviewUpdate builder.
func (_u *UsageCostReviewUpdateOne) Where(ps ...predicate.UsageCostReview) *UsageCostReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageCostReviewUpdateOne) Select(field string, fields ...string) *UsageCostReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageCostReview entity.
func (_u *UsageCostReviewUpdateOne) Save(ctx context.Context) (*UsageCostReview, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageCostReviewUpdateOne) SaveX(ctx context.Context) *UsageCostReview {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageCostReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageCostReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageCostReviewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagecostreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageCostReviewUpdateOne) check() error {
	if v, ok := _u.mutation.ReviewStatus(); ok {
		if err := usagecostreview.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`ent: validator failed for field "UsageCostReview.review_status": %w`, err)}
		}
	}
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageCostReview.usage_log"`)
	}
	return nil
}

func (_u *UsageCostReviewUpdateOne) sqlSave(ctx context.Context) (_node *UsageCostReview, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagecostreview.Table, usagecostreview.Columns, sqlgraph.NewFieldSpec(usagecostreview.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageCostReview.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagecostreview.FieldID)
		for _, f := range fields {
			if !usagecostreview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagecostreview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReviewStatus(); ok {
		_spec.SetField(usagecostreview.FieldReviewStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ManualCostCny(); ok {
		_spec.SetField(usagecostreview.FieldManualCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualCostCny(); ok {
		_spec.AddField(usagecostreview.FieldManualCostCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ManualProfitCny(); ok {
		_spec.SetField(usagecostreview.FieldManualProfitCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedManualProfitCny(); ok {
		_spec.AddField(usagecostreview.FieldManualProfitCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(usagecostreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(usagecostreview.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(usagecostreview.FieldReviewedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagecostreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagecostreview.UsageLogTable,
			Columns: []string{usagecostreview.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagecostreview.UsageLogTable,
			Columns: []string{usagecostreview.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageCostReview{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagecostreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
