// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usageupstreamcostevidence"
)

// UsageUpstreamCostEvidence is the model entity for the UsageUpstreamCostEvidence schema.
type UsageUpstreamCostEvidence struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// Source holds the value of the "source" field.
	Source usageupstreamcostevidence.Source `json:"source,omitempty"`
	// UpstreamRequestID holds the value of the "upstream_request_id" field.
	UpstreamRequestID *string `json:"upstream_request_id,omitempty"`
	// UpstreamBillingTime holds the value of the "upstream_billing_time" field.
	UpstreamBillingTime *time.Time `json:"upstream_billing_time,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel *string `json:"upstream_model,omitempty"`
	// SubActualCost holds the value of the "sub_actual_cost" field.
	SubActualCost *float64 `json:"sub_actual_cost,omitempty"`
	// NewapiQuota holds the value of the "newapi_quota" field.
	NewapiQuota *float64 `json:"newapi_quota,omitempty"`
	// NewapiQuotaPerUnit holds the value of the "newapi_quota_per_unit" field.
	NewapiQuotaPerUnit *float64 `json:"newapi_quota_per_unit,omitempty"`
	// NormalizedCostCny holds the value of the "normalized_cost_cny" field.
	NormalizedCostCny *float64 `json:"normalized_cost_cny,omitempty"`
	// ProfitCny holds the value of the "profit_cny" field.
	ProfitCny *float64 `json:"profit_cny,omitempty"`
	// EvidenceStatus holds the value of the "evidence_status" field.
	EvidenceStatus usageupstreamcostevidence.EvidenceStatus `json:"evidence_status,omitempty"`
	// ReasonCode holds the value of the "reason_code" field.
	ReasonCode *string `json:"reason_code,omitempty"`
	// RecordedAt holds the value of the "recorded_at" field.
	RecordedAt time.Time `json:"recorded_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageUpstreamCostEvidenceQuery when eager-loading is set.
	Edges        UsageUpstreamCostEvidenceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageUpstreamCostEvidenceEdges holds the relations/edges for other nodes in the graph.
type UsageUpstreamCostEvidenceEdges struct {
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageUpstreamCostEvidenceEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageUpstreamCostEvidence) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usageupstreamcostevidence.FieldSubActualCost, usageupstreamcostevidence.FieldNewapiQuota, usageupstreamcostevidence.FieldNewapiQuotaPerUnit, usageupstreamcostevidence.FieldNormalizedCostCny, usageupstreamcostevidence.FieldProfitCny:
			values[i] = new(sql.NullFloat64)
		case usageupstreamcostevidence.FieldID, usageupstreamcostevidence.FieldUsageLogID:
			values[i] = new(sql.NullInt64)
		case usageupstreamcostevidence.FieldSource, usageupstreamcostevidence.FieldUpstreamRequestID, usageupstreamcostevidence.FieldUpstreamModel, usageupstreamcostevidence.FieldEvidenceStatus, usageupstreamcostevidence.FieldReasonCode:
			values[i] = new(sql.NullString)
		case usageupstreamcostevidence.FieldUpstreamBillingTime, usageupstreamcostevidence.FieldRecordedAt, usageupstreamcostevidence.FieldCreatedAt, usageupstreamcostevidence.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageUpstreamCostEvidence fields.
func (_m *UsageUpstreamCostEvidence) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usageupstreamcostevidence.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usageupstreamcostevidence.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case usageupstreamcostevidence.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = usageupstreamcostevidence.Source(value.String)
			}
		case usageupstreamcostevidence.FieldUpstreamRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_id", values[i])
			} else if value.Valid {
				_m.UpstreamRequestID = new(string)
				*_m.UpstreamRequestID = value.String
			}
		case usageupstreamcostevidence.FieldUpstreamBillingTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_billing_time", values[i])
			} else if value.Valid {
				_m.UpstreamBillingTime = new(time.Time)
				*_m.UpstreamBillingTime = value.Time
			}
		case usageupstreamcostevidence.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = new(string)
				*_m.UpstreamModel = value.String
			}
		case usageupstreamcostevidence.FieldSubActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sub_actual_cost", values[i])
			} else if value.Valid {
				_m.SubActualCost = new(float64)
				*_m.SubActualCost = value.Float64
			}
		case usageupstreamcostevidence.FieldNewapiQuota:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field newapi_quota", values[i])
			} else if value.Valid {
				_m.NewapiQuota = new(float64)
				*_m.NewapiQuota = value.Float64
			}
		case usageupstreamcostevidence.FieldNewapiQuotaPerUnit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field newapi_quota_per_unit", values[i])
			} else if value.Valid {
				_m.NewapiQuotaPerUnit = new(float64)
				*_m.NewapiQuotaPerUnit = value.Float64
			}
		case usageupstreamcostevidence.FieldNormalizedCostCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_cost_cny", values[i])
			} else if value.Valid {
				_m.NormalizedCostCny = new(float64)
				*_m.NormalizedCostCny = value.Float64
			}
		case usageupstreamcostevidence.FieldProfitCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field profit_cny", values[i])
			} else if value.Valid {
				_m.ProfitCny = new(float64)
				*_m.ProfitCny = value.Float64
			}
		case usageupstreamcostevidence.FieldEvidenceStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field evidence_status", values[i])
			} else if value.Valid {
				_m.EvidenceStatus = usageupstreamcostevidence.EvidenceStatus(value.String)
			}
		case usageupstreamcostevidence.FieldReasonCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason_code", values[i])
			} else if value.Valid {
				_m.ReasonCode = new(string)
				*_m.ReasonCode = value.String
			}
		case usageupstreamcostevidence.FieldRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_at", values[i])
			} else if value.Valid {
				_m.RecordedAt = value.Time
			}
		case usageupstreamcostevidence.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usageupstreamcostevidence.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageUpstreamCostEvidence.
// This includes values selected through modifiers, order, etc.
func (_m *UsageUpstreamCostEvidence) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageLog queries the "usage_log" edge of the UsageUpstreamCostEvidence entity.
func (_m *UsageUpstreamCostEvidence) QueryUsageLog() *UsageLogQuery {
	return NewUsageUpstreamCostEvidenceClient(_m.config).QueryUsageLog(_m)
}

// Update returns a builder for updating this UsageUpstreamCostEvidence.
// Note that you need to call UsageUpstreamCostEvidence.Unwrap() before calling this method if this UsageUpstreamCostEvidence
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageUpstreamCostEvidence) Update() *UsageUpstreamCostEvidenceUpdateOne {
	return NewUsageUpstreamCostEvidenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageUpstreamCostEvidence entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageUpstreamCostEvidence) Unwrap() *UsageUpstreamCostEvidence {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageUpstreamCostEvidence is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageUpstreamCostEvidence) String() string {
	var builder strings.Builder
	builder.WriteString("UsageUpstreamCostEvidence(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	if v := _m.UpstreamRequestID; v != nil {
		builder.WriteString("upstream_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamBillingTime; v != nil {
		builder.WriteString("upstream_billing_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamModel; v != nil {
		builder.WriteString("upstream_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SubActualCost; v != nil {
		builder.WriteString("sub_actual_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.NewapiQuota; v != nil {
		builder.WriteString("newapi_quota=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.NewapiQuotaPerUnit; v != nil {
		builder.WriteString("newapi_quota_per_unit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.NormalizedCostCny; v != nil {
		builder.WriteString("normalized_cost_cny=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProfitCny; v != nil {
		builder.WriteString("profit_cny=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("evidence_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.EvidenceStatus))
	builder.WriteString(", ")
	if v := _m.ReasonCode; v != nil {
		builder.WriteString("reason_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("recorded_at=")
	builder.WriteString(_m.RecordedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageUpstreamCostEvidences is a parsable slice of UsageUpstreamCostEvidence.
type UsageUpstreamCostEvidences []*UsageUpstreamCostEvidence
