// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/quotaidempotencyrecord"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userquotaledgerentry"
)

// UserQuotaLedgerEntry is the model entity for the UserQuotaLedgerEntry schema.
type UserQuotaLedgerEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// RecordType holds the value of the "record_type" field.
	RecordType string `json:"record_type,omitempty"`
	// CashDeltaCny holds the value of the "cash_delta_cny" field.
	CashDeltaCny float64 `json:"cash_delta_cny,omitempty"`
	// PaidQuotaDeltaUsd holds the value of the "paid_quota_delta_usd" field.
	PaidQuotaDeltaUsd float64 `json:"paid_quota_delta_usd,omitempty"`
	// GiftQuotaDeltaUsd holds the value of the "gift_quota_delta_usd" field.
	GiftQuotaDeltaUsd float64 `json:"gift_quota_delta_usd,omitempty"`
	// CashBeforeCny holds the value of the "cash_before_cny" field.
	CashBeforeCny float64 `json:"cash_before_cny,omitempty"`
	// CashAfterCny holds the value of the "cash_after_cny" field.
	CashAfterCny float64 `json:"cash_after_cny,omitempty"`
	// PaidBeforeUsd holds the value of the "paid_before_usd" field.
	PaidBeforeUsd float64 `json:"paid_before_usd,omitempty"`
	// PaidAfterUsd holds the value of the "paid_after_usd" field.
	PaidAfterUsd float64 `json:"paid_after_usd,omitempty"`
	// GiftBeforeUsd holds the value of the "gift_before_usd" field.
	GiftBeforeUsd float64 `json:"gift_before_usd,omitempty"`
	// GiftAfterUsd holds the value of the "gift_after_usd" field.
	GiftAfterUsd float64 `json:"gift_after_usd,omitempty"`
	// ReferenceType holds the value of the "reference_type" field.
	ReferenceType *string `json:"reference_type,omitempty"`
	// ReferenceID holds the value of the "reference_id" field.
	ReferenceID *string `json:"reference_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// OperatorID holds the value of the "operator_id" field.
	OperatorID *int64 `json:"operator_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuotaLedgerEntryQuery when eager-loading is set.
	Edges        UserQuotaLedgerEntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserQuotaLedgerEntryEdges holds the relations/edges for other nodes in the graph.
type UserQuotaLedgerEntryEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Operator holds the value of the operator edge.
	Operator *User `json:"operator,omitempty"`
	// IdempotencyRecord holds the value of the idempotency_record edge.
	IdempotencyRecord *QuotaIdempotencyRecord `json:"idempotency_record,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuotaLedgerEntryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OperatorOrErr returns the Operator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuotaLedgerEntryEdges) OperatorOrErr() (*User, error) {
	if e.Operator != nil {
		return e.Operator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "operator"}
}

// IdempotencyRecordOrErr returns the IdempotencyRecord value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuotaLedgerEntryEdges) IdempotencyRecordOrErr() (*QuotaIdempotencyRecord, error) {
	if e.IdempotencyRecord != nil {
		return e.IdempotencyRecord, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: quotaidempotencyrecord.Label}
	}
	return nil, &NotLoadedError{edge: "idempotency_record"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserQuotaLedgerEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userquotaledgerentry.FieldCashDeltaCny, userquotaledgerentry.FieldPaidQuotaDeltaUsd, userquotaledgerentry.FieldGiftQuotaDeltaUsd, userquotaledgerentry.FieldCashBeforeCny, userquotaledgerentry.FieldCashAfterCny, userquotaledgerentry.FieldPaidBeforeUsd, userquotaledgerentry.FieldPaidAfterUsd, userquotaledgerentry.FieldGiftBeforeUsd, userquotaledgerentry.FieldGiftAfterUsd:
			values[i] = new(sql.NullFloat64)
		case userquotaledgerentry.FieldID, userquotaledgerentry.FieldUserID, userquotaledgerentry.FieldOperatorID:
			values[i] = new(sql.NullInt64)
		case userquotaledgerentry.FieldRecordType, userquotaledgerentry.FieldReferenceType, userquotaledgerentry.FieldReferenceID, userquotaledgerentry.FieldIdempotencyKey, userquotaledgerentry.FieldNote, userquotaledgerentry.FieldStatus:
			values[i] = new(sql.NullString)
		case userquotaledgerentry.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserQuotaLedgerEntry fields.
func (_m *UserQuotaLedgerEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userquotaledgerentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userquotaledgerentry.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userquotaledgerentry.FieldRecordType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field record_type", values[i])
			} else if value.Valid {
				_m.RecordType = value.String
			}
		case userquotaledgerentry.FieldCashDeltaCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cash_delta_cny", values[i])
			} else if value.Valid {
				_m.CashDeltaCny = value.Float64
			}
		case userquotaledgerentry.FieldPaidQuotaDeltaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_quota_delta_usd", values[i])
			} else if value.Valid {
				_m.PaidQuotaDeltaUsd = value.Float64
			}
		case userquotaledgerentry.FieldGiftQuotaDeltaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gift_quota_delta_usd", values[i])
			} else if value.Valid {
				_m.GiftQuotaDeltaUsd = value.Float64
			}
		case userquotaledgerentry.FieldCashBeforeCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cash_before_cny", values[i])
			} else if value.Valid {
				_m.CashBeforeCny = value.Float64
			}
		case userquotaledgerentry.FieldCashAfterCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cash_after_cny", values[i])
			} else if value.Valid {
				_m.CashAfterCny = value.Float64
			}
		case userquotaledgerentry.FieldPaidBeforeUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_before_usd", values[i])
			} else if value.Valid {
				_m.PaidBeforeUsd = value.Float64
			}
		case userquotaledgerentry.FieldPaidAfterUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_after_usd", values[i])
			} else if value.Valid {
				_m.PaidAfterUsd = value.Float64
			}
		case userquotaledgerentry.FieldGiftBeforeUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gift_before_usd", values[i])
			} else if value.Valid {
				_m.GiftBeforeUsd = value.Float64
			}
		case userquotaledgerentry.FieldGiftAfterUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gift_after_usd", values[i])
			} else if value.Valid {
				_m.GiftAfterUsd = value.Float64
			}
		case userquotaledgerentry.FieldReferenceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_type", values[i])
			} else if value.Valid {
				_m.ReferenceType = new(string)
				*_m.ReferenceType = value.String
			}
		case userquotaledgerentry.FieldReferenceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_id", values[i])
			} else if value.Valid {
				_m.ReferenceID = new(string)
				*_m.ReferenceID = value.String
			}
		case userquotaledgerentry.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case userquotaledgerentry.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case userquotaledgerentry.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = new(int64)
				*_m.OperatorID = value.Int64
			}
		case userquotaledgerentry.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userquotaledgerentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserQuotaLedgerEntry.
// This includes values selected through modifiers, order, etc.
func (_m *UserQuotaLedgerEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserQuotaLedgerEntry entity.
func (_m *UserQuotaLedgerEntry) QueryUser() *UserQuery {
	return NewUserQuotaLedgerEntryClient(_m.config).QueryUser(_m)
}

// QueryOperator queries the "operator" edge of the UserQuotaLedgerEntry entity.
func (_m *UserQuotaLedgerEntry) QueryOperator() *UserQuery {
	return NewUserQuotaLedgerEntryClient(_m.config).QueryOperator(_m)
}

// QueryIdempotencyRecord queries the "idempotency_record" edge of the UserQuotaLedgerEntry entity.
func (_m *UserQuotaLedgerEntry) QueryIdempotencyRecord() *QuotaIdempotencyRecordQuery {
	return NewUserQuotaLedgerEntryClient(_m.config).QueryIdempotencyRecord(_m)
}

// Update returns a builder for updating this UserQuotaLedgerEntry.
// Note that you need to call UserQuotaLedgerEntry.Unwrap() before calling this method if this UserQuotaLedgerEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserQuotaLedgerEntry) Update() *UserQuotaLedgerEntryUpdateOne {
	return NewUserQuotaLedgerEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserQuotaLedgerEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserQuotaLedgerEntry) Unwrap() *UserQuotaLedgerEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserQuotaLedgerEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserQuotaLedgerEntry) String() string {
	var builder strings.Builder
	builder.WriteString("UserQuotaLedgerEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("record_type=")
	builder.WriteString(_m.RecordType)
	builder.WriteString(", ")
	builder.WriteString("cash_delta_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.CashDeltaCny))
	builder.WriteString(", ")
	builder.WriteString("paid_quota_delta_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaidQuotaDeltaUsd))
	builder.WriteString(", ")
	builder.WriteString("gift_quota_delta_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.GiftQuotaDeltaUsd))
	builder.WriteString(", ")
	builder.WriteString("cash_before_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.CashBeforeCny))
	builder.WriteString(", ")
	builder.WriteString("cash_after_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.CashAfterCny))
	builder.WriteString(", ")
	builder.WriteString("paid_before_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaidBeforeUsd))
	builder.WriteString(", ")
	builder.WriteString("paid_after_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaidAfterUsd))
	builder.WriteString(", ")
	builder.WriteString("gift_before_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.GiftBeforeUsd))
	builder.WriteString(", ")
	builder.WriteString("gift_after_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.GiftAfterUsd))
	builder.WriteString(", ")
	if v := _m.ReferenceType; v != nil {
		builder.WriteString("reference_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReferenceID; v != nil {
		builder.WriteString("reference_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	if v := _m.OperatorID; v != nil {
		builder.WriteString("operator_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserQuotaLedgerEntries is a parsable slice of UserQuotaLedgerEntry.
type UserQuotaLedgerEntries []*UserQuotaLedgerEntry
