// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userwallet"
)

// UserWalletCreate is the builder for creating a UserWallet entity.
type UserWalletCreate struct {
	config
	mutation *UserWalletMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserWalletCreate) SetUserID(v int64) *UserWalletCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCashBalanceCny sets the "cash_balance_cny" field.
func (_c *UserWalletCreate) SetCashBalanceCny(v float64) *UserWalletCreate {
	_c.mutation.SetCashBalanceCny(v)
	return _c
}

// SetNillableCashBalanceCny sets the "cash_balance_cny" field if the given value is not nil.
func (_c *UserWalletCreate) SetNillableCashBalanceCny(v *float64) *UserWalletCreate {
	if v != nil {
		_c.SetCashBalanceCny(*v)
	}
	return _c
}

// SetPaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field.
func (_c *UserWalletCreate) SetPaidQuotaBalanceUsd(v float64) *UserWalletCreate {
	_c.mutation.SetPaidQuotaBalanceUsd(v)
	return _c
}

// SetNillablePaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field if the given value is not nil.
func (_c *UserWalletCreate) SetNillablePaidQuotaBalanceUsd(v *float64) *UserWalletCreate {
	if v != nil {
		_c.SetPaidQuotaBalanceUsd(*v)
	}
	return _c
}

// SetGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field.
func (_c *UserWalletCreate) SetGiftQuotaBalanceUsd(v float64) *UserWalletCreate {
	_c.mutation.SetGiftQuotaBalanceUsd(v)
	return _c
}

// SetNillableGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field if the given value is not nil.
func (_c *UserWalletCreate) SetNillableGiftQuotaBalanceUsd(v *float64) *UserWalletCreate {
	if v != nil {
		_c.SetGiftQuotaBalanceUsd(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *UserWalletCreate) SetVersion(v int64) *UserWalletCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *UserWalletCreate) SetNillableVersion(v *int64) *UserWalletCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserWalletCreate) SetCreatedAt(v time.Time) *UserWalletCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserWalletCreate) SetNillableCreatedAt(v *time.Time) *UserWalletCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserWalletCreate) SetUpdatedAt(v time.Time) *UserWalletCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserWalletCreate) SetNillableUpdatedAt(v *time.Time) *UserWalletCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserWalletCreate) SetUser(v *User) *UserWalletCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserWalletMutation object of the builder.
func (_c *UserWalletCreate) Mutation() *UserWalletMutation {
	return _c.mutation
}

// Save creates the UserWallet in the database.
func (_c *UserWalletCreate) Save(ctx context.Context) (*UserWallet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserWalletCreate) SaveX(ctx context.Context) *UserWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserWalletCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserWalletCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserWalletCreate) defaults() {
	if _, ok := _c.mutation.CashBalanceCny(); !ok {
		v := userwallet.DefaultCashBalanceCny
		_c.mutation.SetCashBalanceCny(v)
	}
	if _, ok := _c.mutation.PaidQuotaBalanceUsd(); !ok {
		v := userwallet.DefaultPaidQuotaBalanceUsd
		_c.mutation.SetPaidQuotaBalanceUsd(v)
	}
	if _, ok := _c.mutation.GiftQuotaBalanceUsd(); !ok {
		v := userwallet.DefaultGiftQuotaBalanceUsd
		_c.mutation.SetGiftQuotaBalanceUsd(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := userwallet.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userwallet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userwallet.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserWalletCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserWallet.user_id"`)}
	}
	if _, ok := _c.mutation.CashBalanceCny(); !ok {
		return &ValidationError{Name: "cash_balance_cny", err: errors.New(`ent: missing required field "UserWallet.cash_balance_cny"`)}
	}
	if _, ok := _c.mutation.PaidQuotaBalanceUsd(); !ok {
		return &ValidationError{Name: "paid_quota_balance_usd", err: errors.New(`ent: missing required field "UserWallet.paid_quota_balance_usd"`)}
	}
	if _, ok := _c.mutation.GiftQuotaBalanceUsd(); !ok {
		return &ValidationError{Name: "gift_quota_balance_usd", err: errors.New(`ent: missing required field "UserWallet.gift_quota_balance_usd"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "UserWallet.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserWallet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserWallet.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserWallet.user"`)}
	}
	return nil
}

func (_c *UserWalletCreate) sqlSave(ctx context.Context) (*UserWallet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserWalletCreate) createSpec() (*UserWallet, *sqlgraph.CreateSpec) {
	var (
		_node = &UserWallet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userwallet.Table, sqlgraph.NewFieldSpec(userwallet.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CashBalanceCny(); ok {
		_spec.SetField(userwallet.FieldCashBalanceCny, field.TypeFloat64, value)
		_node.CashBalanceCny = value
	}
	if value, ok := _c.mutation.PaidQuotaBalanceUsd(); ok {
		_spec.SetField(userwallet.FieldPaidQuotaBalanceUsd, field.TypeFloat64, value)
		_node.PaidQuotaBalanceUsd = value
	}
	if value, ok := _c.mutation.GiftQuotaBalanceUsd(); ok {
		_spec.SetField(userwallet.FieldGiftQuotaBalanceUsd, field.TypeFloat64, value)
		_node.GiftQuotaBalanceUsd = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(userwallet.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userwallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userwallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userwallet.UserTable,
			Columns: []string{userwallet.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserWallet.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserWalletUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserWalletCreate) OnConflict(opts ...sql.ConflictOption) *UserWalletUpsertOne {
	_c.conflict = opts
	return &UserWalletUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserWalletCreate) OnConflictColumns(columns ...string) *UserWalletUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserWalletUpsertOne{
		create: _c,
	}
}

type (
	// UserWalletUpsertOne is the builder for "upsert"-ing
	//  one UserWallet node.
	UserWalletUpsertOne struct {
		create *UserWalletCreate
	}

	// UserWalletUpsert is the "OnConflict" setter.
	UserWalletUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserWalletUpsert) SetUserID(v int64) *UserWalletUpsert {
	u.Set(userwallet.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserWalletUpsert) UpdateUserID() *UserWalletUpsert {
	u.SetExcluded(userwallet.FieldUserID)
	return u
}

// SetCashBalanceCny sets the "cash_balance_cny" field.
func (u *UserWalletUpsert) SetCashBalanceCny(v float64) *UserWalletUpsert {
	u.Set(userwallet.FieldCashBalanceCny, v)
	return u
}

// UpdateCashBalanceCny sets the "cash_balance_cny" field to the value that was provided on create.
func (u *UserWalletUpsert) UpdateCashBalanceCny() *UserWalletUpsert {
	u.SetExcluded(userwallet.FieldCashBalanceCny)
	return u
}

// AddCashBalanceCny adds v to the "cash_balance_cny" field.
func (u *UserWalletUpsert) AddCashBalanceCny(v float64) *UserWalletUpsert {
	u.Add(userwallet.FieldCashBalanceCny, v)
	return u
}

// SetPaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field.
func (u *UserWalletUpsert) SetPaidQuotaBalanceUsd(v float64) *UserWalletUpsert {
	u.Set(userwallet.FieldPaidQuotaBalanceUsd, v)
	return u
}

// UpdatePaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field to the value that was provided on create.
func (u *UserWalletUpsert) UpdatePaidQuotaBalanceUsd() *UserWalletUpsert {
	u.SetExcluded(userwallet.FieldPaidQuotaBalanceUsd)
	return u
}

// AddPaidQuotaBalanceUsd adds v to the "paid_quota_balance_usd" field.
func (u *UserWalletUpsert) AddPaidQuotaBalanceUsd(v float64) *UserWalletUpsert {
	u.Add(userwallet.FieldPaidQuotaBalanceUsd, v)
	return u
}

// SetGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field.
func (u *UserWalletUpsert) SetGiftQuotaBalanceUsd(v float64) *UserWalletUpsert {
	u.Set(userwallet.FieldGiftQuotaBalanceUsd, v)
	return u
}

// UpdateGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field to the value that was provided on create.
func (u *UserWalletUpsert) UpdateGiftQuotaBalanceUsd() *UserWalletUpsert {
	u.SetExcluded(userwallet.FieldGiftQuotaBalanceUsd)
	return u
}

// AddGiftQuotaBalanceUsd adds v to the "gift_quota_balance_usd" field.
func (u *UserWalletUpsert) AddGiftQuotaBalanceUsd(v float64) *UserWalletUpsert {
	u.Add(userwallet.FieldGiftQuotaBalanceUsd, v)
	return u
}

// SetVersion sets the "version" field.
func (u *UserWalletUpsert) SetVersion(v int64) *UserWalletUpsert {
	u.Set(userwallet.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserWalletUpsert) UpdateVersion() *UserWalletUpsert {
	u.SetExcluded(userwallet.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *UserWalletUpsert) AddVersion(v int64) *UserWalletUpsert {
	u.Add(userwallet.FieldVersion, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserWalletUpsert) SetUpdatedAt(v time.Time) *UserWalletUpsert {
	u.Set(userwallet.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserWalletUpsert) UpdateUpdatedAt() *UserWalletUpsert {
	u.SetExcluded(userwallet.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserWalletUpsertOne) UpdateNewValues() *UserWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userwallet.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserWallet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserWalletUpsertOne) Ignore() *UserWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserWalletUpsertOne) DoNothing() *UserWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserWalletCreate.OnConflict
// documentation for more info.
func (u *UserWalletUpsertOne) Update(set func(*UserWalletUpsert)) *UserWalletUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserWalletUpsertOne) SetUserID(v int64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserWalletUpsertOne) UpdateUserID() *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateUserID()
	})
}

// SetCashBalanceCny sets the "cash_balance_cny" field.
func (u *UserWalletUpsertOne) SetCashBalanceCny(v float64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetCashBalanceCny(v)
	})
}

// AddCashBalanceCny adds v to the "cash_balance_cny" field.
func (u *UserWalletUpsertOne) AddCashBalanceCny(v float64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddCashBalanceCny(v)
	})
}

// UpdateCashBalanceCny sets the "cash_balance_cny" field to the value that was provided on create.
func (u *UserWalletUpsertOne) UpdateCashBalanceCny() *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateCashBalanceCny()
	})
}

// SetPaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field.
func (u *UserWalletUpsertOne) SetPaidQuotaBalanceUsd(v float64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetPaidQuotaBalanceUsd(v)
	})
}

// AddPaidQuotaBalanceUsd adds v to the "paid_quota_balance_usd" field.
func (u *UserWalletUpsertOne) AddPaidQuotaBalanceUsd(v float64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddPaidQuotaBalanceUsd(v)
	})
}

// UpdatePaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field to the value that was provided on create.
func (u *UserWalletUpsertOne) UpdatePaidQuotaBalanceUsd() *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdatePaidQuotaBalanceUsd()
	})
}

// SetGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field.
func (u *UserWalletUpsertOne) SetGiftQuotaBalanceUsd(v float64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetGiftQuotaBalanceUsd(v)
	})
}

// AddGiftQuotaBalanceUsd adds v to the "gift_quota_balance_usd" field.
func (u *UserWalletUpsertOne) AddGiftQuotaBalanceUsd(v float64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddGiftQuotaBalanceUsd(v)
	})
}

// UpdateGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field to the value that was provided on create.
func (u *UserWalletUpsertOne) UpdateGiftQuotaBalanceUsd() *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateGiftQuotaBalanceUsd()
	})
}

// SetVersion sets the "version" field.
func (u *UserWalletUpsertOne) SetVersion(v int64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserWalletUpsertOne) AddVersion(v int64) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserWalletUpsertOne) UpdateVersion() *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserWalletUpsertOne) SetUpdatedAt(v time.Time) *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserWalletUpsertOne) UpdateUpdatedAt() *UserWalletUpsertOne {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserWalletUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserWalletCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserWalletUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserWalletUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserWalletUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserWalletCreateBulk is the builder for creating many UserWallet entities in bulk.
type UserWalletCreateBulk struct {
	config
	err      error
	builders []*UserWalletCreate
	conflict []sql.ConflictOption
}

// Save creates the UserWallet entities in the database.
func (_c *UserWalletCreateBulk) Save(ctx context.Context) ([]*UserWallet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserWallet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserWalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserWalletCreateBulk) SaveX(ctx context.Context) []*UserWallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserWalletCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserWalletCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserWallet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserWalletUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserWalletCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserWalletUpsertBulk {
	_c.conflict = opts
	return &UserWalletUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserWallet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserWalletCreateBulk) OnConflictColumns(columns ...string) *UserWalletUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserWalletUpsertBulk{
		create: _c,
	}
}

// UserWalletUpsertBulk is the builder for "upsert"-ing
// a bulk of UserWallet nodes.
type UserWalletUpsertBulk struct {
	create *UserWalletCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserWallet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserWalletUpsertBulk) UpdateNewValues() *UserWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userwallet.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserWallet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserWalletUpsertBulk) Ignore() *UserWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserWalletUpsertBulk) DoNothing() *UserWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserWalletCreateBulk.OnConflict
// documentation for more info.
func (u *UserWalletUpsertBulk) Update(set func(*UserWalletUpsert)) *UserWalletUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserWalletUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserWalletUpsertBulk) SetUserID(v int64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserWalletUpsertBulk) UpdateUserID() *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateUserID()
	})
}

// SetCashBalanceCny sets the "cash_balance_cny" field.
func (u *UserWalletUpsertBulk) SetCashBalanceCny(v float64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetCashBalanceCny(v)
	})
}

// AddCashBalanceCny adds v to the "cash_balance_cny" field.
func (u *UserWalletUpsertBulk) AddCashBalanceCny(v float64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddCashBalanceCny(v)
	})
}

// UpdateCashBalanceCny sets the "cash_balance_cny" field to the value that was provided on create.
func (u *UserWalletUpsertBulk) UpdateCashBalanceCny() *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateCashBalanceCny()
	})
}

// SetPaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field.
func (u *UserWalletUpsertBulk) SetPaidQuotaBalanceUsd(v float64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetPaidQuotaBalanceUsd(v)
	})
}

// AddPaidQuotaBalanceUsd adds v to the "paid_quota_balance_usd" field.
func (u *UserWalletUpsertBulk) AddPaidQuotaBalanceUsd(v float64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddPaidQuotaBalanceUsd(v)
	})
}

// UpdatePaidQuotaBalanceUsd sets the "paid_quota_balance_usd" field to the value that was provided on create.
func (u *UserWalletUpsertBulk) UpdatePaidQuotaBalanceUsd() *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdatePaidQuotaBalanceUsd()
	})
}

// SetGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field.
func (u *UserWalletUpsertBulk) SetGiftQuotaBalanceUsd(v float64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetGiftQuotaBalanceUsd(v)
	})
}

// AddGiftQuotaBalanceUsd adds v to the "gift_quota_balance_usd" field.
func (u *UserWalletUpsertBulk) AddGiftQuotaBalanceUsd(v float64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddGiftQuotaBalanceUsd(v)
	})
}

// UpdateGiftQuotaBalanceUsd sets the "gift_quota_balance_usd" field to the value that was provided on create.
func (u *UserWalletUpsertBulk) UpdateGiftQuotaBalanceUsd() *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateGiftQuotaBalanceUsd()
	})
}

// SetVersion sets the "version" field.
func (u *UserWalletUpsertBulk) SetVersion(v int64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *UserWalletUpsertBulk) AddVersion(v int64) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *UserWalletUpsertBulk) UpdateVersion() *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserWalletUpsertBulk) SetUpdatedAt(v time.Time) *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserWalletUpsertBulk) UpdateUpdatedAt() *UserWalletUpsertBulk {
	return u.Update(func(s *UserWalletUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserWalletUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserWalletCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserWalletCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserWalletUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
