// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userquotaadjustment"
	"github.com/shopspring/decimal"
)

// UserQuotaAdjustment is the model entity for the UserQuotaAdjustment schema.
type UserQuotaAdjustment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AdjustmentType holds the value of the "adjustment_type" field.
	AdjustmentType string `json:"adjustment_type,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// ReservedAllocations holds the value of the "reserved_allocations" field.
	ReservedAllocations []map[string]interface{} `json:"reserved_allocations,omitempty"`
	// AppliedAllocations holds the value of the "applied_allocations" field.
	AppliedAllocations []map[string]interface{} `json:"applied_allocations,omitempty"`
	// RefundAmount holds the value of the "refund_amount" field.
	RefundAmount decimal.Decimal `json:"refund_amount,omitempty"`
	// RefundCurrency holds the value of the "refund_currency" field.
	RefundCurrency *string `json:"refund_currency,omitempty"`
	// RefundMethod holds the value of the "refund_method" field.
	RefundMethod *string `json:"refund_method,omitempty"`
	// RefundTradeNo holds the value of the "refund_trade_no" field.
	RefundTradeNo *string `json:"refund_trade_no,omitempty"`
	// RefundProviderInstanceID holds the value of the "refund_provider_instance_id" field.
	RefundProviderInstanceID *string `json:"refund_provider_instance_id,omitempty"`
	// ProviderRefundID holds the value of the "provider_refund_id" field.
	ProviderRefundID *string `json:"provider_refund_id,omitempty"`
	// ProviderRequestKey holds the value of the "provider_request_key" field.
	ProviderRequestKey *string `json:"provider_request_key,omitempty"`
	// ProviderState holds the value of the "provider_state" field.
	ProviderState string `json:"provider_state,omitempty"`
	// ProviderResponseSnapshot holds the value of the "provider_response_snapshot" field.
	ProviderResponseSnapshot map[string]interface{} `json:"provider_response_snapshot,omitempty"`
	// ProviderErrorCode holds the value of the "provider_error_code" field.
	ProviderErrorCode *string `json:"provider_error_code,omitempty"`
	// ProviderErrorMessage holds the value of the "provider_error_message" field.
	ProviderErrorMessage *string `json:"provider_error_message,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// LastAttemptAt holds the value of the "last_attempt_at" field.
	LastAttemptAt *time.Time `json:"last_attempt_at,omitempty"`
	// NextRetryAt holds the value of the "next_retry_at" field.
	NextRetryAt *time.Time `json:"next_retry_at,omitempty"`
	// ReconciliationNote holds the value of the "reconciliation_note" field.
	ReconciliationNote *string `json:"reconciliation_note,omitempty"`
	// ReconciledBy holds the value of the "reconciled_by" field.
	ReconciledBy *int64 `json:"reconciled_by,omitempty"`
	// ReconciledAt holds the value of the "reconciled_at" field.
	ReconciledAt *time.Time `json:"reconciled_at,omitempty"`
	// RequestedPaidQuotaUsd holds the value of the "requested_paid_quota_usd" field.
	RequestedPaidQuotaUsd decimal.Decimal `json:"requested_paid_quota_usd,omitempty"`
	// AppliedPaidQuotaUsd holds the value of the "applied_paid_quota_usd" field.
	AppliedPaidQuotaUsd decimal.Decimal `json:"applied_paid_quota_usd,omitempty"`
	// AppliedGiftQuotaUsd holds the value of the "applied_gift_quota_usd" field.
	AppliedGiftQuotaUsd decimal.Decimal `json:"applied_gift_quota_usd,omitempty"`
	// ShortfallPaidQuotaUsd holds the value of the "shortfall_paid_quota_usd" field.
	ShortfallPaidQuotaUsd decimal.Decimal `json:"shortfall_paid_quota_usd,omitempty"`
	// ForceRefund holds the value of the "force_refund" field.
	ForceRefund bool `json:"force_refund,omitempty"`
	// ApprovalReason holds the value of the "approval_reason" field.
	ApprovalReason *string `json:"approval_reason,omitempty"`
	// ApprovedBy holds the value of the "approved_by" field.
	ApprovedBy *int64 `json:"approved_by,omitempty"`
	// ApprovedAt holds the value of the "approved_at" field.
	ApprovedAt *time.Time `json:"approved_at,omitempty"`
	// FinancialExceptionRef holds the value of the "financial_exception_ref" field.
	FinancialExceptionRef *string `json:"financial_exception_ref,omitempty"`
	// OperatorUserID holds the value of the "operator_user_id" field.
	OperatorUserID *int64 `json:"operator_user_id,omitempty"`
	// ActorType holds the value of the "actor_type" field.
	ActorType string `json:"actor_type,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// AdjustedAt holds the value of the "adjusted_at" field.
	AdjustedAt *time.Time `json:"adjusted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuotaAdjustmentQuery when eager-loading is set.
	Edges        UserQuotaAdjustmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserQuotaAdjustmentEdges holds the relations/edges for other nodes in the graph.
type UserQuotaAdjustmentEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// PaymentOrder holds the value of the payment_order edge.
	PaymentOrder *PaymentOrder `json:"payment_order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuotaAdjustmentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PaymentOrderOrErr returns the PaymentOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserQuotaAdjustmentEdges) PaymentOrderOrErr() (*PaymentOrder, error) {
	if e.PaymentOrder != nil {
		return e.PaymentOrder, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "payment_order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserQuotaAdjustment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userquotaadjustment.FieldReservedAllocations, userquotaadjustment.FieldAppliedAllocations, userquotaadjustment.FieldProviderResponseSnapshot:
			values[i] = new([]byte)
		case userquotaadjustment.FieldRefundAmount, userquotaadjustment.FieldRequestedPaidQuotaUsd, userquotaadjustment.FieldAppliedPaidQuotaUsd, userquotaadjustment.FieldAppliedGiftQuotaUsd, userquotaadjustment.FieldShortfallPaidQuotaUsd:
			values[i] = new(decimal.Decimal)
		case userquotaadjustment.FieldForceRefund:
			values[i] = new(sql.NullBool)
		case userquotaadjustment.FieldID, userquotaadjustment.FieldUserID, userquotaadjustment.FieldPaymentOrderID, userquotaadjustment.FieldAttemptCount, userquotaadjustment.FieldReconciledBy, userquotaadjustment.FieldApprovedBy, userquotaadjustment.FieldOperatorUserID:
			values[i] = new(sql.NullInt64)
		case userquotaadjustment.FieldAdjustmentType, userquotaadjustment.FieldRefundCurrency, userquotaadjustment.FieldRefundMethod, userquotaadjustment.FieldRefundTradeNo, userquotaadjustment.FieldRefundProviderInstanceID, userquotaadjustment.FieldProviderRefundID, userquotaadjustment.FieldProviderRequestKey, userquotaadjustment.FieldProviderState, userquotaadjustment.FieldProviderErrorCode, userquotaadjustment.FieldProviderErrorMessage, userquotaadjustment.FieldReconciliationNote, userquotaadjustment.FieldApprovalReason, userquotaadjustment.FieldFinancialExceptionRef, userquotaadjustment.FieldActorType, userquotaadjustment.FieldReason, userquotaadjustment.FieldStatus, userquotaadjustment.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case userquotaadjustment.FieldLastAttemptAt, userquotaadjustment.FieldNextRetryAt, userquotaadjustment.FieldReconciledAt, userquotaadjustment.FieldApprovedAt, userquotaadjustment.FieldAdjustedAt, userquotaadjustment.FieldCreatedAt, userquotaadjustment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserQuotaAdjustment fields.
func (_m *UserQuotaAdjustment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userquotaadjustment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userquotaadjustment.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userquotaadjustment.FieldAdjustmentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adjustment_type", values[i])
			} else if value.Valid {
				_m.AdjustmentType = value.String
			}
		case userquotaadjustment.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case userquotaadjustment.FieldReservedAllocations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_allocations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ReservedAllocations); err != nil {
					return fmt.Errorf("unmarshal field reserved_allocations: %w", err)
				}
			}
		case userquotaadjustment.FieldAppliedAllocations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field applied_allocations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AppliedAllocations); err != nil {
					return fmt.Errorf("unmarshal field applied_allocations: %w", err)
				}
			}
		case userquotaadjustment.FieldRefundAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field refund_amount", values[i])
			} else if value != nil {
				_m.RefundAmount = *value
			}
		case userquotaadjustment.FieldRefundCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_currency", values[i])
			} else if value.Valid {
				_m.RefundCurrency = new(string)
				*_m.RefundCurrency = value.String
			}
		case userquotaadjustment.FieldRefundMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_method", values[i])
			} else if value.Valid {
				_m.RefundMethod = new(string)
				*_m.RefundMethod = value.String
			}
		case userquotaadjustment.FieldRefundTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_trade_no", values[i])
			} else if value.Valid {
				_m.RefundTradeNo = new(string)
				*_m.RefundTradeNo = value.String
			}
		case userquotaadjustment.FieldRefundProviderInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_provider_instance_id", values[i])
			} else if value.Valid {
				_m.RefundProviderInstanceID = new(string)
				*_m.RefundProviderInstanceID = value.String
			}
		case userquotaadjustment.FieldProviderRefundID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_refund_id", values[i])
			} else if value.Valid {
				_m.ProviderRefundID = new(string)
				*_m.ProviderRefundID = value.String
			}
		case userquotaadjustment.FieldProviderRequestKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_request_key", values[i])
			} else if value.Valid {
				_m.ProviderRequestKey = new(string)
				*_m.ProviderRequestKey = value.String
			}
		case userquotaadjustment.FieldProviderState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_state", values[i])
			} else if value.Valid {
				_m.ProviderState = value.String
			}
		case userquotaadjustment.FieldProviderResponseSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field provider_response_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ProviderResponseSnapshot); err != nil {
					return fmt.Errorf("unmarshal field provider_response_snapshot: %w", err)
				}
			}
		case userquotaadjustment.FieldProviderErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_error_code", values[i])
			} else if value.Valid {
				_m.ProviderErrorCode = new(string)
				*_m.ProviderErrorCode = value.String
			}
		case userquotaadjustment.FieldProviderErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_error_message", values[i])
			} else if value.Valid {
				_m.ProviderErrorMessage = new(string)
				*_m.ProviderErrorMessage = value.String
			}
		case userquotaadjustment.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case userquotaadjustment.FieldLastAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_attempt_at", values[i])
			} else if value.Valid {
				_m.LastAttemptAt = new(time.Time)
				*_m.LastAttemptAt = value.Time
			}
		case userquotaadjustment.FieldNextRetryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_retry_at", values[i])
			} else if value.Valid {
				_m.NextRetryAt = new(time.Time)
				*_m.NextRetryAt = value.Time
			}
		case userquotaadjustment.FieldReconciliationNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reconciliation_note", values[i])
			} else if value.Valid {
				_m.ReconciliationNote = new(string)
				*_m.ReconciliationNote = value.String
			}
		case userquotaadjustment.FieldReconciledBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reconciled_by", values[i])
			} else if value.Valid {
				_m.ReconciledBy = new(int64)
				*_m.ReconciledBy = value.Int64
			}
		case userquotaadjustment.FieldReconciledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reconciled_at", values[i])
			} else if value.Valid {
				_m.ReconciledAt = new(time.Time)
				*_m.ReconciledAt = value.Time
			}
		case userquotaadjustment.FieldRequestedPaidQuotaUsd:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field requested_paid_quota_usd", values[i])
			} else if value != nil {
				_m.RequestedPaidQuotaUsd = *value
			}
		case userquotaadjustment.FieldAppliedPaidQuotaUsd:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field applied_paid_quota_usd", values[i])
			} else if value != nil {
				_m.AppliedPaidQuotaUsd = *value
			}
		case userquotaadjustment.FieldAppliedGiftQuotaUsd:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field applied_gift_quota_usd", values[i])
			} else if value != nil {
				_m.AppliedGiftQuotaUsd = *value
			}
		case userquotaadjustment.FieldShortfallPaidQuotaUsd:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field shortfall_paid_quota_usd", values[i])
			} else if value != nil {
				_m.ShortfallPaidQuotaUsd = *value
			}
		case userquotaadjustment.FieldForceRefund:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field force_refund", values[i])
			} else if value.Valid {
				_m.ForceRefund = value.Bool
			}
		case userquotaadjustment.FieldApprovalReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field approval_reason", values[i])
			} else if value.Valid {
				_m.ApprovalReason = new(string)
				*_m.ApprovalReason = value.String
			}
		case userquotaadjustment.FieldApprovedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approved_by", values[i])
			} else if value.Valid {
				_m.ApprovedBy = new(int64)
				*_m.ApprovedBy = value.Int64
			}
		case userquotaadjustment.FieldApprovedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field approved_at", values[i])
			} else if value.Valid {
				_m.ApprovedAt = new(time.Time)
				*_m.ApprovedAt = value.Time
			}
		case userquotaadjustment.FieldFinancialExceptionRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field financial_exception_ref", values[i])
			} else if value.Valid {
				_m.FinancialExceptionRef = new(string)
				*_m.FinancialExceptionRef = value.String
			}
		case userquotaadjustment.FieldOperatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_user_id", values[i])
			} else if value.Valid {
				_m.OperatorUserID = new(int64)
				*_m.OperatorUserID = value.Int64
			}
		case userquotaadjustment.FieldActorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_type", values[i])
			} else if value.Valid {
				_m.ActorType = value.String
			}
		case userquotaadjustment.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case userquotaadjustment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case userquotaadjustment.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case userquotaadjustment.FieldAdjustedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field adjusted_at", values[i])
			} else if value.Valid {
				_m.AdjustedAt = new(time.Time)
				*_m.AdjustedAt = value.Time
			}
		case userquotaadjustment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userquotaadjustment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserQuotaAdjustment.
// This includes values selected through modifiers, order, etc.
func (_m *UserQuotaAdjustment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserQuotaAdjustment entity.
func (_m *UserQuotaAdjustment) QueryUser() *UserQuery {
	return NewUserQuotaAdjustmentClient(_m.config).QueryUser(_m)
}

// QueryPaymentOrder queries the "payment_order" edge of the UserQuotaAdjustment entity.
func (_m *UserQuotaAdjustment) QueryPaymentOrder() *PaymentOrderQuery {
	return NewUserQuotaAdjustmentClient(_m.config).QueryPaymentOrder(_m)
}

// Update returns a builder for updating this UserQuotaAdjustment.
// Note that you need to call UserQuotaAdjustment.Unwrap() before calling this method if this UserQuotaAdjustment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserQuotaAdjustment) Update() *UserQuotaAdjustmentUpdateOne {
	return NewUserQuotaAdjustmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserQuotaAdjustment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserQuotaAdjustment) Unwrap() *UserQuotaAdjustment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserQuotaAdjustment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserQuotaAdjustment) String() string {
	var builder strings.Builder
	builder.WriteString("UserQuotaAdjustment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("adjustment_type=")
	builder.WriteString(_m.AdjustmentType)
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reserved_allocations=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedAllocations))
	builder.WriteString(", ")
	builder.WriteString("applied_allocations=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppliedAllocations))
	builder.WriteString(", ")
	builder.WriteString("refund_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundAmount))
	builder.WriteString(", ")
	if v := _m.RefundCurrency; v != nil {
		builder.WriteString("refund_currency=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RefundMethod; v != nil {
		builder.WriteString("refund_method=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RefundTradeNo; v != nil {
		builder.WriteString("refund_trade_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RefundProviderInstanceID; v != nil {
		builder.WriteString("refund_provider_instance_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderRefundID; v != nil {
		builder.WriteString("provider_refund_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderRequestKey; v != nil {
		builder.WriteString("provider_request_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("provider_state=")
	builder.WriteString(_m.ProviderState)
	builder.WriteString(", ")
	builder.WriteString("provider_response_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderResponseSnapshot))
	builder.WriteString(", ")
	if v := _m.ProviderErrorCode; v != nil {
		builder.WriteString("provider_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderErrorMessage; v != nil {
		builder.WriteString("provider_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	if v := _m.LastAttemptAt; v != nil {
		builder.WriteString("last_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextRetryAt; v != nil {
		builder.WriteString("next_retry_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReconciliationNote; v != nil {
		builder.WriteString("reconciliation_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReconciledBy; v != nil {
		builder.WriteString("reconciled_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReconciledAt; v != nil {
		builder.WriteString("reconciled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("requested_paid_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedPaidQuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("applied_paid_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppliedPaidQuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("applied_gift_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppliedGiftQuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("shortfall_paid_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShortfallPaidQuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("force_refund=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForceRefund))
	builder.WriteString(", ")
	if v := _m.ApprovalReason; v != nil {
		builder.WriteString("approval_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ApprovedBy; v != nil {
		builder.WriteString("approved_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ApprovedAt; v != nil {
		builder.WriteString("approved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinancialExceptionRef; v != nil {
		builder.WriteString("financial_exception_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OperatorUserID; v != nil {
		builder.WriteString("operator_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("actor_type=")
	builder.WriteString(_m.ActorType)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	if v := _m.AdjustedAt; v != nil {
		builder.WriteString("adjusted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserQuotaAdjustments is a parsable slice of UserQuotaAdjustment.
type UserQuotaAdjustments []*UserQuotaAdjustment
