// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/promocodeusage"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userquotagrant"
	"github.com/shopspring/decimal"
)

// UserQuotaGrantCreate is the builder for creating a UserQuotaGrant entity.
type UserQuotaGrantCreate struct {
	config
	mutation *UserQuotaGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserQuotaGrantCreate) SetUserID(v int64) *UserQuotaGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGrantType sets the "grant_type" field.
func (_c *UserQuotaGrantCreate) SetGrantType(v string) *UserQuotaGrantCreate {
	_c.mutation.SetGrantType(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *UserQuotaGrantCreate) SetPaymentOrderID(v int64) *UserQuotaGrantCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillablePaymentOrderID(v *int64) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *UserQuotaGrantCreate) SetRedeemCodeID(v int64) *UserQuotaGrantCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableRedeemCodeID(v *int64) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetRedeemCodeID(*v)
	}
	return _c
}

// SetPromoCodeUsageID sets the "promo_code_usage_id" field.
func (_c *UserQuotaGrantCreate) SetPromoCodeUsageID(v int64) *UserQuotaGrantCreate {
	_c.mutation.SetPromoCodeUsageID(v)
	return _c
}

// SetNillablePromoCodeUsageID sets the "promo_code_usage_id" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillablePromoCodeUsageID(v *int64) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetPromoCodeUsageID(*v)
	}
	return _c
}

// SetAffiliateLedgerID sets the "affiliate_ledger_id" field.
func (_c *UserQuotaGrantCreate) SetAffiliateLedgerID(v int64) *UserQuotaGrantCreate {
	_c.mutation.SetAffiliateLedgerID(v)
	return _c
}

// SetNillableAffiliateLedgerID sets the "affiliate_ledger_id" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableAffiliateLedgerID(v *int64) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetAffiliateLedgerID(*v)
	}
	return _c
}

// SetPaidQuotaUsd sets the "paid_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetPaidQuotaUsd(v)
	return _c
}

// SetNillablePaidQuotaUsd sets the "paid_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillablePaidQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetPaidQuotaUsd(*v)
	}
	return _c
}

// SetGiftQuotaUsd sets the "gift_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetGiftQuotaUsd(v)
	return _c
}

// SetNillableGiftQuotaUsd sets the "gift_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableGiftQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetGiftQuotaUsd(*v)
	}
	return _c
}

// SetTotalQuotaUsd sets the "total_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetTotalQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetTotalQuotaUsd(v)
	return _c
}

// SetNillableTotalQuotaUsd sets the "total_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableTotalQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetTotalQuotaUsd(*v)
	}
	return _c
}

// SetConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetConsumedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetConsumedPaidQuotaUsd(v)
	return _c
}

// SetNillableConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableConsumedPaidQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetConsumedPaidQuotaUsd(*v)
	}
	return _c
}

// SetConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetConsumedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetConsumedGiftQuotaUsd(v)
	return _c
}

// SetNillableConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableConsumedGiftQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetConsumedGiftQuotaUsd(*v)
	}
	return _c
}

// SetRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetRefundedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetRefundedPaidQuotaUsd(v)
	return _c
}

// SetNillableRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableRefundedPaidQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetRefundedPaidQuotaUsd(*v)
	}
	return _c
}

// SetDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetDeductedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetDeductedGiftQuotaUsd(v)
	return _c
}

// SetNillableDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableDeductedGiftQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetDeductedGiftQuotaUsd(*v)
	}
	return _c
}

// SetReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetReservedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetReservedPaidQuotaUsd(v)
	return _c
}

// SetNillableReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableReservedPaidQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetReservedPaidQuotaUsd(*v)
	}
	return _c
}

// SetLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field.
func (_c *UserQuotaGrantCreate) SetLegacyDebtOffsetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantCreate {
	_c.mutation.SetLegacyDebtOffsetPaidQuotaUsd(v)
	return _c
}

// SetNillableLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableLegacyDebtOffsetPaidQuotaUsd(v *decimal.Decimal) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetLegacyDebtOffsetPaidQuotaUsd(*v)
	}
	return _c
}

// SetOperatorUserID sets the "operator_user_id" field.
func (_c *UserQuotaGrantCreate) SetOperatorUserID(v int64) *UserQuotaGrantCreate {
	_c.mutation.SetOperatorUserID(v)
	return _c
}

// SetNillableOperatorUserID sets the "operator_user_id" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableOperatorUserID(v *int64) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetOperatorUserID(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *UserQuotaGrantCreate) SetIdempotencyKey(v string) *UserQuotaGrantCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableIdempotencyKey(v *string) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetRuleSnapshot sets the "rule_snapshot" field.
func (_c *UserQuotaGrantCreate) SetRuleSnapshot(v map[string]interface{}) *UserQuotaGrantCreate {
	_c.mutation.SetRuleSnapshot(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *UserQuotaGrantCreate) SetNote(v string) *UserQuotaGrantCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableNote(v *string) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetGrantedAt sets the "granted_at" field.
func (_c *UserQuotaGrantCreate) SetGrantedAt(v time.Time) *UserQuotaGrantCreate {
	_c.mutation.SetGrantedAt(v)
	return _c
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableGrantedAt(v *time.Time) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetGrantedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserQuotaGrantCreate) SetCreatedAt(v time.Time) *UserQuotaGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserQuotaGrantCreate) SetNillableCreatedAt(v *time.Time) *UserQuotaGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserQuotaGrantCreate) SetUser(v *User) *UserQuotaGrantCreate {
	return _c.SetUserID(v.ID)
}

// SetPaymentOrder sets the "payment_order" edge to the PaymentOrder entity.
func (_c *UserQuotaGrantCreate) SetPaymentOrder(v *PaymentOrder) *UserQuotaGrantCreate {
	return _c.SetPaymentOrderID(v.ID)
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_c *UserQuotaGrantCreate) SetRedeemCode(v *RedeemCode) *UserQuotaGrantCreate {
	return _c.SetRedeemCodeID(v.ID)
}

// SetPromoCodeUsage sets the "promo_code_usage" edge to the PromoCodeUsage entity.
func (_c *UserQuotaGrantCreate) SetPromoCodeUsage(v *PromoCodeUsage) *UserQuotaGrantCreate {
	return _c.SetPromoCodeUsageID(v.ID)
}

// Mutation returns the UserQuotaGrantMutation object of the builder.
func (_c *UserQuotaGrantCreate) Mutation() *UserQuotaGrantMutation {
	return _c.mutation
}

// Save creates the UserQuotaGrant in the database.
func (_c *UserQuotaGrantCreate) Save(ctx context.Context) (*UserQuotaGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserQuotaGrantCreate) SaveX(ctx context.Context) *UserQuotaGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserQuotaGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserQuotaGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserQuotaGrantCreate) defaults() {
	if _, ok := _c.mutation.PaidQuotaUsd(); !ok {
		v := userquotagrant.DefaultPaidQuotaUsd
		_c.mutation.SetPaidQuotaUsd(v)
	}
	if _, ok := _c.mutation.GiftQuotaUsd(); !ok {
		v := userquotagrant.DefaultGiftQuotaUsd
		_c.mutation.SetGiftQuotaUsd(v)
	}
	if _, ok := _c.mutation.TotalQuotaUsd(); !ok {
		v := userquotagrant.DefaultTotalQuotaUsd
		_c.mutation.SetTotalQuotaUsd(v)
	}
	if _, ok := _c.mutation.ConsumedPaidQuotaUsd(); !ok {
		v := userquotagrant.DefaultConsumedPaidQuotaUsd
		_c.mutation.SetConsumedPaidQuotaUsd(v)
	}
	if _, ok := _c.mutation.ConsumedGiftQuotaUsd(); !ok {
		v := userquotagrant.DefaultConsumedGiftQuotaUsd
		_c.mutation.SetConsumedGiftQuotaUsd(v)
	}
	if _, ok := _c.mutation.RefundedPaidQuotaUsd(); !ok {
		v := userquotagrant.DefaultRefundedPaidQuotaUsd
		_c.mutation.SetRefundedPaidQuotaUsd(v)
	}
	if _, ok := _c.mutation.DeductedGiftQuotaUsd(); !ok {
		v := userquotagrant.DefaultDeductedGiftQuotaUsd
		_c.mutation.SetDeductedGiftQuotaUsd(v)
	}
	if _, ok := _c.mutation.ReservedPaidQuotaUsd(); !ok {
		v := userquotagrant.DefaultReservedPaidQuotaUsd
		_c.mutation.SetReservedPaidQuotaUsd(v)
	}
	if _, ok := _c.mutation.LegacyDebtOffsetPaidQuotaUsd(); !ok {
		v := userquotagrant.DefaultLegacyDebtOffsetPaidQuotaUsd
		_c.mutation.SetLegacyDebtOffsetPaidQuotaUsd(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := userquotagrant.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		v := userquotagrant.DefaultGrantedAt()
		_c.mutation.SetGrantedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userquotagrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserQuotaGrantCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserQuotaGrant.user_id"`)}
	}
	if _, ok := _c.mutation.GrantType(); !ok {
		return &ValidationError{Name: "grant_type", err: errors.New(`ent: missing required field "UserQuotaGrant.grant_type"`)}
	}
	if v, ok := _c.mutation.GrantType(); ok {
		if err := userquotagrant.GrantTypeValidator(v); err != nil {
			return &ValidationError{Name: "grant_type", err: fmt.Errorf(`ent: validator failed for field "UserQuotaGrant.grant_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaidQuotaUsd(); !ok {
		return &ValidationError{Name: "paid_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.paid_quota_usd"`)}
	}
	if _, ok := _c.mutation.GiftQuotaUsd(); !ok {
		return &ValidationError{Name: "gift_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.gift_quota_usd"`)}
	}
	if _, ok := _c.mutation.TotalQuotaUsd(); !ok {
		return &ValidationError{Name: "total_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.total_quota_usd"`)}
	}
	if _, ok := _c.mutation.ConsumedPaidQuotaUsd(); !ok {
		return &ValidationError{Name: "consumed_paid_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.consumed_paid_quota_usd"`)}
	}
	if _, ok := _c.mutation.ConsumedGiftQuotaUsd(); !ok {
		return &ValidationError{Name: "consumed_gift_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.consumed_gift_quota_usd"`)}
	}
	if _, ok := _c.mutation.RefundedPaidQuotaUsd(); !ok {
		return &ValidationError{Name: "refunded_paid_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.refunded_paid_quota_usd"`)}
	}
	if _, ok := _c.mutation.DeductedGiftQuotaUsd(); !ok {
		return &ValidationError{Name: "deducted_gift_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.deducted_gift_quota_usd"`)}
	}
	if _, ok := _c.mutation.ReservedPaidQuotaUsd(); !ok {
		return &ValidationError{Name: "reserved_paid_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.reserved_paid_quota_usd"`)}
	}
	if _, ok := _c.mutation.LegacyDebtOffsetPaidQuotaUsd(); !ok {
		return &ValidationError{Name: "legacy_debt_offset_paid_quota_usd", err: errors.New(`ent: missing required field "UserQuotaGrant.legacy_debt_offset_paid_quota_usd"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := userquotagrant.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "UserQuotaGrant.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RuleSnapshot(); !ok {
		return &ValidationError{Name: "rule_snapshot", err: errors.New(`ent: missing required field "UserQuotaGrant.rule_snapshot"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "UserQuotaGrant.note"`)}
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		return &ValidationError{Name: "granted_at", err: errors.New(`ent: missing required field "UserQuotaGrant.granted_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserQuotaGrant.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserQuotaGrant.user"`)}
	}
	return nil
}

func (_c *UserQuotaGrantCreate) sqlSave(ctx context.Context) (*UserQuotaGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserQuotaGrantCreate) createSpec() (*UserQuotaGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &UserQuotaGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userquotagrant.Table, sqlgraph.NewFieldSpec(userquotagrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GrantType(); ok {
		_spec.SetField(userquotagrant.FieldGrantType, field.TypeString, value)
		_node.GrantType = value
	}
	if value, ok := _c.mutation.AffiliateLedgerID(); ok {
		_spec.SetField(userquotagrant.FieldAffiliateLedgerID, field.TypeInt64, value)
		_node.AffiliateLedgerID = &value
	}
	if value, ok := _c.mutation.PaidQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldPaidQuotaUsd, field.TypeOther, value)
		_node.PaidQuotaUsd = value
	}
	if value, ok := _c.mutation.GiftQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldGiftQuotaUsd, field.TypeOther, value)
		_node.GiftQuotaUsd = value
	}
	if value, ok := _c.mutation.TotalQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldTotalQuotaUsd, field.TypeOther, value)
		_node.TotalQuotaUsd = value
	}
	if value, ok := _c.mutation.ConsumedPaidQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldConsumedPaidQuotaUsd, field.TypeOther, value)
		_node.ConsumedPaidQuotaUsd = value
	}
	if value, ok := _c.mutation.ConsumedGiftQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldConsumedGiftQuotaUsd, field.TypeOther, value)
		_node.ConsumedGiftQuotaUsd = value
	}
	if value, ok := _c.mutation.RefundedPaidQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldRefundedPaidQuotaUsd, field.TypeOther, value)
		_node.RefundedPaidQuotaUsd = value
	}
	if value, ok := _c.mutation.DeductedGiftQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldDeductedGiftQuotaUsd, field.TypeOther, value)
		_node.DeductedGiftQuotaUsd = value
	}
	if value, ok := _c.mutation.ReservedPaidQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldReservedPaidQuotaUsd, field.TypeOther, value)
		_node.ReservedPaidQuotaUsd = value
	}
	if value, ok := _c.mutation.LegacyDebtOffsetPaidQuotaUsd(); ok {
		_spec.SetField(userquotagrant.FieldLegacyDebtOffsetPaidQuotaUsd, field.TypeOther, value)
		_node.LegacyDebtOffsetPaidQuotaUsd = value
	}
	if value, ok := _c.mutation.OperatorUserID(); ok {
		_spec.SetField(userquotagrant.FieldOperatorUserID, field.TypeInt64, value)
		_node.OperatorUserID = &value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(userquotagrant.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.RuleSnapshot(); ok {
		_spec.SetField(userquotagrant.FieldRuleSnapshot, field.TypeJSON, value)
		_node.RuleSnapshot = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(userquotagrant.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.GrantedAt(); ok {
		_spec.SetField(userquotagrant.FieldGrantedAt, field.TypeTime, value)
		_node.GrantedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userquotagrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquotagrant.UserTable,
			Columns: []string{userquotagrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaymentOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquotagrant.PaymentOrderTable,
			Columns: []string{userquotagrant.PaymentOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PaymentOrderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquotagrant.RedeemCodeTable,
			Columns: []string{userquotagrant.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedeemCodeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PromoCodeUsageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userquotagrant.PromoCodeUsageTable,
			Columns: []string{userquotagrant.PromoCodeUsageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PromoCodeUsageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserQuotaGrant.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserQuotaGrantUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserQuotaGrantCreate) OnConflict(opts ...sql.ConflictOption) *UserQuotaGrantUpsertOne {
	_c.conflict = opts
	return &UserQuotaGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserQuotaGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserQuotaGrantCreate) OnConflictColumns(columns ...string) *UserQuotaGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserQuotaGrantUpsertOne{
		create: _c,
	}
}

type (
	// UserQuotaGrantUpsertOne is the builder for "upsert"-ing
	//  one UserQuotaGrant node.
	UserQuotaGrantUpsertOne struct {
		create *UserQuotaGrantCreate
	}

	// UserQuotaGrantUpsert is the "OnConflict" setter.
	UserQuotaGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserQuotaGrantUpsert) SetUserID(v int64) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateUserID() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldUserID)
	return u
}

// SetGrantType sets the "grant_type" field.
func (u *UserQuotaGrantUpsert) SetGrantType(v string) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldGrantType, v)
	return u
}

// UpdateGrantType sets the "grant_type" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateGrantType() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldGrantType)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *UserQuotaGrantUpsert) SetPaymentOrderID(v int64) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdatePaymentOrderID() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldPaymentOrderID)
	return u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *UserQuotaGrantUpsert) ClearPaymentOrderID() *UserQuotaGrantUpsert {
	u.SetNull(userquotagrant.FieldPaymentOrderID)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *UserQuotaGrantUpsert) SetRedeemCodeID(v int64) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateRedeemCodeID() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldRedeemCodeID)
	return u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *UserQuotaGrantUpsert) ClearRedeemCodeID() *UserQuotaGrantUpsert {
	u.SetNull(userquotagrant.FieldRedeemCodeID)
	return u
}

// SetPromoCodeUsageID sets the "promo_code_usage_id" field.
func (u *UserQuotaGrantUpsert) SetPromoCodeUsageID(v int64) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldPromoCodeUsageID, v)
	return u
}

// UpdatePromoCodeUsageID sets the "promo_code_usage_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdatePromoCodeUsageID() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldPromoCodeUsageID)
	return u
}

// ClearPromoCodeUsageID clears the value of the "promo_code_usage_id" field.
func (u *UserQuotaGrantUpsert) ClearPromoCodeUsageID() *UserQuotaGrantUpsert {
	u.SetNull(userquotagrant.FieldPromoCodeUsageID)
	return u
}

// SetAffiliateLedgerID sets the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsert) SetAffiliateLedgerID(v int64) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldAffiliateLedgerID, v)
	return u
}

// UpdateAffiliateLedgerID sets the "affiliate_ledger_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateAffiliateLedgerID() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldAffiliateLedgerID)
	return u
}

// AddAffiliateLedgerID adds v to the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsert) AddAffiliateLedgerID(v int64) *UserQuotaGrantUpsert {
	u.Add(userquotagrant.FieldAffiliateLedgerID, v)
	return u
}

// ClearAffiliateLedgerID clears the value of the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsert) ClearAffiliateLedgerID() *UserQuotaGrantUpsert {
	u.SetNull(userquotagrant.FieldAffiliateLedgerID)
	return u
}

// SetPaidQuotaUsd sets the "paid_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldPaidQuotaUsd, v)
	return u
}

// UpdatePaidQuotaUsd sets the "paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdatePaidQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldPaidQuotaUsd)
	return u
}

// SetGiftQuotaUsd sets the "gift_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldGiftQuotaUsd, v)
	return u
}

// UpdateGiftQuotaUsd sets the "gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateGiftQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldGiftQuotaUsd)
	return u
}

// SetTotalQuotaUsd sets the "total_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetTotalQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldTotalQuotaUsd, v)
	return u
}

// UpdateTotalQuotaUsd sets the "total_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateTotalQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldTotalQuotaUsd)
	return u
}

// SetConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetConsumedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldConsumedPaidQuotaUsd, v)
	return u
}

// UpdateConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateConsumedPaidQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldConsumedPaidQuotaUsd)
	return u
}

// SetConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetConsumedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldConsumedGiftQuotaUsd, v)
	return u
}

// UpdateConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateConsumedGiftQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldConsumedGiftQuotaUsd)
	return u
}

// SetRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetRefundedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldRefundedPaidQuotaUsd, v)
	return u
}

// UpdateRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateRefundedPaidQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldRefundedPaidQuotaUsd)
	return u
}

// SetDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetDeductedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldDeductedGiftQuotaUsd, v)
	return u
}

// UpdateDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateDeductedGiftQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldDeductedGiftQuotaUsd)
	return u
}

// SetReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetReservedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldReservedPaidQuotaUsd, v)
	return u
}

// UpdateReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateReservedPaidQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldReservedPaidQuotaUsd)
	return u
}

// SetLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field.
func (u *UserQuotaGrantUpsert) SetLegacyDebtOffsetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldLegacyDebtOffsetPaidQuotaUsd, v)
	return u
}

// UpdateLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateLegacyDebtOffsetPaidQuotaUsd() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldLegacyDebtOffsetPaidQuotaUsd)
	return u
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserQuotaGrantUpsert) SetOperatorUserID(v int64) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldOperatorUserID, v)
	return u
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateOperatorUserID() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldOperatorUserID)
	return u
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserQuotaGrantUpsert) AddOperatorUserID(v int64) *UserQuotaGrantUpsert {
	u.Add(userquotagrant.FieldOperatorUserID, v)
	return u
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *UserQuotaGrantUpsert) ClearOperatorUserID() *UserQuotaGrantUpsert {
	u.SetNull(userquotagrant.FieldOperatorUserID)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *UserQuotaGrantUpsert) SetIdempotencyKey(v string) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateIdempotencyKey() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *UserQuotaGrantUpsert) ClearIdempotencyKey() *UserQuotaGrantUpsert {
	u.SetNull(userquotagrant.FieldIdempotencyKey)
	return u
}

// SetRuleSnapshot sets the "rule_snapshot" field.
func (u *UserQuotaGrantUpsert) SetRuleSnapshot(v map[string]interface{}) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldRuleSnapshot, v)
	return u
}

// UpdateRuleSnapshot sets the "rule_snapshot" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateRuleSnapshot() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldRuleSnapshot)
	return u
}

// SetNote sets the "note" field.
func (u *UserQuotaGrantUpsert) SetNote(v string) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateNote() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldNote)
	return u
}

// SetGrantedAt sets the "granted_at" field.
func (u *UserQuotaGrantUpsert) SetGrantedAt(v time.Time) *UserQuotaGrantUpsert {
	u.Set(userquotagrant.FieldGrantedAt, v)
	return u
}

// UpdateGrantedAt sets the "granted_at" field to the value that was provided on create.
func (u *UserQuotaGrantUpsert) UpdateGrantedAt() *UserQuotaGrantUpsert {
	u.SetExcluded(userquotagrant.FieldGrantedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserQuotaGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserQuotaGrantUpsertOne) UpdateNewValues() *UserQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userquotagrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserQuotaGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserQuotaGrantUpsertOne) Ignore() *UserQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserQuotaGrantUpsertOne) DoNothing() *UserQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserQuotaGrantCreate.OnConflict
// documentation for more info.
func (u *UserQuotaGrantUpsertOne) Update(set func(*UserQuotaGrantUpsert)) *UserQuotaGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserQuotaGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserQuotaGrantUpsertOne) SetUserID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateUserID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGrantType sets the "grant_type" field.
func (u *UserQuotaGrantUpsertOne) SetGrantType(v string) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetGrantType(v)
	})
}

// UpdateGrantType sets the "grant_type" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateGrantType() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateGrantType()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *UserQuotaGrantUpsertOne) SetPaymentOrderID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdatePaymentOrderID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *UserQuotaGrantUpsertOne) ClearPaymentOrderID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *UserQuotaGrantUpsertOne) SetRedeemCodeID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateRedeemCodeID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *UserQuotaGrantUpsertOne) ClearRedeemCodeID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetPromoCodeUsageID sets the "promo_code_usage_id" field.
func (u *UserQuotaGrantUpsertOne) SetPromoCodeUsageID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetPromoCodeUsageID(v)
	})
}

// UpdatePromoCodeUsageID sets the "promo_code_usage_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdatePromoCodeUsageID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdatePromoCodeUsageID()
	})
}

// ClearPromoCodeUsageID clears the value of the "promo_code_usage_id" field.
func (u *UserQuotaGrantUpsertOne) ClearPromoCodeUsageID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearPromoCodeUsageID()
	})
}

// SetAffiliateLedgerID sets the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsertOne) SetAffiliateLedgerID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetAffiliateLedgerID(v)
	})
}

// AddAffiliateLedgerID adds v to the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsertOne) AddAffiliateLedgerID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.AddAffiliateLedgerID(v)
	})
}

// UpdateAffiliateLedgerID sets the "affiliate_ledger_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateAffiliateLedgerID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateAffiliateLedgerID()
	})
}

// ClearAffiliateLedgerID clears the value of the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsertOne) ClearAffiliateLedgerID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearAffiliateLedgerID()
	})
}

// SetPaidQuotaUsd sets the "paid_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetPaidQuotaUsd(v)
	})
}

// UpdatePaidQuotaUsd sets the "paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdatePaidQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdatePaidQuotaUsd()
	})
}

// SetGiftQuotaUsd sets the "gift_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetGiftQuotaUsd(v)
	})
}

// UpdateGiftQuotaUsd sets the "gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateGiftQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateGiftQuotaUsd()
	})
}

// SetTotalQuotaUsd sets the "total_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetTotalQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetTotalQuotaUsd(v)
	})
}

// UpdateTotalQuotaUsd sets the "total_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateTotalQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateTotalQuotaUsd()
	})
}

// SetConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetConsumedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetConsumedPaidQuotaUsd(v)
	})
}

// UpdateConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateConsumedPaidQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateConsumedPaidQuotaUsd()
	})
}

// SetConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetConsumedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetConsumedGiftQuotaUsd(v)
	})
}

// UpdateConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateConsumedGiftQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateConsumedGiftQuotaUsd()
	})
}

// SetRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetRefundedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetRefundedPaidQuotaUsd(v)
	})
}

// UpdateRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateRefundedPaidQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateRefundedPaidQuotaUsd()
	})
}

// SetDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetDeductedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetDeductedGiftQuotaUsd(v)
	})
}

// UpdateDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateDeductedGiftQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateDeductedGiftQuotaUsd()
	})
}

// SetReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetReservedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetReservedPaidQuotaUsd(v)
	})
}

// UpdateReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateReservedPaidQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateReservedPaidQuotaUsd()
	})
}

// SetLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertOne) SetLegacyDebtOffsetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetLegacyDebtOffsetPaidQuotaUsd(v)
	})
}

// UpdateLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateLegacyDebtOffsetPaidQuotaUsd() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateLegacyDebtOffsetPaidQuotaUsd()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserQuotaGrantUpsertOne) SetOperatorUserID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserQuotaGrantUpsertOne) AddOperatorUserID(v int64) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateOperatorUserID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *UserQuotaGrantUpsertOne) ClearOperatorUserID() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *UserQuotaGrantUpsertOne) SetIdempotencyKey(v string) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateIdempotencyKey() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *UserQuotaGrantUpsertOne) ClearIdempotencyKey() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetRuleSnapshot sets the "rule_snapshot" field.
func (u *UserQuotaGrantUpsertOne) SetRuleSnapshot(v map[string]interface{}) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetRuleSnapshot(v)
	})
}

// UpdateRuleSnapshot sets the "rule_snapshot" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateRuleSnapshot() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateRuleSnapshot()
	})
}

// SetNote sets the "note" field.
func (u *UserQuotaGrantUpsertOne) SetNote(v string) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateNote() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateNote()
	})
}

// SetGrantedAt sets the "granted_at" field.
func (u *UserQuotaGrantUpsertOne) SetGrantedAt(v time.Time) *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetGrantedAt(v)
	})
}

// UpdateGrantedAt sets the "granted_at" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertOne) UpdateGrantedAt() *UserQuotaGrantUpsertOne {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateGrantedAt()
	})
}

// Exec executes the query.
func (u *UserQuotaGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserQuotaGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserQuotaGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserQuotaGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserQuotaGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserQuotaGrantCreateBulk is the builder for creating many UserQuotaGrant entities in bulk.
type UserQuotaGrantCreateBulk struct {
	config
	err      error
	builders []*UserQuotaGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the UserQuotaGrant entities in the database.
func (_c *UserQuotaGrantCreateBulk) Save(ctx context.Context) ([]*UserQuotaGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserQuotaGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserQuotaGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserQuotaGrantCreateBulk) SaveX(ctx context.Context) []*UserQuotaGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserQuotaGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserQuotaGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserQuotaGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserQuotaGrantUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserQuotaGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserQuotaGrantUpsertBulk {
	_c.conflict = opts
	return &UserQuotaGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserQuotaGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserQuotaGrantCreateBulk) OnConflictColumns(columns ...string) *UserQuotaGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserQuotaGrantUpsertBulk{
		create: _c,
	}
}

// UserQuotaGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of UserQuotaGrant nodes.
type UserQuotaGrantUpsertBulk struct {
	create *UserQuotaGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserQuotaGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserQuotaGrantUpsertBulk) UpdateNewValues() *UserQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userquotagrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserQuotaGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserQuotaGrantUpsertBulk) Ignore() *UserQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserQuotaGrantUpsertBulk) DoNothing() *UserQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserQuotaGrantCreateBulk.OnConflict
// documentation for more info.
func (u *UserQuotaGrantUpsertBulk) Update(set func(*UserQuotaGrantUpsert)) *UserQuotaGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserQuotaGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserQuotaGrantUpsertBulk) SetUserID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateUserID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGrantType sets the "grant_type" field.
func (u *UserQuotaGrantUpsertBulk) SetGrantType(v string) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetGrantType(v)
	})
}

// UpdateGrantType sets the "grant_type" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateGrantType() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateGrantType()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *UserQuotaGrantUpsertBulk) SetPaymentOrderID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdatePaymentOrderID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *UserQuotaGrantUpsertBulk) ClearPaymentOrderID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *UserQuotaGrantUpsertBulk) SetRedeemCodeID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateRedeemCodeID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *UserQuotaGrantUpsertBulk) ClearRedeemCodeID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetPromoCodeUsageID sets the "promo_code_usage_id" field.
func (u *UserQuotaGrantUpsertBulk) SetPromoCodeUsageID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetPromoCodeUsageID(v)
	})
}

// UpdatePromoCodeUsageID sets the "promo_code_usage_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdatePromoCodeUsageID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdatePromoCodeUsageID()
	})
}

// ClearPromoCodeUsageID clears the value of the "promo_code_usage_id" field.
func (u *UserQuotaGrantUpsertBulk) ClearPromoCodeUsageID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearPromoCodeUsageID()
	})
}

// SetAffiliateLedgerID sets the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsertBulk) SetAffiliateLedgerID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetAffiliateLedgerID(v)
	})
}

// AddAffiliateLedgerID adds v to the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsertBulk) AddAffiliateLedgerID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.AddAffiliateLedgerID(v)
	})
}

// UpdateAffiliateLedgerID sets the "affiliate_ledger_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateAffiliateLedgerID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateAffiliateLedgerID()
	})
}

// ClearAffiliateLedgerID clears the value of the "affiliate_ledger_id" field.
func (u *UserQuotaGrantUpsertBulk) ClearAffiliateLedgerID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearAffiliateLedgerID()
	})
}

// SetPaidQuotaUsd sets the "paid_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetPaidQuotaUsd(v)
	})
}

// UpdatePaidQuotaUsd sets the "paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdatePaidQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdatePaidQuotaUsd()
	})
}

// SetGiftQuotaUsd sets the "gift_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetGiftQuotaUsd(v)
	})
}

// UpdateGiftQuotaUsd sets the "gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateGiftQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateGiftQuotaUsd()
	})
}

// SetTotalQuotaUsd sets the "total_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetTotalQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetTotalQuotaUsd(v)
	})
}

// UpdateTotalQuotaUsd sets the "total_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateTotalQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateTotalQuotaUsd()
	})
}

// SetConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetConsumedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetConsumedPaidQuotaUsd(v)
	})
}

// UpdateConsumedPaidQuotaUsd sets the "consumed_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateConsumedPaidQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateConsumedPaidQuotaUsd()
	})
}

// SetConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetConsumedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetConsumedGiftQuotaUsd(v)
	})
}

// UpdateConsumedGiftQuotaUsd sets the "consumed_gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateConsumedGiftQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateConsumedGiftQuotaUsd()
	})
}

// SetRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetRefundedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetRefundedPaidQuotaUsd(v)
	})
}

// UpdateRefundedPaidQuotaUsd sets the "refunded_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateRefundedPaidQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateRefundedPaidQuotaUsd()
	})
}

// SetDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetDeductedGiftQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetDeductedGiftQuotaUsd(v)
	})
}

// UpdateDeductedGiftQuotaUsd sets the "deducted_gift_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateDeductedGiftQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateDeductedGiftQuotaUsd()
	})
}

// SetReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetReservedPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetReservedPaidQuotaUsd(v)
	})
}

// UpdateReservedPaidQuotaUsd sets the "reserved_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateReservedPaidQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateReservedPaidQuotaUsd()
	})
}

// SetLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field.
func (u *UserQuotaGrantUpsertBulk) SetLegacyDebtOffsetPaidQuotaUsd(v decimal.Decimal) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetLegacyDebtOffsetPaidQuotaUsd(v)
	})
}

// UpdateLegacyDebtOffsetPaidQuotaUsd sets the "legacy_debt_offset_paid_quota_usd" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateLegacyDebtOffsetPaidQuotaUsd() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateLegacyDebtOffsetPaidQuotaUsd()
	})
}

// SetOperatorUserID sets the "operator_user_id" field.
func (u *UserQuotaGrantUpsertBulk) SetOperatorUserID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetOperatorUserID(v)
	})
}

// AddOperatorUserID adds v to the "operator_user_id" field.
func (u *UserQuotaGrantUpsertBulk) AddOperatorUserID(v int64) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.AddOperatorUserID(v)
	})
}

// UpdateOperatorUserID sets the "operator_user_id" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateOperatorUserID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateOperatorUserID()
	})
}

// ClearOperatorUserID clears the value of the "operator_user_id" field.
func (u *UserQuotaGrantUpsertBulk) ClearOperatorUserID() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearOperatorUserID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *UserQuotaGrantUpsertBulk) SetIdempotencyKey(v string) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateIdempotencyKey() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *UserQuotaGrantUpsertBulk) ClearIdempotencyKey() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetRuleSnapshot sets the "rule_snapshot" field.
func (u *UserQuotaGrantUpsertBulk) SetRuleSnapshot(v map[string]interface{}) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetRuleSnapshot(v)
	})
}

// UpdateRuleSnapshot sets the "rule_snapshot" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateRuleSnapshot() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateRuleSnapshot()
	})
}

// SetNote sets the "note" field.
func (u *UserQuotaGrantUpsertBulk) SetNote(v string) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateNote() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateNote()
	})
}

// SetGrantedAt sets the "granted_at" field.
func (u *UserQuotaGrantUpsertBulk) SetGrantedAt(v time.Time) *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.SetGrantedAt(v)
	})
}

// UpdateGrantedAt sets the "granted_at" field to the value that was provided on create.
func (u *UserQuotaGrantUpsertBulk) UpdateGrantedAt() *UserQuotaGrantUpsertBulk {
	return u.Update(func(s *UserQuotaGrantUpsert) {
		s.UpdateGrantedAt()
	})
}

// Exec executes the query.
func (u *UserQuotaGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserQuotaGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserQuotaGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserQuotaGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
