// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userwallet"
)

// UserWallet is the model entity for the UserWallet schema.
type UserWallet struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CashBalanceCny holds the value of the "cash_balance_cny" field.
	CashBalanceCny float64 `json:"cash_balance_cny,omitempty"`
	// PaidQuotaBalanceUsd holds the value of the "paid_quota_balance_usd" field.
	PaidQuotaBalanceUsd float64 `json:"paid_quota_balance_usd,omitempty"`
	// GiftQuotaBalanceUsd holds the value of the "gift_quota_balance_usd" field.
	GiftQuotaBalanceUsd float64 `json:"gift_quota_balance_usd,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserWalletQuery when eager-loading is set.
	Edges        UserWalletEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserWalletEdges holds the relations/edges for other nodes in the graph.
type UserWalletEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserWalletEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserWallet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userwallet.FieldCashBalanceCny, userwallet.FieldPaidQuotaBalanceUsd, userwallet.FieldGiftQuotaBalanceUsd:
			values[i] = new(sql.NullFloat64)
		case userwallet.FieldID, userwallet.FieldUserID, userwallet.FieldVersion:
			values[i] = new(sql.NullInt64)
		case userwallet.FieldCreatedAt, userwallet.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserWallet fields.
func (_m *UserWallet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userwallet.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userwallet.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userwallet.FieldCashBalanceCny:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cash_balance_cny", values[i])
			} else if value.Valid {
				_m.CashBalanceCny = value.Float64
			}
		case userwallet.FieldPaidQuotaBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_quota_balance_usd", values[i])
			} else if value.Valid {
				_m.PaidQuotaBalanceUsd = value.Float64
			}
		case userwallet.FieldGiftQuotaBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field gift_quota_balance_usd", values[i])
			} else if value.Valid {
				_m.GiftQuotaBalanceUsd = value.Float64
			}
		case userwallet.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case userwallet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userwallet.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserWallet.
// This includes values selected through modifiers, order, etc.
func (_m *UserWallet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserWallet entity.
func (_m *UserWallet) QueryUser() *UserQuery {
	return NewUserWalletClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserWallet.
// Note that you need to call UserWallet.Unwrap() before calling this method if this UserWallet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserWallet) Update() *UserWalletUpdateOne {
	return NewUserWalletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserWallet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserWallet) Unwrap() *UserWallet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserWallet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserWallet) String() string {
	var builder strings.Builder
	builder.WriteString("UserWallet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("cash_balance_cny=")
	builder.WriteString(fmt.Sprintf("%v", _m.CashBalanceCny))
	builder.WriteString(", ")
	builder.WriteString("paid_quota_balance_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaidQuotaBalanceUsd))
	builder.WriteString(", ")
	builder.WriteString("gift_quota_balance_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.GiftQuotaBalanceUsd))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserWallets is a parsable slice of UserWallet.
type UserWallets []*UserWallet
