import { describe, expect, it, vi, beforeEach } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import { nextTick } from 'vue'
import AccountProfitabilityView from '../AccountProfitabilityView.vue'
const getReport = vi.hoisted(() => vi.fn())
vi.mock('@/api/admin', () => ({ adminAPI: { accountFinancial: { getReport } } }))
const messages: Record<string, string> = { 'admin.accountProfitability.title': '账号盈利', 'admin.accountProfitability.description': '原生用量经营指标', 'admin.accountProfitability.ranges.today': '今日', 'admin.accountProfitability.ranges.24h': '24 小时', 'admin.accountProfitability.ranges.7d': '7 天', 'admin.accountProfitability.ranges.31d': '31 天', 'admin.accountProfitability.loading': '加载中', 'admin.accountProfitability.refreshing': '刷新中', 'admin.accountProfitability.empty': '暂无用量', 'admin.accountProfitability.loadError': '加载失败', 'admin.accountProfitability.retry': '重试', 'admin.accountProfitability.scope.label': '经营维度', 'admin.accountProfitability.scope.all': '全站', 'admin.accountProfitability.scope.unassigned': '未归属', 'admin.accountProfitability.scope.groupSummary': '分组摘要', 'admin.accountProfitability.scope.accountCount': '{count} 个账号', 'admin.accountProfitability.summary.requests': '请求数', 'admin.accountProfitability.summary.tokens': 'Token', 'admin.accountProfitability.summary.accountCost': '账号成本', 'admin.accountProfitability.summary.userCost': '用户扣费', 'admin.accountProfitability.summary.profit': '利润', 'admin.accountProfitability.summary.margin': '利润率', 'admin.accountProfitability.summary.unconsumedBalance': '用户未消费余额', 'admin.accountProfitability.columns.account': '账号', 'admin.accountProfitability.columns.requests': '请求数', 'admin.accountProfitability.columns.tokens': 'Token', 'admin.accountProfitability.columns.accountCost': '账号成本', 'admin.accountProfitability.columns.userCost': '用户扣费', 'admin.accountProfitability.columns.profit': '利润', 'admin.accountProfitability.columns.margin': '利润率', 'common.refresh': '刷新' }
vi.mock('vue-i18n', async (importOriginal) => ({ ...(await importOriginal<typeof import('vue-i18n')>()), useI18n: () => ({ t: (key: string, params?: Record<string, unknown>) => (messages[key] ?? key).replace('{count}', String(params?.count ?? '')) }) }))
const amounts = (requests = 2, tokens = 10) => ({ requests, tokens, cost: 0.000123, user_cost: 0.000456, profit: 0.000333, margin: null as number | null })
const nativeReport = () => ({ generated_at: '2026-08-12T10:00:00Z', range: 'today' as const, currency: 'USD' as const, summary: amounts(), accounts: [{ id: 7, name: 'Native', type: 'api_key', platform: 'sub', historical: false, amounts: amounts() }], groups: [{ id: 10, name: 'Pro', unassigned: false, historical: false, amounts: amounts(), accounts: [{ id: 7, name: 'Native', type: 'api_key', platform: 'sub', historical: false, amounts: amounts() }] }], user_unconsumed_balance_cny: 90 })
const mountPage = () => mount(AccountProfitabilityView, { global: { stubs: { AppLayout: { template: '<div><slot /></div>' } } } })
describe('AccountProfitabilityView', () => {
  beforeEach(() => { getReport.mockReset().mockResolvedValue(nativeReport()) })
  it('shows loading before first response and seven cards after native success', async () => { getReport.mockReturnValueOnce(new Promise(() => undefined)); const wrapper = mountPage(); await nextTick(); expect(wrapper.get('[data-test="financial-loading"]')).toBeTruthy(); wrapper.unmount(); const ready = mountPage(); await flushPromises(); expect(ready.findAll('[data-test^="summary-"]').length).toBe(7); expect(ready.get('[data-test="summary-unconsumed-balance"]').text()).toContain('90') })
  it('renders native table columns, tiny USD values and null margin dash', async () => { const wrapper = mountPage(); await flushPromises(); expect(wrapper.findAll('th').map(h => h.text())).toEqual(['账号', '请求数', 'Token', '账号成本', '用户扣费', '利润', '利润率']); expect(wrapper.get('[data-test="account-financial-7"]').text()).toContain('$0.000123'); expect(wrapper.get('[data-test="account-financial-7"]').text()).toContain('—') })
  it('shows empty state for zero native usage despite CNY balance', async () => { getReport.mockResolvedValueOnce({ ...nativeReport(), summary: { requests: 0, tokens: 0, cost: 0, user_cost: 0, profit: 0, margin: null }, accounts: [], groups: [], user_unconsumed_balance_cny: 90 }); const wrapper = mountPage(); await flushPromises(); expect(wrapper.get('[data-test="financial-empty"]')).toBeTruthy(); expect(wrapper.get('[data-test="summary-unconsumed-balance"]').text()).toContain('90') })
  it('shows error and retry without fabricated success cards', async () => { getReport.mockRejectedValueOnce(new Error('x')); const wrapper = mountPage(); await flushPromises(); expect(wrapper.get('[data-test="financial-load-error"]')).toBeTruthy(); expect(wrapper.get('[data-test="financial-retry"]')).toBeTruthy() })
  it('uses latest request response when ranges resolve out of order', async () => { let resolveOld!: (v: any) => void; let resolveNew!: (v: any) => void; getReport.mockReturnValueOnce(new Promise(r => { resolveOld = r })).mockReturnValueOnce(new Promise(r => { resolveNew = r })); const wrapper = mountPage(); await wrapper.get('[data-test="range-7d"]').trigger('click'); resolveOld({ ...nativeReport(), range: 'today', generated_at: '2026-08-12T10:00:00Z' }); resolveNew({ ...nativeReport(), range: '7d', generated_at: '2026-08-13T10:00:00Z' }); await flushPromises(); expect(wrapper.get('[data-test="range-7d"]').classes()).toContain('bg-primary-600') })
  it('refreshes through getReport only and has no legacy controls or forbidden source strings', async () => { const wrapper = mountPage(); await flushPromises(); await wrapper.get('[data-test="financial-refresh"]').trigger('click'); expect(getReport).toHaveBeenCalledTimes(2); expect(wrapper.find('input').exists()).toBe(false); expect(wrapper.text()).not.toContain('异常流水'); expect(AccountProfitabilityView.__file ?? '').toBeTruthy() })
})
