// Code generated by ent, DO NOT EDIT.

package userquotagrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUserID, v))
}

// GrantType applies equality check predicate on the "grant_type" field. It's identical to GrantTypeEQ.
func GrantType(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldGrantType, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldPaymentOrderID, v))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldRedeemCodeID, v))
}

// PromoCodeUsageID applies equality check predicate on the "promo_code_usage_id" field. It's identical to PromoCodeUsageIDEQ.
func PromoCodeUsageID(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldPromoCodeUsageID, v))
}

// AffiliateLedgerID applies equality check predicate on the "affiliate_ledger_id" field. It's identical to AffiliateLedgerIDEQ.
func AffiliateLedgerID(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldAffiliateLedgerID, v))
}

// PaidQuotaUsd applies equality check predicate on the "paid_quota_usd" field. It's identical to PaidQuotaUsdEQ.
func PaidQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldPaidQuotaUsd, v))
}

// GiftQuotaUsd applies equality check predicate on the "gift_quota_usd" field. It's identical to GiftQuotaUsdEQ.
func GiftQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldGiftQuotaUsd, v))
}

// TotalQuotaUsd applies equality check predicate on the "total_quota_usd" field. It's identical to TotalQuotaUsdEQ.
func TotalQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldTotalQuotaUsd, v))
}

// ConsumedPaidQuotaUsd applies equality check predicate on the "consumed_paid_quota_usd" field. It's identical to ConsumedPaidQuotaUsdEQ.
func ConsumedPaidQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldConsumedPaidQuotaUsd, v))
}

// ConsumedGiftQuotaUsd applies equality check predicate on the "consumed_gift_quota_usd" field. It's identical to ConsumedGiftQuotaUsdEQ.
func ConsumedGiftQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldConsumedGiftQuotaUsd, v))
}

// RefundedPaidQuotaUsd applies equality check predicate on the "refunded_paid_quota_usd" field. It's identical to RefundedPaidQuotaUsdEQ.
func RefundedPaidQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldRefundedPaidQuotaUsd, v))
}

// DeductedGiftQuotaUsd applies equality check predicate on the "deducted_gift_quota_usd" field. It's identical to DeductedGiftQuotaUsdEQ.
func DeductedGiftQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldDeductedGiftQuotaUsd, v))
}

// ReservedPaidQuotaUsd applies equality check predicate on the "reserved_paid_quota_usd" field. It's identical to ReservedPaidQuotaUsdEQ.
func ReservedPaidQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldReservedPaidQuotaUsd, v))
}

// LegacyDebtOffsetPaidQuotaUsd applies equality check predicate on the "legacy_debt_offset_paid_quota_usd" field. It's identical to LegacyDebtOffsetPaidQuotaUsdEQ.
func LegacyDebtOffsetPaidQuotaUsd(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldLegacyDebtOffsetPaidQuotaUsd, v))
}

// OperatorUserID applies equality check predicate on the "operator_user_id" field. It's identical to OperatorUserIDEQ.
func OperatorUserID(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldOperatorUserID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldIdempotencyKey, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldNote, v))
}

// GrantedAt applies equality check predicate on the "granted_at" field. It's identical to GrantedAtEQ.
func GrantedAt(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldGrantedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// GrantTypeEQ applies the EQ predicate on the "grant_type" field.
func GrantTypeEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldGrantType, v))
}

// GrantTypeNEQ applies the NEQ predicate on the "grant_type" field.
func GrantTypeNEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldGrantType, v))
}

// GrantTypeIn applies the In predicate on the "grant_type" field.
func GrantTypeIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldGrantType, vs...))
}

// GrantTypeNotIn applies the NotIn predicate on the "grant_type" field.
func GrantTypeNotIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldGrantType, vs...))
}

// GrantTypeGT applies the GT predicate on the "grant_type" field.
func GrantTypeGT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldGrantType, v))
}

// GrantTypeGTE applies the GTE predicate on the "grant_type" field.
func GrantTypeGTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldGrantType, v))
}

// GrantTypeLT applies the LT predicate on the "grant_type" field.
func GrantTypeLT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldGrantType, v))
}

// GrantTypeLTE applies the LTE predicate on the "grant_type" field.
func GrantTypeLTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldGrantType, v))
}

// GrantTypeContains applies the Contains predicate on the "grant_type" field.
func GrantTypeContains(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContains(FieldGrantType, v))
}

// GrantTypeHasPrefix applies the HasPrefix predicate on the "grant_type" field.
func GrantTypeHasPrefix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasPrefix(FieldGrantType, v))
}

// GrantTypeHasSuffix applies the HasSuffix predicate on the "grant_type" field.
func GrantTypeHasSuffix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasSuffix(FieldGrantType, v))
}

// GrantTypeEqualFold applies the EqualFold predicate on the "grant_type" field.
func GrantTypeEqualFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEqualFold(FieldGrantType, v))
}

// GrantTypeContainsFold applies the ContainsFold predicate on the "grant_type" field.
func GrantTypeContainsFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContainsFold(FieldGrantType, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDIsNil applies the IsNil predicate on the "payment_order_id" field.
func PaymentOrderIDIsNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIsNull(FieldPaymentOrderID))
}

// PaymentOrderIDNotNil applies the NotNil predicate on the "payment_order_id" field.
func PaymentOrderIDNotNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotNull(FieldPaymentOrderID))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDIsNil applies the IsNil predicate on the "redeem_code_id" field.
func RedeemCodeIDIsNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIsNull(FieldRedeemCodeID))
}

// RedeemCodeIDNotNil applies the NotNil predicate on the "redeem_code_id" field.
func RedeemCodeIDNotNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotNull(FieldRedeemCodeID))
}

// PromoCodeUsageIDEQ applies the EQ predicate on the "promo_code_usage_id" field.
func PromoCodeUsageIDEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldPromoCodeUsageID, v))
}

// PromoCodeUsageIDNEQ applies the NEQ predicate on the "promo_code_usage_id" field.
func PromoCodeUsageIDNEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldPromoCodeUsageID, v))
}

// PromoCodeUsageIDIn applies the In predicate on the "promo_code_usage_id" field.
func PromoCodeUsageIDIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldPromoCodeUsageID, vs...))
}

// PromoCodeUsageIDNotIn applies the NotIn predicate on the "promo_code_usage_id" field.
func PromoCodeUsageIDNotIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldPromoCodeUsageID, vs...))
}

// PromoCodeUsageIDIsNil applies the IsNil predicate on the "promo_code_usage_id" field.
func PromoCodeUsageIDIsNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIsNull(FieldPromoCodeUsageID))
}

// PromoCodeUsageIDNotNil applies the NotNil predicate on the "promo_code_usage_id" field.
func PromoCodeUsageIDNotNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotNull(FieldPromoCodeUsageID))
}

// AffiliateLedgerIDEQ applies the EQ predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldAffiliateLedgerID, v))
}

// AffiliateLedgerIDNEQ applies the NEQ predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDNEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldAffiliateLedgerID, v))
}

// AffiliateLedgerIDIn applies the In predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldAffiliateLedgerID, vs...))
}

// AffiliateLedgerIDNotIn applies the NotIn predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDNotIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldAffiliateLedgerID, vs...))
}

// AffiliateLedgerIDGT applies the GT predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDGT(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldAffiliateLedgerID, v))
}

// AffiliateLedgerIDGTE applies the GTE predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDGTE(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldAffiliateLedgerID, v))
}

// AffiliateLedgerIDLT applies the LT predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDLT(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldAffiliateLedgerID, v))
}

// AffiliateLedgerIDLTE applies the LTE predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDLTE(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldAffiliateLedgerID, v))
}

// AffiliateLedgerIDIsNil applies the IsNil predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDIsNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIsNull(FieldAffiliateLedgerID))
}

// AffiliateLedgerIDNotNil applies the NotNil predicate on the "affiliate_ledger_id" field.
func AffiliateLedgerIDNotNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotNull(FieldAffiliateLedgerID))
}

// PaidQuotaUsdEQ applies the EQ predicate on the "paid_quota_usd" field.
func PaidQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldPaidQuotaUsd, v))
}

// PaidQuotaUsdNEQ applies the NEQ predicate on the "paid_quota_usd" field.
func PaidQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldPaidQuotaUsd, v))
}

// PaidQuotaUsdIn applies the In predicate on the "paid_quota_usd" field.
func PaidQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldPaidQuotaUsd, vs...))
}

// PaidQuotaUsdNotIn applies the NotIn predicate on the "paid_quota_usd" field.
func PaidQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldPaidQuotaUsd, vs...))
}

// PaidQuotaUsdGT applies the GT predicate on the "paid_quota_usd" field.
func PaidQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldPaidQuotaUsd, v))
}

// PaidQuotaUsdGTE applies the GTE predicate on the "paid_quota_usd" field.
func PaidQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldPaidQuotaUsd, v))
}

// PaidQuotaUsdLT applies the LT predicate on the "paid_quota_usd" field.
func PaidQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldPaidQuotaUsd, v))
}

// PaidQuotaUsdLTE applies the LTE predicate on the "paid_quota_usd" field.
func PaidQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldPaidQuotaUsd, v))
}

// GiftQuotaUsdEQ applies the EQ predicate on the "gift_quota_usd" field.
func GiftQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldGiftQuotaUsd, v))
}

// GiftQuotaUsdNEQ applies the NEQ predicate on the "gift_quota_usd" field.
func GiftQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldGiftQuotaUsd, v))
}

// GiftQuotaUsdIn applies the In predicate on the "gift_quota_usd" field.
func GiftQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldGiftQuotaUsd, vs...))
}

// GiftQuotaUsdNotIn applies the NotIn predicate on the "gift_quota_usd" field.
func GiftQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldGiftQuotaUsd, vs...))
}

// GiftQuotaUsdGT applies the GT predicate on the "gift_quota_usd" field.
func GiftQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldGiftQuotaUsd, v))
}

// GiftQuotaUsdGTE applies the GTE predicate on the "gift_quota_usd" field.
func GiftQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldGiftQuotaUsd, v))
}

// GiftQuotaUsdLT applies the LT predicate on the "gift_quota_usd" field.
func GiftQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldGiftQuotaUsd, v))
}

// GiftQuotaUsdLTE applies the LTE predicate on the "gift_quota_usd" field.
func GiftQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldGiftQuotaUsd, v))
}

// TotalQuotaUsdEQ applies the EQ predicate on the "total_quota_usd" field.
func TotalQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldTotalQuotaUsd, v))
}

// TotalQuotaUsdNEQ applies the NEQ predicate on the "total_quota_usd" field.
func TotalQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldTotalQuotaUsd, v))
}

// TotalQuotaUsdIn applies the In predicate on the "total_quota_usd" field.
func TotalQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldTotalQuotaUsd, vs...))
}

// TotalQuotaUsdNotIn applies the NotIn predicate on the "total_quota_usd" field.
func TotalQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldTotalQuotaUsd, vs...))
}

// TotalQuotaUsdGT applies the GT predicate on the "total_quota_usd" field.
func TotalQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldTotalQuotaUsd, v))
}

// TotalQuotaUsdGTE applies the GTE predicate on the "total_quota_usd" field.
func TotalQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldTotalQuotaUsd, v))
}

// TotalQuotaUsdLT applies the LT predicate on the "total_quota_usd" field.
func TotalQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldTotalQuotaUsd, v))
}

// TotalQuotaUsdLTE applies the LTE predicate on the "total_quota_usd" field.
func TotalQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldTotalQuotaUsd, v))
}

// ConsumedPaidQuotaUsdEQ applies the EQ predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldConsumedPaidQuotaUsd, v))
}

// ConsumedPaidQuotaUsdNEQ applies the NEQ predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldConsumedPaidQuotaUsd, v))
}

// ConsumedPaidQuotaUsdIn applies the In predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldConsumedPaidQuotaUsd, vs...))
}

// ConsumedPaidQuotaUsdNotIn applies the NotIn predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldConsumedPaidQuotaUsd, vs...))
}

// ConsumedPaidQuotaUsdGT applies the GT predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldConsumedPaidQuotaUsd, v))
}

// ConsumedPaidQuotaUsdGTE applies the GTE predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldConsumedPaidQuotaUsd, v))
}

// ConsumedPaidQuotaUsdLT applies the LT predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldConsumedPaidQuotaUsd, v))
}

// ConsumedPaidQuotaUsdLTE applies the LTE predicate on the "consumed_paid_quota_usd" field.
func ConsumedPaidQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldConsumedPaidQuotaUsd, v))
}

// ConsumedGiftQuotaUsdEQ applies the EQ predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldConsumedGiftQuotaUsd, v))
}

// ConsumedGiftQuotaUsdNEQ applies the NEQ predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldConsumedGiftQuotaUsd, v))
}

// ConsumedGiftQuotaUsdIn applies the In predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldConsumedGiftQuotaUsd, vs...))
}

// ConsumedGiftQuotaUsdNotIn applies the NotIn predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldConsumedGiftQuotaUsd, vs...))
}

// ConsumedGiftQuotaUsdGT applies the GT predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldConsumedGiftQuotaUsd, v))
}

// ConsumedGiftQuotaUsdGTE applies the GTE predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldConsumedGiftQuotaUsd, v))
}

// ConsumedGiftQuotaUsdLT applies the LT predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldConsumedGiftQuotaUsd, v))
}

// ConsumedGiftQuotaUsdLTE applies the LTE predicate on the "consumed_gift_quota_usd" field.
func ConsumedGiftQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldConsumedGiftQuotaUsd, v))
}

// RefundedPaidQuotaUsdEQ applies the EQ predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldRefundedPaidQuotaUsd, v))
}

// RefundedPaidQuotaUsdNEQ applies the NEQ predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldRefundedPaidQuotaUsd, v))
}

// RefundedPaidQuotaUsdIn applies the In predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldRefundedPaidQuotaUsd, vs...))
}

// RefundedPaidQuotaUsdNotIn applies the NotIn predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldRefundedPaidQuotaUsd, vs...))
}

// RefundedPaidQuotaUsdGT applies the GT predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldRefundedPaidQuotaUsd, v))
}

// RefundedPaidQuotaUsdGTE applies the GTE predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldRefundedPaidQuotaUsd, v))
}

// RefundedPaidQuotaUsdLT applies the LT predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldRefundedPaidQuotaUsd, v))
}

// RefundedPaidQuotaUsdLTE applies the LTE predicate on the "refunded_paid_quota_usd" field.
func RefundedPaidQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldRefundedPaidQuotaUsd, v))
}

// DeductedGiftQuotaUsdEQ applies the EQ predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldDeductedGiftQuotaUsd, v))
}

// DeductedGiftQuotaUsdNEQ applies the NEQ predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldDeductedGiftQuotaUsd, v))
}

// DeductedGiftQuotaUsdIn applies the In predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldDeductedGiftQuotaUsd, vs...))
}

// DeductedGiftQuotaUsdNotIn applies the NotIn predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldDeductedGiftQuotaUsd, vs...))
}

// DeductedGiftQuotaUsdGT applies the GT predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldDeductedGiftQuotaUsd, v))
}

// DeductedGiftQuotaUsdGTE applies the GTE predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldDeductedGiftQuotaUsd, v))
}

// DeductedGiftQuotaUsdLT applies the LT predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldDeductedGiftQuotaUsd, v))
}

// DeductedGiftQuotaUsdLTE applies the LTE predicate on the "deducted_gift_quota_usd" field.
func DeductedGiftQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldDeductedGiftQuotaUsd, v))
}

// ReservedPaidQuotaUsdEQ applies the EQ predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldReservedPaidQuotaUsd, v))
}

// ReservedPaidQuotaUsdNEQ applies the NEQ predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldReservedPaidQuotaUsd, v))
}

// ReservedPaidQuotaUsdIn applies the In predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldReservedPaidQuotaUsd, vs...))
}

// ReservedPaidQuotaUsdNotIn applies the NotIn predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldReservedPaidQuotaUsd, vs...))
}

// ReservedPaidQuotaUsdGT applies the GT predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldReservedPaidQuotaUsd, v))
}

// ReservedPaidQuotaUsdGTE applies the GTE predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldReservedPaidQuotaUsd, v))
}

// ReservedPaidQuotaUsdLT applies the LT predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldReservedPaidQuotaUsd, v))
}

// ReservedPaidQuotaUsdLTE applies the LTE predicate on the "reserved_paid_quota_usd" field.
func ReservedPaidQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldReservedPaidQuotaUsd, v))
}

// LegacyDebtOffsetPaidQuotaUsdEQ applies the EQ predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldLegacyDebtOffsetPaidQuotaUsd, v))
}

// LegacyDebtOffsetPaidQuotaUsdNEQ applies the NEQ predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdNEQ(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldLegacyDebtOffsetPaidQuotaUsd, v))
}

// LegacyDebtOffsetPaidQuotaUsdIn applies the In predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldLegacyDebtOffsetPaidQuotaUsd, vs...))
}

// LegacyDebtOffsetPaidQuotaUsdNotIn applies the NotIn predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdNotIn(vs ...decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldLegacyDebtOffsetPaidQuotaUsd, vs...))
}

// LegacyDebtOffsetPaidQuotaUsdGT applies the GT predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdGT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldLegacyDebtOffsetPaidQuotaUsd, v))
}

// LegacyDebtOffsetPaidQuotaUsdGTE applies the GTE predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdGTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldLegacyDebtOffsetPaidQuotaUsd, v))
}

// LegacyDebtOffsetPaidQuotaUsdLT applies the LT predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdLT(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldLegacyDebtOffsetPaidQuotaUsd, v))
}

// LegacyDebtOffsetPaidQuotaUsdLTE applies the LTE predicate on the "legacy_debt_offset_paid_quota_usd" field.
func LegacyDebtOffsetPaidQuotaUsdLTE(v decimal.Decimal) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldLegacyDebtOffsetPaidQuotaUsd, v))
}

// OperatorUserIDEQ applies the EQ predicate on the "operator_user_id" field.
func OperatorUserIDEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldOperatorUserID, v))
}

// OperatorUserIDNEQ applies the NEQ predicate on the "operator_user_id" field.
func OperatorUserIDNEQ(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldOperatorUserID, v))
}

// OperatorUserIDIn applies the In predicate on the "operator_user_id" field.
func OperatorUserIDIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDNotIn applies the NotIn predicate on the "operator_user_id" field.
func OperatorUserIDNotIn(vs ...int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldOperatorUserID, vs...))
}

// OperatorUserIDGT applies the GT predicate on the "operator_user_id" field.
func OperatorUserIDGT(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldOperatorUserID, v))
}

// OperatorUserIDGTE applies the GTE predicate on the "operator_user_id" field.
func OperatorUserIDGTE(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldOperatorUserID, v))
}

// OperatorUserIDLT applies the LT predicate on the "operator_user_id" field.
func OperatorUserIDLT(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldOperatorUserID, v))
}

// OperatorUserIDLTE applies the LTE predicate on the "operator_user_id" field.
func OperatorUserIDLTE(v int64) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldOperatorUserID, v))
}

// OperatorUserIDIsNil applies the IsNil predicate on the "operator_user_id" field.
func OperatorUserIDIsNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIsNull(FieldOperatorUserID))
}

// OperatorUserIDNotNil applies the NotNil predicate on the "operator_user_id" field.
func OperatorUserIDNotNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotNull(FieldOperatorUserID))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldContainsFold(FieldNote, v))
}

// GrantedAtEQ applies the EQ predicate on the "granted_at" field.
func GrantedAtEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldGrantedAt, v))
}

// GrantedAtNEQ applies the NEQ predicate on the "granted_at" field.
func GrantedAtNEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldGrantedAt, v))
}

// GrantedAtIn applies the In predicate on the "granted_at" field.
func GrantedAtIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldGrantedAt, vs...))
}

// GrantedAtNotIn applies the NotIn predicate on the "granted_at" field.
func GrantedAtNotIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldGrantedAt, vs...))
}

// GrantedAtGT applies the GT predicate on the "granted_at" field.
func GrantedAtGT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldGrantedAt, v))
}

// GrantedAtGTE applies the GTE predicate on the "granted_at" field.
func GrantedAtGTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldGrantedAt, v))
}

// GrantedAtLT applies the LT predicate on the "granted_at" field.
func GrantedAtLT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldGrantedAt, v))
}

// GrantedAtLTE applies the LTE predicate on the "granted_at" field.
func GrantedAtLTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldGrantedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentOrder applies the HasEdge predicate on the "payment_order" edge.
func HasPaymentOrder() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PaymentOrderTable, PaymentOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentOrderWith applies the HasEdge predicate on the "payment_order" edge with a given conditions (other predicates).
func HasPaymentOrderWith(preds ...predicate.PaymentOrder) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := newPaymentOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRedeemCode applies the HasEdge predicate on the "redeem_code" edge.
func HasRedeemCode() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RedeemCodeTable, RedeemCodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedeemCodeWith applies the HasEdge predicate on the "redeem_code" edge with a given conditions (other predicates).
func HasRedeemCodeWith(preds ...predicate.RedeemCode) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := newRedeemCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPromoCodeUsage applies the HasEdge predicate on the "promo_code_usage" edge.
func HasPromoCodeUsage() predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromoCodeUsageTable, PromoCodeUsageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromoCodeUsageWith applies the HasEdge predicate on the "promo_code_usage" edge with a given conditions (other predicates).
func HasPromoCodeUsageWith(preds ...predicate.PromoCodeUsage) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(func(s *sql.Selector) {
		step := newPromoCodeUsageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserQuotaGrant) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserQuotaGrant) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserQuotaGrant) predicate.UserQuotaGrant {
	return predicate.UserQuotaGrant(sql.NotPredicates(p))
}
