'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {KeyRound,RefreshCw} from 'lucide-react';
import {Composer} from './parts/composer';
import {ChatStream} from './parts/chat-stream';
import {HistoryRail} from './parts/history-rail';
import {useReferenceImages} from './hooks/use-reference-images';
import {useImagePoller} from './hooks/use-image-poller';
import type {GenerationItem} from './types';
import type {GenerationType} from '@/lib/types';
import type {ImageCapability} from '@/lib/workstation/capabilities';

export function SiteStudio({admin,expiresAt}:{admin:boolean;expiresAt:number}){
 const [key,setKey]=useState(''),[models,setModels]=useState<ImageCapability[]>([]),[model,setModel]=useState(''),[checking,setChecking]=useState(false),[verified,setVerified]=useState(false),[error,setError]=useState('');
 const [prompt,setPrompt]=useState(''),[size,setSize]=useState('auto'),[quality,setQuality]=useState('auto'),[format,setFormat]=useState('png'),[count,setCount]=useState(1),[mode,setMode]=useState<GenerationType>('text_to_image'),[settings,setSettings]=useState(false),[busy,setBusy]=useState(false),[jobs,setJobs]=useState<GenerationItem[]>([]),[zoom,setZoom]=useState<string|null>(null),[now,setNow]=useState(Date.now()),[theme,setTheme]=useState('light'),[inset,setInset]=useState(200);
 const composer=useRef<HTMLDivElement|null>(null),textarea=useRef<HTMLTextAreaElement|null>(null),composing=useRef(false),version=useRef(0);
 const refs=useReferenceImages();const expired=now>=expiresAt;const cap=models.find(m=>m.id===model);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(expired){setKey('');setVerified(false)}},[expired]);
 useEffect(()=>{const initial=new URLSearchParams(location.search).get('theme');if(initial)setTheme(initial);const onMessage=(e:MessageEvent)=>{if(e.origin===location.origin&&e.source===window.parent&&e.data?.type==='xingqiao-theme')setTheme(e.data.theme==='dark'?'dark':'light')};addEventListener('message',onMessage);return()=>removeEventListener('message',onMessage)},[]);
 useEffect(()=>{if(!composer.current)return;const observer=new ResizeObserver(()=>setInset(composer.current?.offsetHeight||200));observer.observe(composer.current);return()=>observer.disconnect()},[]);
 const update=useCallback((value:GenerationItem)=>setJobs(old=>old.map(j=>j.id===value.id?value:j)),[]);
 useImagePoller({generations:expired?[]:jobs,onUpdate:update});
 const history=useMemo(()=>jobs.flatMap(g=>g.images.map(i=>({...i,createdAt:g.createdAt,generation:g}))).reverse(),[jobs]);
 function choose(id:string){const c=models.find(m=>m.id===id);setModel(id);setSize(c?.sizes[0]||'auto');setQuality(c?.qualities[0]||'auto');setFormat(c?.formats[0]||'png');setCount(1);if(!c?.edit||refs.referenceImages.length>(c?.maxReferences||0)){refs.clear();setMode('text_to_image')}}
 async function verify(){if(!key.trim()||checking||expired)return;const current=++version.current;setChecking(true);setError('');setVerified(false);try{const r=await fetch('/image-workstation/api/provider-models/probe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:key.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'无法读取模型列表');if(current!==version.current)return;const list=d.models as ImageCapability[];setModels(list);const c=list.find(m=>m.id===model);setModel(c?.id||'');setSize(c?.sizes[0]||'auto');setQuality(c?.qualities[0]||'auto');setFormat(c?.formats[0]||'png');setCount(1);setVerified(true);if(!list.length)setError('这个 Key 暂无已配置的生图模型，请检查本站分组和模型路由。')}catch(e){if(current===version.current)setError(e instanceof Error?e.message:'加载模型失败')}finally{if(current===version.current)setChecking(false)}}
 function changeKey(value:string){version.current++;setKey(value);setVerified(false);setChecking(false);setModels([]);setModel('')}
 function addFiles(files:File[]|FileList|null){const list=Array.from(files||[]);if(!cap?.edit){setError('请先选择支持图生图的模型');return}if(list.length+refs.referenceImages.length>cap.maxReferences){setError(`当前模型最多支持 ${cap.maxReferences} 张参考图`);return}refs.addFiles(list);setMode('image_to_image')}
 async function useImage(url:string){if(!url.startsWith('/image-workstation/api/workstation/media/')){setError('请从本次图片中选择，或上传本地文件');return}try{const r=await fetch(url);if(!r.ok)throw new Error('图片已过期或暂不可读取');const blob=await r.blob();addFiles([new File([blob],'reference.'+(blob.type.split('/')[1]||'png'),{type:blob.type})])}catch(e){setError(e instanceof Error?e.message:'读取图片失败')}}
 const canSubmit=verified&&!!cap&&!expired&&!busy&&!!prompt.trim()&&(mode==='text_to_image'||refs.referenceImages.length>0);
 async function generate(){if(!canSubmit)return;setBusy(true);setError('');try{const common={providerMode:'custom',model,prompt,size,quality,outputFormat:format,count:mode==='image_to_image'?1:count,generationType:mode,customProvider:{apiKey:key.trim(),baseUrl:'https://site.invalid/v1',model,models:[model],remember:false}};let body:BodyInit,headers:HeadersInit={};if(mode==='image_to_image'){const form=new FormData();Object.entries(common).filter(([k])=>k!=='customProvider').forEach(([k,v])=>form.set(k,String(v)));form.set('customApiKey',key.trim());form.set('customBaseUrl','https://site.invalid/v1');form.set('customModel',model);refs.referenceImages.forEach(i=>{if(i.file)form.append('images',i.file)});body=form}else{body=JSON.stringify(common);headers={'Content-Type':'application/json'}}const r=await fetch('/image-workstation/api/generate',{method:'POST',headers,body});const d=await r.json();if(!r.ok)throw new Error(d.error||'提交失败');setJobs(old=>[...old,d.data.generation]);setPrompt('');refs.clear();setMode('text_to_image')}catch(e){setError(e instanceof Error?e.message:'提交失败')}finally{setBusy(false)}}
 function reuse(g:GenerationItem){setPrompt(g.prompt);const c=models.find(m=>m.id===g.model);if(!c){setError('当前 Key 不含原模型，已复用提示词');return}choose(g.model);if(c.sizes.includes(g.size)||c.customSize)setSize(g.size);if(g.quality&&c.qualities.includes(g.quality))setQuality(g.quality);if(g.outputFormat&&c.formats.includes(g.outputFormat))setFormat(g.outputFormat);setCount(Math.min(c.maxCount,g.count))}
 async function download(url:string){const r=await fetch(url);if(!r.ok){setError('图片已过期或下载失败');return}const blob=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=blob;a.download='xingqiao-'+Date.now()+'.'+(url.split('.').pop()||'png');a.click();setTimeout(()=>URL.revokeObjectURL(blob),1000)}
 async function cancel(g:GenerationItem){const r=await fetch(`/image-workstation/api/me/generations/${g.id}`,{method:'DELETE'});if(!r.ok){setError('任务已开始处理，请等待结果');return}update({...g,status:'failed',errorMessage:'已取消'})}
 const sizeOptions=(cap?.sizes||['auto']).map(value=>({value,label:value==='auto'?'自动':value,detail:cap?.family==='grok'&&value!=='auto'?(Number(value.split('x')[0])>1024||Number(value.split('x')[1])>1024?'2K':'1K'):undefined}));
 return <main className="site-native" data-theme={theme}>
  <header className="studio-heading"><div><h1>生图工作站</h1><p>{expired?'会话已到期，请从本站菜单重新打开':'本次创作 · 图片临时保存 6 小时，请及时下载'}</p></div><nav>{admin&&<a href="/image-workstation/admin/generations">管理图片</a>}<a href="/image-workstation/api/workstation/source">源码</a></nav></header>
  <div className="studio-key"><KeyRound size={16}/><input aria-label="本站 API Key" type="password" value={key} autoComplete="off" placeholder="填入本站 Key，自动加载可用模型" onChange={e=>changeKey(e.target.value)} onBlur={()=>{if(!verified)void verify()}} onKeyDown={e=>{if(e.key==='Enter')void verify()}}/><button disabled={!key.trim()||checking||expired} onClick={verify}><RefreshCw size={14} className={checking?'animate-spin':''}/>{checking?'正在加载':verified?`${models.length} 个生图模型`:'加载模型'}</button></div>
  <div className="studio-workspace"><section className="studio-canvas">
   <ChatStream generations={jobs} bottomInset={inset} onZoom={setZoom} onDownload={u=>void download(u)} onUseForEdit={u=>void useImage(u)} onReuseConfig={reuse} onRetry={g=>setPrompt(g.prompt)} onCancel={g=>void cancel(g)}/>
   <Composer ref={textarea} shellRef={composer} prompt={prompt} onChangePrompt={setPrompt} onPaste={e=>{if(e.clipboardData.files.length){e.preventDefault();addFiles(e.clipboardData.files)}}} onCompositionStart={()=>{composing.current=true}} onCompositionEnd={()=>{composing.current=false}} onKeyDownEnter={()=>void generate()} isComposing={()=>composing.current} isPending={busy} error={error||null} onDismissError={()=>setError('')} generationType={mode} onChangeGenerationType={v=>{if(v==='image_to_image'&&!cap?.edit){setError('当前模型不支持图生图');return}setMode(v);if(v==='text_to_image')refs.clear()}} referenceImages={refs.referenceImages} onPickFiles={addFiles} onPickImageUrl={u=>void useImage(u)} onRemoveReference={refs.removeImage} onMoveReference={refs.moveImage} onReorderReference={refs.reorderImage} size={size} sizeSelectValue={cap?.sizes.includes(size)?size:'custom'} onSizeSelect={v=>{if(v==='custom'){setSize('2048x2048');setSettings(true)}else setSize(v)}} sizeOptions={cap?.customSize?[...sizeOptions,{value:'custom',label:'自定义',detail:undefined}]:sizeOptions} showSettings={settings} onToggleSettings={()=>setSettings(v=>!v)} channels={[]} selectedChannelId={null} onChangeChannel={()=>{}} modelOptions={models.map(m=>m.id)} model={model} onChangeModel={choose} providerMode="built_in" activeModel={model} onOpenCustomProviderSettings={()=>{}} onSubmit={()=>void generate()} canSubmit={canSubmit} onClickImageMode={()=>{}}>
    {settings&&<div className="studio-settings"><label>模型<select value={model} onChange={e=>choose(e.target.value)}>{!model&&<option value="">{models.length?'请选择模型':'请先加载模型'}</option>}{models.map(m=><option key={m.id}>{m.id}</option>)}</select></label>{cap?.customSize&&<label>自定义尺寸<input aria-label="自定义尺寸" value={size} onChange={e=>setSize(e.target.value)} placeholder="2048x2048"/></label>}{!!cap?.qualities.length&&<label>质量<select value={quality} onChange={e=>setQuality(e.target.value)}>{cap.qualities.map(v=><option key={v}>{v}</option>)}</select></label>}{!!cap?.formats.length&&<label>格式<select value={format} onChange={e=>setFormat(e.target.value)}>{cap.formats.map(v=><option key={v}>{v}</option>)}</select></label>}{mode==='text_to_image'&&(cap?.maxCount||1)>1&&<label>张数<select value={count} onChange={e=>setCount(Number(e.target.value))}>{Array.from({length:cap?.maxCount||1},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>}<p>{cap?.family==='grok'?'比例和分辨率由本站原生 Grok 适配器按所选尺寸转换。':cap?.family==='compatible'?'该模型使用保守参数，上游默认设置生效。':'只显示当前模型已配置的参数。'}模型权限和费用以本站网关为准。</p></div>}
   </Composer>
  </section><HistoryRail title="本次图片" images={history} onPickImage={setZoom} onUseForEdit={u=>void useImage(u)} onReuseConfig={reuse}/></div>
  {zoom&&<div className="site-zoom" role="dialog" aria-label="图片预览" onClick={()=>setZoom(null)}><button onClick={()=>setZoom(null)}>关闭预览</button><img alt="生成图片" src={zoom}/></div>}
 </main>
}
