server {
  listen 8088;

  location /api/ {
    proxy_set_header Host $host;
    proxy_set_header X-Admin-Lab-Only 1;
    proxy_pass http://admin-lab-api:8080/;
  }

  location /ws/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Admin-Lab-Only 1;
    proxy_pass http://admin-lab-api:8080/;
  }

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Admin-Lab-Only 1;
    proxy_pass http://admin-lab-frontend:4173/;
  }
}
