import { flushPromises, mount } from '@vue/test-utils'
import { readFileSync } from 'node:fs'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import CreateLineKeyDialog from '../CreateLineKeyDialog.vue'
import type { Group } from '@/types'
import type { MonitorV4Group } from '@/features/monitor-v4/types'
const { create } = vi.hoisted(() => ({ create: vi.fn() }))
vi.mock('@/api/keys', () => ({ keysAPI: { create } }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const groups = [{id: 1, name: 'GPT Plus', platform: 'openai', status: 'active', rate_multiplier: 1}, {id: 2, name: 'GPT Budget', platform: 'openai', status: 'active', rate_multiplier: .2}] as Group[]
function render(initialGroupId?: number, attached = false) { return mount(CreateLineKeyDialog, {attachTo: attached ? document.body : undefined, props: { show: true, toolName: 'Codex', groups, metrics: new Map([[1, {success_rate: 97, ttft_p50_ms: 2160, current_operational: false} as MonitorV4Group]]), linkedCounts: new Map([[1, 2]]), rates: {}, initialGroupId }, global: {stubs: { BaseDialog: {template: '<div><slot/><slot name="footer"/></div>'}, Teleport: true }}}) }
beforeEach(() => create.mockReset())
describe('create line key', () => {
  it('applies one type and color hierarchy to all seven field labels and their controls', () => {
    const source = readFileSync('src/features/ai-tools/CreateLineKeyDialog.vue', 'utf8')
    expect(source).toContain('<BaseDialog :show="show" title="创建线路密钥" brand-theme')
    expect(source).toMatch(/\.compact-key-form\{[^}]*font-size:12px;[^}]*color:var\(--xq-secondary\)/)
    expect(source).toMatch(/\.toggle-row\{[^}]*font-weight:500/)
    expect(source).toMatch(/\.xq-control\{[^}]*font-size:14px;[^}]*font-weight:400/)
    expect(source).toMatch(/\.hint\{[^}]*font-size:11px;[^}]*font-weight:400/)
    const wrapper = render()
    expect(wrapper.findAll('.compact-key-form > .field, .compact-key-form > .key-option')).toHaveLength(7)
    wrapper.unmount()
  })
  it('allows unavailable already linked lines and searches supplied choices', async () => {
    const wrapper = render()
    await wrapper.get('[aria-label="选择线路"]').trigger('click')
    expect(wrapper.text()).toContain('关联密钥 2 把')
    expect(wrapper.text()).toContain('97%')
    expect(wrapper.text()).toContain('2.16s')
    await wrapper.get('[aria-label="搜索Codex线路"]').setValue('Plus')
    expect(wrapper.findAll('[role="option"]')).toHaveLength(1)
    await wrapper.get('[role="option"]').trigger('click')
    await wrapper.get('[name="name"]').setValue('工作密钥')
    create.mockResolvedValue({id: 3, group_id: 1, key: 'secret-not-for-display'})
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(create.mock.calls[0].slice(0, 2)).toEqual(['工作密钥', 1])
    expect(wrapper.emitted('created')?.[0]?.[0]).toMatchObject({id: 3})
    expect(wrapper.text()).not.toContain('secret-not-for-display')
  })
  it('retains input on failure and retries with preselected line', async () => {
    const wrapper = render(2)
    await wrapper.get('[name="name"]').setValue('重试密钥')
    create.mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({id: 4})
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('创建失败')
    expect((wrapper.get('[name="name"]').element as HTMLInputElement).value).toBe('重试密钥')
    expect(wrapper.emitted('created')).toBeUndefined()
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(create).toHaveBeenCalledTimes(2)
    expect(create.mock.calls[1].slice(0, 2)).toEqual(['重试密钥', 2])
  })
  it('does not create on cancellation or without a line', async () => {
    const wrapper = render()
    await wrapper.get('[name="name"]').setValue('测试')
    await wrapper.get('form').trigger('submit')
    expect(wrapper.text()).toContain('请选择线路')
    await wrapper.get('[data-test="cancel"]').trigger('click')
    expect(wrapper.emitted('close')).toHaveLength(1)
    expect(create).not.toHaveBeenCalled()
  })
  it('requires the existing minimum custom key length', async () => {
    const wrapper = render(1)
    await wrapper.get('[name="name"]').setValue('custom')
    await wrapper.get('[name="customOn"]').setValue(true)
    await wrapper.get('[name="customKey"]').setValue('abcdefgh12345')
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(create).not.toHaveBeenCalled()
  })
  it('closes line choices on outside click', async () => {
    const wrapper = render()
    await wrapper.get('[aria-label="选择线路"]').trigger('click')
    document.body.dispatchEvent(new MouseEvent('click', {bubbles: true}))
    await flushPromises()
    expect(wrapper.get('[aria-label="选择线路"]').attributes('aria-expanded')).toBe('false')
    wrapper.unmount()
  })
  it('returns focus to trigger after selecting or escaping choices', async () => {
    const wrapper = render(1, true)
    const trigger = wrapper.get('[aria-label="选择线路"]')
    await trigger.trigger('click')
    ;(wrapper.get('[role="option"]').element as HTMLElement).focus()
    await wrapper.get('[role="option"]').trigger('click')
    await flushPromises()
    expect(document.activeElement).toBe(trigger.element)
    await trigger.trigger('click')
    ;(wrapper.get('[aria-label="搜索Codex线路"]').element as HTMLElement).focus()
    await wrapper.get('[aria-label="搜索Codex线路"]').trigger('keydown', {key: 'Escape'})
    await flushPromises()
    expect(document.activeElement).toBe(trigger.element)
    expect(trigger.attributes('aria-expanded')).toBe('false')
    wrapper.unmount()
  })
  it('lets Escape reach dialog when choices are already closed', async () => {
    const wrapper = render(1, true)
    const listener = vi.fn()
    document.addEventListener('keydown', listener)
    await wrapper.get('[aria-label="选择线路"]').trigger('keydown', {key: 'Escape'})
    expect(listener).toHaveBeenCalledTimes(1)
    document.removeEventListener('keydown', listener)
    wrapper.unmount()
  })
  it('rejects expired dates', async () => {
    const wrapper = render(1)
    await wrapper.get('[name="name"]').setValue('expires')
    await wrapper.get('[name="expiresOn"]').setValue(true)
    await wrapper.get('[name="expires"]').setValue('2000-01-01')
    await wrapper.get('form').trigger('submit')
    expect(create).not.toHaveBeenCalled()
    expect(wrapper.get('[role="alert"]').exists()).toBe(true)
  })
  it('disables create without configurable lines', async () => {
    const wrapper = render()
    await wrapper.setProps({groups: []})
    expect(wrapper.get('[type="submit"]').attributes('disabled')).toBeDefined()
  })
  it('uses the shared current-tool options and the effective user rate', async () => {
    const wrapper = render()
    await wrapper.setProps({
      groups: [...groups, { ...groups[0], id: 3, name: 'Claude', platform: 'anthropic' }],
      rates: { 1: 0.8 }
    })
    await wrapper.get('[aria-label="选择线路"]').trigger('click')
    expect(wrapper.text()).toContain('0.8倍率')
    expect(wrapper.text()).not.toContain('Claude')
  })
  it('sends enabled limits and omits switched off custom key', async () => {
    const wrapper = render(1)
    await wrapper.get('[name="name"]').setValue('限制密钥')
    await wrapper.get('[name="customOn"]').setValue(true)
    await wrapper.get('[name="customKey"]').setValue('custom_key_123')
    await wrapper.get('[name="customOn"]').setValue(false)
    await wrapper.get('[name="ipOn"]').setValue(true)
    await wrapper.get('[name="whitelist"]').setValue('192.168.1.1, 10.0.0.0/8')
    await wrapper.get('[name="blacklist"]').setValue('192.168.1.2')
    await wrapper.get('[name="quota"]').setValue(20)
    await wrapper.get('[name="rateOn"]').setValue(true)
    await wrapper.get('[name="rate5h"]').setValue(5)
    create.mockResolvedValue({id: 5})
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(create).toHaveBeenCalledWith('限制密钥', 1, undefined, ['192.168.1.1', '10.0.0.0/8'], ['192.168.1.2'], 20, undefined, {rate_limit_5h: 5, rate_limit_1d: 0, rate_limit_7d: 0})
  })
})
