#!/usr/bin/env ruby
# frozen_string_literal: true

require "bigdecimal"
require "digest"
require "json"
require "optparse"
require "securerandom"
require "time"
require_relative "validate-upstream"

class ManualLedger
  EVENT_TYPES = %w[
    ledger_opened payment_received balance_adjustment refund_recorded
    usage_snapshot incident_recorded
  ].freeze
  RESERVED_BUILD_KEYS = %w[schema_version sequence previous_hash event_hash].freeze
  HASH_PATTERN = /\A[0-9a-f]{64}\z/.freeze
  ID_PATTERN = /\A[A-Z][A-Z0-9-]{5,100}\z/.freeze
  TIME_PATTERN = /\A\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\z/.freeze
  APPLIED_STATUS = {
    "simulation" => "simulated",
    "real" => "succeeded"
  }.freeze

  class ValidationError < StandardError
    attr_reader :errors

    def initialize(errors)
      @errors = errors
      super(errors.join("; "))
    end
  end

  class << self
    def build_event(existing_events, payload)
      unless payload.is_a?(Hash)
        raise ValidationError, ["event: must be a mapping"]
      end
      reserved = payload.keys.map(&:to_s) & RESERVED_BUILD_KEYS
      unless reserved.empty?
        raise ValidationError, reserved.map { |key| "event.#{key}: is generated by the ledger" }
      end

      event = {
        "schema_version" => 1,
        "sequence" => existing_events.length + 1
      }.merge(deep_copy(payload))
      event["previous_hash"] = existing_events.empty? ? "GENESIS" : existing_events.last["event_hash"]
      event["event_hash"] = canonical_hash(event)

      errors = verify(existing_events + [event])
      raise ValidationError, errors unless errors.empty?

      event
    end

    def verify(events)
      validator = Validator.new(events)
      validator.errors
    end

    def summary(events)
      errors = verify(events)
      raise ValidationError, errors unless errors.empty?

      header = events.first
      mode = header["mode"]
      applied_status = APPLIED_STATUS.fetch(mode)
      payments = events.select { |event| event["event_type"] == "payment_received" }
      adjustments = events.select { |event| event["event_type"] == "balance_adjustment" }
      applied = adjustments.select { |event| event["status"] == applied_status }
      refunds = events.select { |event| event["event_type"] == "refund_recorded" }
      usage = events.select { |event| event["event_type"] == "usage_snapshot" }

      expected = sum_decimal(payments, "expected_balance_usd")
      added = sum_decimal(applied.select { |event| event["operation"] == "add" }, "amount_usd")
      subtracted = sum_decimal(applied.select { |event| event["operation"] == "subtract" }, "amount_usd")
      credited_by_payment = Hash.new { |hash, key| hash[key] = BigDecimal("0") }
      applied.each do |event|
        next unless event["operation"] == "add"

        credited_by_payment[event["reference_event_id"]] += decimal(event["amount_usd"])
      end
      unreconciled = payments.each_with_object([]) do |payment, result|
        delta = credited_by_payment[payment["event_id"]] - decimal(payment["expected_balance_usd"])
        result << payment["order_id"] if delta.abs > BigDecimal("0.00000001")
      end

      {
        "ledger_id" => header["ledger_id"],
        "mode" => mode,
        "event_count" => events.length,
        "payment_received_cny" => number(sum_decimal(payments, "amount_cny")),
        "expected_balance_usd" => number(expected),
        "balance_added_usd" => number(added),
        "balance_subtracted_usd" => number(subtracted),
        "net_balance_adjustment_usd" => number(added - subtracted),
        "payment_credit_variance_usd" => number(added - expected),
        "refund_recorded_cny" => number(sum_decimal(refunds, "amount_cny")),
        "site_usage_usd" => number(sum_decimal(usage, "site_usage_usd")),
        "upstream_cost_cny" => number(sum_decimal(usage, "upstream_cost_cny")),
        "request_count" => usage.sum { |event| event["request_count"] },
        "pending_adjustment_count" => adjustments.count { |event| event["status"] == "pending" },
        "failed_adjustment_count" => adjustments.count { |event| event["status"] == "failed" },
        "unreconciled_order_ids" => unreconciled
      }
    end

    def request_preview(event)
      unless event.is_a?(Hash) && event["event_type"] == "balance_adjustment"
        raise ValidationError, ["event: must be a balance_adjustment"]
      end
      errors = []
      errors << "event.event_id: is required" unless event["event_id"].is_a?(String) && !event["event_id"].empty?
      errors << "event.sub2api_user_id: must be a positive integer" unless event["sub2api_user_id"].is_a?(Integer) && event["sub2api_user_id"].positive?
      errors << "event.operation: must be add or subtract" unless %w[add subtract].include?(event["operation"])
      errors << "event.amount_usd: must be a positive number" unless event["amount_usd"].is_a?(Numeric) && event["amount_usd"].finite? && event["amount_usd"].positive?
      unless event["idempotency_key"].is_a?(String) && event["idempotency_key"].match?(/\A[a-zA-Z0-9][a-zA-Z0-9._:-]{7,127}\z/)
        errors << "event.idempotency_key: has an invalid format"
      end
      raise ValidationError, errors unless errors.empty?

      {
        "method" => "POST",
        "path" => "/api/v1/admin/users/#{event['sub2api_user_id']}/balance",
        "headers" => {
          "Idempotency-Key" => event["idempotency_key"],
          "Content-Type" => "application/json"
        },
        "body" => {
          "balance" => event["amount_usd"],
          "operation" => event["operation"],
          "notes" => "ledger event #{event['event_id']}"
        }
      }
    end

    def canonical_hash(event)
      payload = deep_copy(event)
      payload.delete("event_hash")
      Digest::SHA256.hexdigest(JSON.generate(deep_sort(payload)))
    end

    def parse_jsonl(content, source: "ledger")
      events = []
      errors = []
      content.each_line.with_index(1) do |line, line_number|
        next if line.strip.empty?

        begin
          parsed = JSON.parse(line)
          if parsed.is_a?(Hash)
            events << parsed
          else
            errors << "#{source}:#{line_number}: event must be a JSON object"
          end
        rescue JSON::ParserError => e
          errors << "#{source}:#{line_number}: invalid JSON: #{e.message}"
        end
      end
      errors << "#{source}: ledger is empty" if events.empty? && errors.empty?
      raise ValidationError, errors unless errors.empty?

      events
    end

    private

    def deep_copy(value)
      Marshal.load(Marshal.dump(value))
    end

    def deep_sort(value)
      case value
      when Hash
        value.keys.map(&:to_s).sort.each_with_object({}) do |key, result|
          original_key = value.key?(key) ? key : value.keys.find { |candidate| candidate.to_s == key }
          result[key] = deep_sort(value[original_key])
        end
      when Array
        value.map { |item| deep_sort(item) }
      else
        value
      end
    end

    def decimal(value)
      BigDecimal(value.to_s)
    end

    def sum_decimal(events, key)
      events.reduce(BigDecimal("0")) { |sum, event| sum + decimal(event[key]) }
    end

    def number(value)
      value.to_f
    end
  end

  class Validator
    def initialize(events)
      @events = events
      @errors = []
      @event_by_id = {}
      @order_ids = {}
      @external_references = {}
      @idempotency_keys = {}
    end

    def errors
      unless @events.is_a?(Array) && !@events.empty?
        return ["ledger: must contain at least one event"]
      end

      validate_chain
      validate_events
      @errors
    end

    private

    def validate_chain
      expected_previous = "GENESIS"
      @events.each_with_index do |event, index|
        path = "events[#{index}]"
        unless event.is_a?(Hash)
          add(path, "must be a mapping")
          next
        end
        integer(event["schema_version"], "#{path}.schema_version", minimum: 1, maximum: 1)
        integer(event["sequence"], "#{path}.sequence", minimum: index + 1, maximum: index + 1)
        unless event["previous_hash"] == expected_previous
          add("#{path}.previous_hash", "does not continue the hash chain")
        end
        hash_value = event["event_hash"]
        if !hash_value.is_a?(String) || !hash_value.match?(HASH_PATTERN)
          add("#{path}.event_hash", "must be a lowercase SHA-256 hash")
        elsif hash_value != ManualLedger.canonical_hash(event)
          add("#{path}.event_hash", "does not match event content")
        end
        expected_previous = hash_value if hash_value.is_a?(String)
      end
    end

    def validate_events
      header = @events.first
      unless header.is_a?(Hash) && header["event_type"] == "ledger_opened"
        add("events[0].event_type", "must be ledger_opened")
        return
      end
      mode = header["mode"]

      @events.each_with_index do |event, index|
        next unless event.is_a?(Hash)

        path = "events[#{index}]"
        validate_common(event, path)
        scan_secrets(event, path)
        case event["event_type"]
        when "ledger_opened"
          validate_opened(event, path, index)
        when "payment_received"
          validate_payment(event, path)
        when "balance_adjustment"
          validate_adjustment(event, path, mode)
        when "refund_recorded"
          validate_refund(event, path)
        when "usage_snapshot"
          validate_usage(event, path)
        when "incident_recorded"
          validate_incident(event, path)
        end
        @event_by_id[event["event_id"]] = event if event["event_id"].is_a?(String)
      end
    end

    def validate_common(event, path)
      %w[event_id event_type occurred_at operator_ref notes].each do |key|
        required(event, key, "#{path}.#{key}")
      end
      event_id = event["event_id"]
      string(event_id, "#{path}.event_id", pattern: ID_PATTERN)
      if event_id.is_a?(String)
        if @event_by_id.key?(event_id)
          add("#{path}.event_id", "duplicates #{event_id}")
        end
      end
      enum(event["event_type"], "#{path}.event_type", EVENT_TYPES)
      string(event["occurred_at"], "#{path}.occurred_at", pattern: TIME_PATTERN)
      string(event["operator_ref"], "#{path}.operator_ref")
      string(event["notes"], "#{path}.notes")
    end

    def validate_opened(event, path, index)
      add("#{path}.event_type", "ledger_opened is only allowed as the first event") unless index.zero?
      %w[ledger_id mode payment_currency balance_currency].each do |key|
        required(event, key, "#{path}.#{key}")
      end
      string(event["ledger_id"], "#{path}.ledger_id", pattern: ID_PATTERN)
      enum(event["mode"], "#{path}.mode", %w[simulation real])
      enum(event["payment_currency"], "#{path}.payment_currency", ["CNY"])
      enum(event["balance_currency"], "#{path}.balance_currency", ["USD"])
    end

    def validate_payment(event, path)
      %w[
        user_ref order_id amount_cny usd_per_cny expected_balance_usd
        external_reference
      ].each { |key| required(event, key, "#{path}.#{key}") }
      string(event["user_ref"], "#{path}.user_ref", pattern: ID_PATTERN)
      unique_string(event["order_id"], "#{path}.order_id", @order_ids)
      unique_string(event["external_reference"], "#{path}.external_reference", @external_references)
      number(event["amount_cny"], "#{path}.amount_cny", minimum: 0.000001)
      number(event["usd_per_cny"], "#{path}.usd_per_cny", minimum: 0.000001)
      number(event["expected_balance_usd"], "#{path}.expected_balance_usd", minimum: 0.000001)
      if numeric?(event["amount_cny"]) && numeric?(event["usd_per_cny"]) && numeric?(event["expected_balance_usd"])
        expected = decimal(event["amount_cny"]) * decimal(event["usd_per_cny"])
        actual = decimal(event["expected_balance_usd"])
        if (expected - actual).abs > BigDecimal("0.00000001")
          add("#{path}.expected_balance_usd", "must equal amount_cny x usd_per_cny")
        end
      end
    end

    def validate_adjustment(event, path, mode)
      %w[
        user_ref reference_event_id sub2api_user_id operation amount_usd
        idempotency_key status result_reference
      ].each { |key| required(event, key, "#{path}.#{key}") }
      string(event["user_ref"], "#{path}.user_ref", pattern: ID_PATTERN)
      reference = earlier_event(event["reference_event_id"], "#{path}.reference_event_id")
      integer(event["sub2api_user_id"], "#{path}.sub2api_user_id", minimum: 1)
      enum(event["operation"], "#{path}.operation", %w[add subtract])
      number(event["amount_usd"], "#{path}.amount_usd", minimum: 0.000001)
      unique_string(event["idempotency_key"], "#{path}.idempotency_key", @idempotency_keys,
                    pattern: /\A[a-zA-Z0-9][a-zA-Z0-9._:-]{7,127}\z/)
      enum(event["status"], "#{path}.status", %w[simulated pending succeeded failed])
      string(event["result_reference"], "#{path}.result_reference")
      if mode == "simulation" && event["status"] != "simulated"
        add("#{path}.status", "simulation ledger adjustments must use simulated")
      elsif mode == "real" && event["status"] == "simulated"
        add("#{path}.status", "real ledger adjustments cannot use simulated")
      end
      if reference
        if event["operation"] == "add" && reference["event_type"] != "payment_received"
          add("#{path}.reference_event_id", "add must reference a payment_received event")
        end
        if reference["user_ref"] && reference["user_ref"] != event["user_ref"]
          add("#{path}.user_ref", "must match referenced event user_ref")
        end
      end
    end

    def validate_refund(event, path)
      %w[user_ref reference_event_id amount_cny external_reference].each do |key|
        required(event, key, "#{path}.#{key}")
      end
      string(event["user_ref"], "#{path}.user_ref", pattern: ID_PATTERN)
      reference = earlier_event(event["reference_event_id"], "#{path}.reference_event_id")
      if reference && reference["event_type"] != "payment_received"
        add("#{path}.reference_event_id", "refund must reference a payment_received event")
      end
      number(event["amount_cny"], "#{path}.amount_cny", minimum: 0.000001)
      unique_string(event["external_reference"], "#{path}.external_reference", @external_references)
    end

    def validate_usage(event, path)
      %w[period_start period_end site_usage_usd upstream_cost_cny request_count].each do |key|
        required(event, key, "#{path}.#{key}")
      end
      string(event["period_start"], "#{path}.period_start", pattern: TIME_PATTERN)
      string(event["period_end"], "#{path}.period_end", pattern: TIME_PATTERN)
      number(event["site_usage_usd"], "#{path}.site_usage_usd", minimum: 0)
      number(event["upstream_cost_cny"], "#{path}.upstream_cost_cny", minimum: 0)
      integer(event["request_count"], "#{path}.request_count", minimum: 0)
    end

    def validate_incident(event, path)
      %w[incident_id category status].each { |key| required(event, key, "#{path}.#{key}") }
      string(event["incident_id"], "#{path}.incident_id", pattern: ID_PATTERN)
      string(event["category"], "#{path}.category")
      enum(event["status"], "#{path}.status", %w[open resolved])
    end

    def earlier_event(event_id, path)
      unless event_id.is_a?(String) && @event_by_id.key?(event_id)
        add(path, "must reference an earlier event")
        return nil
      end
      @event_by_id[event_id]
    end

    def scan_secrets(value, path)
      case value
      when Hash
        value.each do |raw_key, child|
          key = raw_key.to_s
          child_path = "#{path}.#{key}"
          if key.downcase.match?(UpstreamConfigValidator::FORBIDDEN_CREDENTIAL_KEY)
            add(child_path, "credential fields are forbidden")
          end
          scan_secrets(child, child_path)
        end
      when Array
        value.each_with_index { |child, index| scan_secrets(child, "#{path}[#{index}]") }
      when String
        if UpstreamConfigValidator::SECRET_VALUE_PATTERNS.any? { |pattern| value.match?(pattern) }
          add(path, "value looks like a secret")
        end
      end
    end

    def unique_string(value, path, seen, pattern: nil)
      return unless string(value, path, pattern: pattern)

      if seen.key?(value)
        add(path, "duplicates #{value}")
      else
        seen[value] = true
      end
    end

    def required(hash, key, path)
      add(path, "is required") unless hash.key?(key)
    end

    def string(value, path, pattern: nil)
      unless value.is_a?(String) && !value.strip.empty?
        add(path, "must be a non-empty string") unless value.nil?
        return false
      end
      if pattern && !value.match?(pattern)
        add(path, "has an invalid format")
        return false
      end
      true
    end

    def enum(value, path, allowed)
      return true if allowed.include?(value)

      add(path, "must be one of: #{allowed.join(', ')}") unless value.nil?
      false
    end

    def integer(value, path, minimum: nil, maximum: nil)
      unless value.is_a?(Integer)
        add(path, "must be an integer") unless value.nil?
        return false
      end
      add(path, "must be at least #{minimum}") if minimum && value < minimum
      add(path, "must be at most #{maximum}") if maximum && value > maximum
      true
    end

    def number(value, path, minimum: nil)
      unless numeric?(value)
        add(path, "must be a finite number") unless value.nil?
        return false
      end
      add(path, "must be at least #{minimum}") if minimum && value < minimum
      true
    end

    def numeric?(value)
      value.is_a?(Numeric) && value.finite?
    end

    def decimal(value)
      BigDecimal(value.to_s)
    end

    def add(path, message)
      @errors << "#{path}: #{message}"
    end
  end
end

def load_manual_ledger(path)
  ManualLedger.parse_jsonl(File.read(path), source: path)
end

def manual_ledger_summary_markdown(summary)
  lines = []
  lines << "# Manual Ledger Summary: #{summary['ledger_id']}"
  lines << ""
  lines << "> Mode: `#{summary['mode']}`. A simulation summary is not evidence of payment or balance change."
  lines << ""
  lines << "- Events: #{summary['event_count']}"
  lines << "- Payments received: CNY #{format('%.6f', summary['payment_received_cny'])}"
  lines << "- Expected balance credit: USD #{format('%.8f', summary['expected_balance_usd'])}"
  lines << "- Applied balance add: USD #{format('%.8f', summary['balance_added_usd'])}"
  lines << "- Payment-credit variance: USD #{format('%.8f', summary['payment_credit_variance_usd'])}"
  lines << "- Site usage: USD #{format('%.8f', summary['site_usage_usd'])}"
  lines << "- Upstream cost: CNY #{format('%.6f', summary['upstream_cost_cny'])}"
  lines << "- Unreconciled orders: #{summary['unreconciled_order_ids'].empty? ? 'none' : summary['unreconciled_order_ids'].join(', ')}"
  lines.join("\n") + "\n"
end

def require_local_ledger_path(path)
  return if path&.end_with?(".local.jsonl")

  raise ManualLedger::ValidationError, ["ledger path must end with .local.jsonl for write operations"]
end

if $PROGRAM_NAME == __FILE__
  command = ARGV.shift
  options = { format: "markdown", mode: "simulation" }
  parser = OptionParser.new do |opts|
    opts.banner = "Usage: ruby ops/manual-ledger.rb COMMAND [options]"
    opts.on("--ledger FILE", "Ledger JSONL file") { |value| options[:ledger] = value }
    opts.on("--event FILE", "Event payload JSON file") { |value| options[:event] = value }
    opts.on("--event-id ID", "Existing event ID") { |value| options[:event_id] = value }
    opts.on("--ledger-id ID", "New ledger ID") { |value| options[:ledger_id] = value }
    opts.on("--mode MODE", %w[simulation real], "Ledger mode") { |value| options[:mode] = value }
    opts.on("--operator-ref REF", "Non-sensitive operator reference") { |value| options[:operator_ref] = value }
    opts.on("--format FORMAT", %w[markdown json], "Output format") { |value| options[:format] = value }
  end

  begin
    parser.parse!
    unless options[:ledger] || (command == "request-preview" && options[:event])
      raise OptionParser::MissingArgument, "--ledger"
    end

    case command
    when "init"
      require_local_ledger_path(options[:ledger])
      raise OptionParser::MissingArgument, "--ledger-id" unless options[:ledger_id]
      raise OptionParser::MissingArgument, "--operator-ref" unless options[:operator_ref]
      payload = {
        "event_id" => "EVT-OPEN-#{SecureRandom.hex(6).upcase}",
        "event_type" => "ledger_opened",
        "occurred_at" => Time.now.utc.iso8601,
        "operator_ref" => options[:operator_ref],
        "ledger_id" => options[:ledger_id],
        "mode" => options[:mode],
        "payment_currency" => "CNY",
        "balance_currency" => "USD",
        "notes" => "Ledger initialized locally."
      }
      event = ManualLedger.build_event([], payload)
      File.open(options[:ledger], File::WRONLY | File::CREAT | File::EXCL, 0o600) do |file|
        file.puts(JSON.generate(event))
      end
      puts "initialized #{options[:ledger]}"
    when "append"
      require_local_ledger_path(options[:ledger])
      raise OptionParser::MissingArgument, "--event" unless options[:event]
      File.open(options[:ledger], File::RDWR) do |file|
        file.flock(File::LOCK_EX)
        events = ManualLedger.parse_jsonl(file.read, source: options[:ledger])
        payload = JSON.parse(File.read(options[:event]))
        event = ManualLedger.build_event(events, payload)
        file.seek(0, IO::SEEK_END)
        file.puts(JSON.generate(event))
        file.flush
        file.fsync
        puts "appended #{event['event_id']}"
      end
    when "verify"
      events = load_manual_ledger(options[:ledger])
      errors = ManualLedger.verify(events)
      raise ManualLedger::ValidationError, errors unless errors.empty?
      puts "#{options[:ledger]}: OK (#{events.length} events)"
    when "summary"
      result = ManualLedger.summary(load_manual_ledger(options[:ledger]))
      puts(options[:format] == "json" ? JSON.pretty_generate(result) : manual_ledger_summary_markdown(result))
    when "request-preview"
      if options[:event]
        event = JSON.parse(File.read(options[:event]))
      else
        raise OptionParser::MissingArgument, "--event-id or --event" unless options[:event_id]
        events = load_manual_ledger(options[:ledger])
        errors = ManualLedger.verify(events)
        raise ManualLedger::ValidationError, errors unless errors.empty?
        event = events.find { |candidate| candidate["event_id"] == options[:event_id] }
        raise ManualLedger::ValidationError, ["event not found: #{options[:event_id]}"] unless event
      end
      puts JSON.pretty_generate(ManualLedger.request_preview(event))
    else
      warn parser
      exit 2
    end
  rescue OptionParser::ParseError, Errno::ENOENT, Errno::EACCES, Errno::EEXIST, JSON::ParserError => e
    warn e.message
    exit 2
  rescue ManualLedger::ValidationError => e
    warn "ledger is invalid"
    e.errors.each { |error| warn "  - #{error}" }
    exit 1
  end
end
