<template>
  <AppLayout><main class="mx-auto w-full max-w-[1400px] space-y-5 p-5" data-test="account-profitability-page">
    <header class="flex items-center justify-between gap-3"><div><h1 class="text-2xl font-semibold">{{ t('admin.accountProfitability.title') }}</h1><p class="text-sm text-gray-500">{{ t('admin.accountProfitability.description') }}</p></div><button class="btn btn-secondary" data-test="financial-refresh" @click="load">{{ t('common.refresh') }}</button></header>
    <nav class="flex gap-2" aria-label="range"><button v-for="item in ranges" :key="item" :data-test="`range-${item}`" class="btn btn-secondary" :class="{ 'bg-primary-600 text-white': activeRange === item }" @click="selectRange(item)">{{ t(`admin.accountProfitability.ranges.${item}`) }}</button></nav>
    <div v-if="loading" data-test="financial-loading" class="text-sm text-gray-500">{{ t('admin.accountProfitability.loading') }}</div>
    <div v-if="refreshing" data-test="financial-refreshing" class="text-xs text-gray-500">{{ t('admin.accountProfitability.refreshing') }}</div>
    <div v-if="loadError" class="rounded border border-red-300 bg-red-50 p-3 text-sm text-red-700" data-test="financial-load-error" role="alert"><span>{{ loadError }}</span><button class="btn btn-secondary ml-3" data-test="financial-retry" @click="load">{{ t('admin.accountProfitability.retry') }}</button></div>
    <div class="text-xs text-gray-500" data-test="financial-generated-at">{{ generatedAt }}</div>
    <section v-if="hasLoaded" class="grid grid-cols-2 gap-3 lg:grid-cols-7"><article v-for="card in cards" :key="card.key" class="card p-4" :data-test="`summary-${card.key}`"><div class="text-xs text-gray-500">{{ card.label }}</div><div class="mt-2 text-xl font-semibold">{{ card.value }}</div></article></section>
    <nav class="flex max-w-full gap-2 overflow-x-auto pb-1" :aria-label="t('admin.accountProfitability.scope.label')"><button class="btn btn-secondary shrink-0" data-test="scope-all" :class="{ 'bg-primary-600 text-white': activeScope.kind === 'all' }" @click="activeScope = { kind: 'all' }">{{ t('admin.accountProfitability.scope.all') }}</button><button v-for="group in report.groups" :key="`${group.unassigned ? 'unassigned' : 'group'}-${group.id}`" class="btn btn-secondary shrink-0" :data-test="`scope-group-${group.id}`" :class="{ 'bg-primary-600 text-white': isSelectedGroup(group.id, group.unassigned) }" @click="activeScope = { kind: 'group', id: group.id, unassigned: group.unassigned }">{{ group.unassigned ? t('admin.accountProfitability.scope.unassigned') : group.name }}</button></nav>
    <section v-if="selectedGroup" class="space-y-3" :data-test="`group-summary-${selectedGroup.id}`"><div class="flex flex-wrap items-center justify-between gap-2"><h2 class="text-base font-semibold"><span class="text-gray-500">{{ t('admin.accountProfitability.scope.groupSummary') }}：</span>{{ selectedGroup.unassigned ? t('admin.accountProfitability.scope.unassigned') : selectedGroup.name }}</h2><span class="text-xs text-gray-500">{{ t('admin.accountProfitability.scope.accountCount', { count: selectedAccounts.length }) }}</span></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-6"><article v-for="item in scopedCards" :key="item.key" class="card p-3"><div class="text-xs text-gray-500">{{ item.label }}</div><div class="mt-1 text-base font-semibold">{{ item.value }}</div></article></div></section>
    <div v-if="isEmpty" data-test="financial-empty" class="text-sm text-gray-500">{{ t('admin.accountProfitability.empty') }}</div>
    <section class="table-container overflow-x-auto" data-test="account-financial-table"><table class="table min-w-max"><thead><tr><th>{{ t('admin.accountProfitability.columns.account') }}</th><th>{{ t('admin.accountProfitability.columns.requests') }}</th><th>{{ t('admin.accountProfitability.columns.tokens') }}</th><th>{{ t('admin.accountProfitability.columns.accountCost') }}</th><th>{{ t('admin.accountProfitability.columns.userCost') }}</th><th>{{ t('admin.accountProfitability.columns.profit') }}</th><th>{{ t('admin.accountProfitability.columns.margin') }}</th></tr></thead><tbody><tr v-for="row in selectedAccounts" :key="row.id" :data-test="`account-financial-${row.id}`" :data-pair="`${selectedGroup?.id ?? 'all'}:${row.id}`"><td>{{ row.name }}</td><td>{{ compact(row.amounts.requests) }}</td><td>{{ compact(row.amounts.tokens) }}</td><td>{{ usd(row.amounts.cost) }}</td><td>{{ usd(row.amounts.user_cost) }}</td><td>{{ usd(row.amounts.profit) }}</td><td>{{ percent(row.amounts.margin) }}</td></tr></tbody></table></section>
  </main></AppLayout>
</template>
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { adminAPI } from '@/api/admin'
import type { AccountFinancialReport, FinancialAmounts, FinancialRange } from '@/api/admin/accountFinancial'
import AppLayout from '@/components/layout/AppLayout.vue'
type FinancialScope = { kind: 'all' } | { kind: 'group'; id: number; unassigned: boolean }
const { t } = useI18n(); const activeRange = ref<FinancialRange>('today'); const activeScope = ref<FinancialScope>({ kind: 'all' }); const loading = ref(false); const refreshing = ref(false); const loadError = ref(''); const hasLoaded = ref(false); let requestSequence = 0; let timer: ReturnType<typeof setInterval> | undefined
const emptyReport = (): AccountFinancialReport => ({ generated_at: '', range: 'today', currency: 'USD', summary: { requests: 0, tokens: 0, cost: 0, user_cost: 0, profit: 0, margin: null }, accounts: [], groups: [], user_unconsumed_balance_cny: 0 })
const report = ref<AccountFinancialReport>(emptyReport()); const ranges: FinancialRange[] = ['today', '24h', '7d', '31d']
const generatedAt = computed(() => report.value.generated_at ? new Date(report.value.generated_at).toLocaleString() : '—')
const usd = (value: number) => { if (!Number.isFinite(value)) return '—'; if (value !== 0 && Math.abs(value) < 1e-8) return `${value < 0 ? '-$' : '$'}${Math.abs(value).toExponential(2)}`; return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', minimumFractionDigits: 2, maximumFractionDigits: 8 }).format(value) }
const cny = (value: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: 'CNY', minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value)
const compact = (value: number) => new Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 2 }).format(value)
const percent = (value: number | null) => value == null ? '—' : `${(value * 100).toFixed(1)}%`
const metricCards = (a: FinancialAmounts) => [{ key: 'requests', label: t('admin.accountProfitability.summary.requests'), value: compact(a.requests) }, { key: 'tokens', label: t('admin.accountProfitability.summary.tokens'), value: compact(a.tokens) }, { key: 'cost', label: t('admin.accountProfitability.summary.accountCost'), value: usd(a.cost) }, { key: 'user-cost', label: t('admin.accountProfitability.summary.userCost'), value: usd(a.user_cost) }, { key: 'profit', label: t('admin.accountProfitability.summary.profit'), value: usd(a.profit) }, { key: 'margin', label: t('admin.accountProfitability.summary.margin'), value: percent(a.margin) }]
const cards = computed(() => [...metricCards(report.value.summary), { key: 'unconsumed-balance', label: t('admin.accountProfitability.summary.unconsumedBalance'), value: cny(report.value.user_unconsumed_balance_cny) }]); const selectedGroup = computed(() => { const scope = activeScope.value; return scope.kind === 'group' ? report.value.groups.find(g => g.id === scope.id && g.unassigned === scope.unassigned) : undefined }); const selectedAccounts = computed(() => selectedGroup.value?.accounts ?? report.value.accounts); const selectedAmounts = computed(() => selectedGroup.value?.amounts ?? report.value.summary); const scopedCards = computed(() => metricCards(selectedAmounts.value)); const isSelectedGroup = (id: number, unassigned: boolean) => activeScope.value.kind === 'group' && activeScope.value.id === id && activeScope.value.unassigned === unassigned
const isEmpty = computed(() => hasLoaded.value && report.value.summary.requests === 0 && report.value.summary.tokens === 0 && report.value.accounts.every(a => a.amounts.requests === 0 && a.amounts.tokens === 0) && report.value.groups.every(g => g.amounts.requests === 0 && g.amounts.tokens === 0))
async function load() { const sequence = ++requestSequence; if (hasLoaded.value) refreshing.value = true; else loading.value = true; loadError.value = ''; try { const next = await adminAPI.accountFinancial.getReport({ range: activeRange.value }); if (sequence !== requestSequence) return; report.value = next; hasLoaded.value = true; if (activeScope.value.kind === 'group' && !selectedGroup.value) activeScope.value = { kind: 'all' } } catch { if (sequence === requestSequence) loadError.value = t('admin.accountProfitability.loadError') } finally { if (sequence === requestSequence) { loading.value = false; refreshing.value = false } } }
function selectRange(range: FinancialRange) { activeRange.value = range; void load() }
onMounted(() => { void load(); timer = setInterval(() => void load(), 60_000) }); onUnmounted(() => { if (timer) clearInterval(timer) })
</script>
